Repository pymedusa/Medusa, pull requests merged in 2018-08, with the labels that each got.

#4259 Vueify config-postprocessing
  CHANGELOG.md
  medusa/server/api/v2/config.py
  medusa/server/web/config/post_processing.py
  setup.py
  tests/apiv2/test_config.py
  themes-default/slim/package.json
  themes-default/slim/static/css/dark.css
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/store.js
  themes-default/slim/static/js/templates/name-pattern.vue
  themes-default/slim/test/specs/name-pattern.spec.js
  themes-default/slim/test/specs/snapshots/name-pattern.spec.js.md
  themes-default/slim/test/specs/snapshots/name-pattern.spec.js.snap
  themes-default/slim/views/config_anime.mako
  themes-default/slim/views/config_backuprestore.mako
  themes-default/slim/views/config_general.mako
  themes-default/slim/views/config_notifications.mako
  themes-default/slim/views/config_postProcessing.mako
  themes-default/slim/views/config_providers.mako
  themes-default/slim/views/config_search.mako
  themes-default/slim/views/config_subtitles.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/css/dark.css
  themes/dark/assets/css/style.css
  themes/dark/assets/css/themed.css
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/assets/js/templates/name-pattern.vue
  themes/dark/templates/config_anime.mako
  themes/dark/templates/config_backuprestore.mako
  themes/dark/templates/config_general.mako
  themes/dark/templates/config_notifications.mako
  themes/dark/templates/config_postProcessing.mako
  themes/dark/templates/config_providers.mako
  themes/dark/templates/config_search.mako
  themes/dark/templates/config_subtitles.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/css/dark.css
  themes/light/assets/css/style.css
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/assets/js/templates/name-pattern.vue
  themes/light/templates/config_anime.mako
  themes/light/templates/config_backuprestore.mako
  themes/light/templates/config_general.mako
  themes/light/templates/config_notifications.mako
  themes/light/templates/config_postProcessing.mako
  themes/light/templates/config_providers.mako
  themes/light/templates/config_search.mako
  themes/light/templates/config_subtitles.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded

#4675 Improve multi-episode and season snatches. Fixes #229. Fixes #4750
  CHANGELOG.md
  medusa/classes.py
  medusa/providers/generic_provider.py
  medusa/search/core.py
  medusa/tv/cache.py
Labels: Bug, Concluded, Enhancement, Needs review, Needs testing

#4718 Update root dirs
  themes-default/slim/static/js/templates/root-dirs.vue
  themes-default/slim/test/__fixtures__/root-dirs.json
  themes-default/slim/test/specs/root-dirs.spec.js
  themes-default/slim/test/specs/snapshots/root-dirs.spec.js.md
  themes-default/slim/test/specs/snapshots/root-dirs.spec.js.snap
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/addShows_trendingShows.mako
  themes-default/slim/views/config_general.mako
  themes/dark/assets/js/templates/root-dirs.vue
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/addShows_trendingShows.mako
  themes/dark/templates/config_general.mako
  themes/light/assets/js/templates/root-dirs.vue
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/addShows_trendingShows.mako
  themes/light/templates/config_general.mako
Labels: Concluded

#4843 Update base url to ww3.
  CHANGELOG.md
  medusa/providers/torrent/html/yggtorrent.py
Labels: Bug, Concluded

#4845 Added new config ui components
  themes-default/slim/static/js/templates/config-textbox-number.vue
  themes-default/slim/static/js/templates/config-textbox.vue
  themes-default/slim/static/js/templates/config-toggle-slider.vue
  themes-default/slim/test/specs/config-textbox-number.spec.js
  themes-default/slim/test/specs/config-textbox.spec.js
  themes-default/slim/test/specs/config-toggle-slider.spec.js
  themes-default/slim/test/specs/snapshots/config-textbox-number.spec.js.md
  themes-default/slim/test/specs/snapshots/config-textbox-number.spec.js.snap
  themes-default/slim/test/specs/snapshots/config-textbox.spec.js.md
  themes-default/slim/test/specs/snapshots/config-textbox.spec.js.snap
  themes-default/slim/test/specs/snapshots/config-toggle-slider.spec.js.md
  themes-default/slim/test/specs/snapshots/config-toggle-slider.spec.js.snap
  themes/dark/assets/js/templates/config-checkbox.vue
  themes/dark/assets/js/templates/config-textbox-number.vue
  themes/dark/assets/js/templates/config-textbox.vue
  themes/dark/assets/js/templates/config-toggle-slider.vue
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/templates/config-checkbox.vue
  themes/light/assets/js/templates/config-textbox-number.vue
  themes/light/assets/js/templates/config-textbox.vue
  themes/light/assets/js/templates/config-toggle-slider.vue
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement

#4850 add asset test and update snapshots
  themes-default/slim/static/js/templates/asset.vue
  themes-default/slim/test/specs/asset.spec.js
  themes-default/slim/test/specs/snapshots/app-header.spec.js.snap
  themes-default/slim/test/specs/snapshots/app-link.spec.js.snap
  themes-default/slim/test/specs/snapshots/asset.spec.js.md
  themes-default/slim/test/specs/snapshots/asset.spec.js.snap
  themes-default/slim/test/specs/snapshots/name-pattern.spec.js.md
  themes-default/slim/test/specs/snapshots/name-pattern.spec.js.snap
  themes-default/slim/test/specs/snapshots/root-dirs.spec.js.snap
  themes-default/slim/test/specs/snapshots/scroll-buttons.spec.js.snap
  themes-default/slim/test/specs/snapshots/show-selector.spec.js.md
  themes-default/slim/test/specs/snapshots/show-selector.spec.js.snap
  themes/dark/assets/js/templates/asset.vue
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/templates/asset.vue
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement

#4819 add TV4(se) network logo
  themes-default/slim/static/images/network/tv4-(se).png
  themes/dark/assets/img/network/tv4-(se).png
  themes/light/assets/img/network/tv4-(se).png
Labels: Concluded, Enhancement

#4854 Renovate groups, update vue & vue-test-utils
  renovate.json
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded, Enhancement, Update dep (JS)

#4855 Fix vue test warnings
  themes-default/slim/package.json
  themes-default/slim/static/js/templates/config-textbox-number.vue
  themes-default/slim/static/js/templates/config-textbox.vue
  themes-default/slim/static/js/templates/config-toggle-slider.vue
  themes-default/slim/static/js/templates/index.js
  themes-default/slim/static/js/templates/root-dirs.vue
  themes-default/slim/static/js/templates/select-list.vue
  themes-default/slim/test/specs/config-textbox-number.spec.js
  themes-default/slim/test/specs/config-textbox.spec.js
  themes-default/slim/test/specs/config-toggle-slider.spec.js
  themes-default/slim/test/specs/select-list.spec.js
  themes-default/slim/test/specs/snapshots/config-textbox-number.spec.js.md
  themes-default/slim/test/specs/snapshots/config-textbox-number.spec.js.snap
  themes-default/slim/test/specs/snapshots/config-textbox.spec.js.md
  themes-default/slim/test/specs/snapshots/config-textbox.spec.js.snap
  themes-default/slim/test/specs/snapshots/config-toggle-slider.spec.js.md
  themes-default/slim/test/specs/snapshots/config-toggle-slider.spec.js.snap
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Concluded

#4865 fix paths from src move
  package.json
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
Labels: Bug, Concluded

#4873 configured minimal versions.
  setup.py
Labels: Concluded

#4874 Update Store/WebSocket code
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/webpack.config.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
  themes/light/templates/layouts/main.mako
Labels: Bug, Concluded, Enhancement, Frontend, Priority: 2. Medium

#4886 move shows to store module
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/modules/index.js
  themes-default/slim/src/store/modules/shows.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement

#4872 UI improvements / fixes
  themes-default/slim/.babelrc
  themes-default/slim/package.json
  themes-default/slim/src/app.js
  themes-default/slim/src/components/show-selector.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/src/utils.js
  themes-default/slim/views/config_postProcessing.mako
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/config_postProcessing.mako
  themes/dark/templates/displayShow.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
  themes/light/templates/config_postProcessing.mako
  themes/light/templates/displayShow.mako
  themes/light/templates/layouts/main.mako
Labels: Bug, Concluded, Enhancement

#4891 Fix metadata tab - undefined episode thumbnails example
  themes-default/slim/views/config_postProcessing.mako
  themes/dark/templates/config_postProcessing.mako
  themes/light/templates/config_postProcessing.mako
Labels: Bug, Concluded

#4892 Add missing commas
  medusa/databases/main_db.py
  medusa/tv/episode.py
Labels: Bug, Concluded

#4888 Vueify display show and snatch selection
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/router.js
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/static/js/home/snatch-selection.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/snatchSelection.mako
  themes/dark/assets/js/home/snatch-selection.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/displayShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/assets/js/home/snatch-selection.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
  themes/light/templates/displayShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/snatchSelection.mako
Labels: Concluded, Enhancement, Frontend

#4905 Fix exception when getting full release title for TVChaosUK provider.…
  medusa/providers/torrent/html/tvchaosuk.py
Labels: Bug, Concluded, Needs testing

#4910 Rebuild Webpack bundle
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Concluded

#4822 Feature/upgrade adba to medusa adba
  CHANGELOG.md
  ext/adba/__init__.py
  ext/adba/aniDBAbstracter.py
  ext/adba/aniDBcommands.py
  ext/adba/aniDBerrors.py
  ext/adba/aniDBfileInfo.py
  ext/adba/aniDBlink.py
  ext/adba/aniDBmaper.py
  ext/adba/aniDBresponses.py
  ext/adba/aniDBtvDBmaper.py
  ext/backports/__init__.py
  ext/backports/configparser/__init__.py
  ext/backports/configparser/helpers.py
  ext/configparser.py
  ext/readme.md
  lib/adba/.gitignore
  lib/adba/aniDBfileInfo.py
  lib/adba/aniDBmaper.py
  lib/adba/aniDBtvDBmaper.py
  lib/readme.md
  lib/simpleanidb/__init__.py
  medusa/helpers/anidb.py
  medusa/scene_exceptions.py
  medusa/server/web/home/handler.py
  medusa/show/recommendations/anidb.py
  medusa/show/recommendations/recommended.py
  requirements.txt
Labels: Concluded, Needs review, Needs testing

#4916 Remove puex
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded, Remove dep (JS)

#4925 Fix Yggtorrent provider login, update URL, made future proof. Fixes #4901
  medusa/providers/torrent/html/yggtorrent.py
Labels: Bug, Concluded, Needs review

#4927 Avoid Yggtorrent warning on first auth check
  medusa/providers/torrent/html/yggtorrent.py
Labels: Concluded, Enhancement

#4928 Fix ui not loading using edge browser, when using a reverse proxy
  CHANGELOG.md
  themes-default/slim/src/store/index.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Bug, Concluded, Frontend

#4878 Update vue-loader & enable Webpack builds on Travis
  .github/build-themes-check.sh
  .yarnrc
  themes-default/slim/.yarnrc
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement, Frontend, Update dep (JS)

#4922 Fix config being loaded twice for pages using the main app
  themes-default/slim/src/components/login.vue
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/vendors.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/layouts/main.mako
Labels: Bug, Concluded, Frontend

#4929 Add response verification to BinSearch provider. Fixes #4844
  medusa/providers/nzb/binsearch.py
Labels: Bug, Concluded, Needs review

#4912 Update to Babel 7 (beta)
  renovate.json
  themes-default/slim/.babelrc
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement

#4933 Use indexer ID in get_episode(). Fixes #4857
  CHANGELOG.md
  medusa/tv/series.py
Labels: Bug, Concluded, Needs review, Needs testing

#4935 Convert all SFC to ES6 modules
  themes-default/slim/src/components/add-recommended.vue
  themes-default/slim/src/components/add-shows.vue
  themes-default/slim/src/components/anidb-release-group-ui.vue
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/app-link.vue
  themes-default/slim/src/components/asset.vue
  themes-default/slim/src/components/backstretch.vue
  themes-default/slim/src/components/config-textbox-number.vue
  themes-default/slim/src/components/config-textbox.vue
  themes-default/slim/src/components/config-toggle-slider.vue
  themes-default/slim/src/components/config.vue
  themes-default/slim/src/components/file-browser.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/http/404.vue
  themes-default/slim/src/components/language-select.vue
  themes-default/slim/src/components/login.vue
  themes-default/slim/src/components/name-pattern.vue
  themes-default/slim/src/components/plot-info.vue
  themes-default/slim/src/components/root-dirs.vue
  themes-default/slim/src/components/scroll-buttons.vue
  themes-default/slim/src/components/select-list.vue
  themes-default/slim/src/components/show-selector.vue
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement, Frontend

#4949 convert python truncate to vue
  themes-default/slim/package.json
  themes-default/slim/src/app.js
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/index.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/partials/showheader.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
  themes/light/templates/layouts/main.mako
  themes/light/templates/partials/showheader.mako
Labels: Concluded, Enhancement, Frontend

#4951 Update components & optimize imports/exports
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/app-link.vue
  themes-default/slim/src/components/config-textbox-number.vue
  themes-default/slim/src/components/config-textbox.vue
  themes-default/slim/src/components/config-toggle-slider.vue
  themes-default/slim/src/components/config.vue
  themes-default/slim/src/components/http/index.js
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/root-dirs.vue
  themes-default/slim/src/store/modules/index.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/errorlogs.mako
  themes-default/slim/views/manage_manageSearches.mako
  themes/dark/assets/js/vendors.js
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/errorlogs.mako
  themes/dark/templates/manage_manageSearches.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/errorlogs.mako
  themes/light/templates/manage_manageSearches.mako
Labels: Concluded, Enhancement

#4944 Only check for scene_exception when series_name is known.
  medusa/name_parser/parser.py
  medusa/scene_exceptions.py
Labels: Bug

#4962 Use FileManagerPlugin to copy bundled assets
  themes-default/slim/package.json
  themes-default/slim/webpack.config.js
  themes-default/slim/yarn.lock
Labels: Bug, Concluded, Frontend

#4966 Fix split home in tabs
  themes-default/slim/src/components/home.vue
  themes-default/slim/static/js/common/init.js
  themes-default/slim/views/home.mako
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/home.mako
  themes/light/assets/js/common/init.js
  themes/light/assets/js/vendors.js
  themes/light/templates/home.mako
Labels: Bug, Changelog, Concluded, Frontend

#4964 Fix #4757: Error getting season scene exceptions on show page
  CHANGELOG.md
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Bug, Concluded, Frontend

#4972 Fix test email notification with TLS
  CHANGELOG.md
  themes-default/slim/static/js/config/notifications.js
  themes/dark/assets/js/config/notifications.js
  themes/light/assets/js/config/notifications.js
Labels: Bug, Concluded, Frontend

#4979 Improve shows module
  themes-default/slim/src/store/modules/shows.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Concluded, Enhancement, Frontend

#4976 Remove pyup
  .pyup.yml
  readme.md
Labels: Concluded, Enhancement

#4987 Ensure show IMDB info is never None
  medusa/tv/series.py
Labels: Bug, Concluded

#5082 Move stylelint from root to themes-default/slim
  .travis.yml
  package.json
  themes-default/slim/package.json
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/manual-post-process.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/components/status.vue
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
  yarn.lock
Labels: Concluded, Enhancement

#5081 Fix uTorrent client & BTN provider
  medusa/clients/torrent/utorrent_client.py
  medusa/providers/torrent/html/yggtorrent.py
  medusa/providers/torrent/json/btn.py
Labels: Bug, Concluded, Needs review
