Repository pymedusa/Medusa, pull requests merged in 2018-09, with the labels that each got.

#5089 Vueify IRC page
  CHANGELOG.md
  medusa/server/api/v2/config.py
  medusa/server/web/home/irc.py
  setup.cfg
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/irc.vue
  themes-default/slim/src/router.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/irc.spec.js
  themes-default/slim/test/specs/snapshots/irc.spec.js.md
  themes-default/slim/test/specs/snapshots/irc.spec.js.snap
  themes-default/slim/views/IRC.mako
  themes/dark/assets/js/vendors.js
  themes/dark/templates/IRC.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/IRC.mako
Labels: Concluded, Enhancement, Needs review

#4961 Fix adba error handling
  CHANGELOG.md
  ext/adba/aniDBlink.py
  ext/readme.md
  medusa/tv/series.py
Labels: Bug, Concluded

#5111 Fix HDSpace pubdate parsing
  CHANGELOG.md
  medusa/providers/generic_provider.py
  medusa/providers/torrent/html/hdspace.py
  tests/providers/test_generic_provider.py
Labels: Bug, Concluded, Needs testing, Provider

#5118 Re-add removed Scene column header
  themes-default/slim/views/displayShow.mako
  themes/dark/templates/displayShow.mako
  themes/light/templates/displayShow.mako
Labels: Bug, Concluded, Confirmed

#4946 Convert Post Processing Config to VueRouter
  CHANGELOG.md
  medusa/server/web/config/post_processing.py
  setup.cfg
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/router.js
  themes-default/slim/test/__fixtures__/app-header.json
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/config-post-processing.spec.js
  themes-default/slim/test/specs/config.spec.js
  themes-default/slim/test/specs/snapshots/config-post-processing.spec.js.md
  themes-default/slim/test/specs/snapshots/config-post-processing.spec.js.snap
  themes-default/slim/test/specs/snapshots/config.spec.js.md
  themes-default/slim/test/specs/snapshots/config.spec.js.snap
  themes-default/slim/views/index.mako
  themes/dark/assets/js/vendors.js
  themes/dark/templates/config_postProcessing.mako
  themes/dark/templates/index.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/config_postProcessing.mako
  themes/light/templates/index.mako
Labels: Concluded, Enhancement, Frontend, Needs review, Needs testing

#5116 Update meta
  .gitattributes
  readme.md
Labels: Concluded

#5119 Update changelog for 0.2.9
  CHANGELOG.md
Labels: Concluded

#5124 Sync develop with master
  .github/check_version.py
  medusa/common.py
  themes/dark/assets/css/vendors.css.map
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/css/vendors.css.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#5126 Fix home tabs poster layout
  themes-default/slim/static/css/style.css
  themes/dark/assets/css/style.css
  themes/light/assets/css/style.css
Labels: Bug, Concluded, Frontend

#5128 Fix Scene release group E7 match confused with episode.
  medusa/name_parser/guessit_parser.py
Labels: Bug, Concluded

#4970 Multi-threaded API v2 handler
  CHANGELOG.md
  medusa/server/api/v2/alias.py
  medusa/server/api/v2/alias_source.py
  medusa/server/api/v2/auth.py
  medusa/server/api/v2/base.py
  medusa/server/api/v2/config.py
  medusa/server/api/v2/episodes.py
  medusa/server/api/v2/internal.py
  medusa/server/api/v2/log.py
  medusa/server/api/v2/series.py
  medusa/server/api/v2/series_asset.py
  medusa/server/api/v2/series_legacy.py
  medusa/server/api/v2/series_operation.py
  medusa/server/api/v2/stats.py
Labels: Backend, Concluded, Enhancement

#5096 Update lib unrar2 (python2 and python3 supported)
  .gitignore
  lib/readme.md
  lib/unrar2/.hgignore
  lib/unrar2/MANIFEST.in
  lib/unrar2/UnRAR2.html
  lib/unrar2/[test].rar
  lib/unrar2/[test].txt
  lib/unrar2/__init__.py
  lib/unrar2/license.txt
  lib/unrar2/rar_exceptions.py
  lib/unrar2/setup.py
  lib/unrar2/test_UnRAR2.py
  lib/unrar2/test_nulls.rar
  lib/unrar2/test_protected_files.rar
  lib/unrar2/test_protected_headers.rar
  lib/unrar2/test_volumes.part1.rar
  lib/unrar2/test_volumes.part2.rar
  lib/unrar2/test_volumes_old.r00
  lib/unrar2/test_volumes_old.rar
  lib/unrar2/unix.py
  lib/unrar2/windows.py
  medusa/server/web/config/post_processing.py
Labels: Needs review, Update dep (Py)

#5127 Fix UI bugs
  CHANGELOG.md
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/home.mako
  themes-default/slim/views/status.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/home.mako
  themes/dark/templates/status.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/home.mako
  themes/light/templates/status.mako
Labels: Bug, Concluded, Frontend

#4985 [Python3] Changes in python2 code to make it python3 compatible (part1)
  medusa/__main__.py
  medusa/black_and_white_list.py
  medusa/clients/torrent/generic.py
  medusa/config.py
  medusa/databases/cache_db.py
  medusa/databases/failed_db.py
  medusa/databases/main_db.py
  medusa/db.py
  medusa/failed_history.py
  medusa/helpers/__init__.py
  medusa/helpers/anidb.py
  medusa/helpers/externals.py
  medusa/name_parser/parser.py
  medusa/name_parser/rules/rules.py
  medusa/network_timezones.py
  medusa/notifiers/emailnotify.py
  medusa/notifiers/prowl.py
  medusa/notifiers/slack.py
  medusa/notifiers/telegram.py
  medusa/post_processor.py
  medusa/process_tv.py
  medusa/providers/generic_provider.py
  medusa/scene_exceptions.py
  medusa/scene_numbering.py
  medusa/search/backlog.py
  medusa/search/core.py
  medusa/search/daily.py
  medusa/search/manual.py
  medusa/search/proper.py
  medusa/search/queue.py
  medusa/server/api/v1/core.py
  medusa/server/api/v2/alias.py
  medusa/server/api/v2/alias_source.py
  medusa/server/api/v2/internal.py
  medusa/server/api/v2/stats.py
  medusa/server/web/core/base.py
  medusa/server/web/core/calendar.py
  medusa/server/web/home/handler.py
  medusa/server/web/manage/handler.py
  medusa/session/handlers.py
  medusa/show/coming_episodes.py
  medusa/show/recommendations/anidb.py
  medusa/show/recommendations/imdb.py
  medusa/show/recommendations/recommended.py
  medusa/show/recommendations/trakt.py
  medusa/show/show.py
  medusa/show_updater.py
  medusa/subtitles.py
  medusa/trakt_checker.py
  medusa/tv/cache.py
  medusa/tv/episode.py
  medusa/tv/series.py
Labels: Backend, Concluded, Enhancement, Needs testing

#5095 Move date-fns to Webpack and use selective import
  themes-default/slim/package.json
  themes-default/slim/src/components/name-pattern.vue
  themes-default/slim/static/js/lib/date_fns.min.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/lib/date_fns.min.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/lib/date_fns.min.js
  themes/light/assets/js/vendors.js
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement, Frontend, Needs review

#5087 vueify start of showheader
  CHANGELOG.md
  themes-default/slim/package.json
  themes-default/slim/src/api.js
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/views/partials/seasonEpisode.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/dark/templates/partials/seasonEpisode.mako
  themes/dark/templates/partials/showheader.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/partials/seasonEpisode.mako
  themes/light/templates/partials/showheader.mako
Labels: Concluded, Frontend, Needs review, Needs testing

#5164 Fix internal API routes
  medusa/server/api/v2/internal.py
Labels: Backend, Bug, Concluded

#5166 Update `/series` API to only get AniDB data if requested
  CHANGELOG.md
  dredd/api-description.yml
  medusa/server/api/v2/series.py
  medusa/tv/series.py
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/views/editShow.mako
  themes/dark/assets/js/vendors.js
  themes/dark/templates/editShow.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/editShow.mako
Labels: Backend, Bug, Concluded, Enhancement, Frontend, Needs review

#5132 Fix watched null values.
  CHANGELOG.md
  medusa/tv/episode.py
Labels: Bug, Concluded, Needs review

#5145 Fix unable to start Medusa due to configparser ImportError
  CHANGELOG.md
  ext/backports/__init__.py
  ext/configparser.pth
  ext/readme.md
  medusa/init/__init__.py
Labels: Bug, Concluded, Enhancement, Needs review

#5169 Fix Preview Rename page
  CHANGELOG.md
  themes-default/slim/views/testRename.mako
  themes/dark/templates/testRename.mako
  themes/light/templates/testRename.mako
Labels: Bug, Concluded, Frontend

#5165 Post Processing config saving `select-list` values incorrectly
  CHANGELOG.md
  medusa/__main__.py
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/select-list.vue
  themes-default/slim/test/specs/select-list.spec.js
  themes-default/slim/test/specs/snapshots/select-list.spec.js.md
  themes-default/slim/test/specs/snapshots/select-list.spec.js.snap
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Backend, Bug, Concluded, Frontend, Needs review

#5172 Fix TorrentLeech pagination code
  CHANGELOG.md
  medusa/providers/torrent/json/torrentleech.py
Labels: Bug, Concluded, Provider

#5163 Hotfix 0.2.10
  CHANGELOG.md
  dredd/api-description.yml
  ext/backports/__init__.py
  ext/configparser.pth
  ext/readme.md
  medusa/__main__.py
  medusa/common.py
  medusa/init/__init__.py
  medusa/providers/torrent/json/torrentleech.py
  medusa/server/api/v2/series.py
  medusa/tv/episode.py
  medusa/tv/series.py
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/select-list.vue
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/static/css/style.css
  themes-default/slim/test/specs/select-list.spec.js
  themes-default/slim/test/specs/snapshots/select-list.spec.js.md
  themes-default/slim/test/specs/snapshots/select-list.spec.js.snap
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/home.mako
  themes-default/slim/views/status.mako
  themes-default/slim/views/testRename.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/vendors.js
  themes/dark/assets/js/vendors.js.map
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/home.mako
  themes/dark/templates/status.mako
  themes/dark/templates/testRename.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/vendors.js
  themes/light/assets/js/vendors.js.map
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/editShow.mako
  themes/light/templates/home.mako
  themes/light/templates/status.mako
  themes/light/templates/testRename.mako
Labels: Concluded

#5176 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#5179 Update renovate config
  renovate.json
Labels: Concluded, Enhancement

#4848 Vueify add show options
  CHANGELOG.md
  medusa/common.py
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  tests/test_common.py
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/anidb-release-group-ui.vue
  themes-default/slim/src/components/config-toggle-slider.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/index.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/src/utils.js
  themes-default/slim/static/js/blackwhite.js
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/add-show-options.spec.js
  themes-default/slim/test/specs/snapshots/add-show-options.spec.js.md
  themes-default/slim/test/specs/snapshots/add-show-options.spec.js.snap
  themes-default/slim/test/specs/utils.spec.js
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/inc_addShowOptions.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/assets/js/blackwhite.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/inc_addShowOptions.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/assets/js/blackwhite.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/editShow.mako
  themes/light/templates/inc_addShowOptions.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Bug, Concluded, Enhancement

#5187 Update `feedparser`
  ext/feedparser/__init__.py
  ext/feedparser/api.py
  ext/feedparser/encodings.py
  ext/feedparser/mixin.py
  ext/readme.md
  requirements.txt
Labels: Concluded, Update dep (Py)

#5186 Remove UA spoofing code and `fake-useragent`
  lib/fake_useragent/__init__.py
  lib/fake_useragent/fake.py
  lib/fake_useragent/settings.py
  lib/fake_useragent/ua.json
  lib/fake_useragent/utils.py
  lib/readme.md
  medusa/common.py
Labels: Concluded, Needs review, Remove dep (Py)

#5192 Upgrade pygithub to 1.43.1
  ext/github/Consts.py
  ext/github/MainClass.py
  ext/github/Organization.py
  ext/github/Project.py
  ext/github/ProjectCard.py
  ext/github/ProjectColumn.py
  ext/github/Repository.py
  ext/readme.md
Labels: Concluded, Update dep (Py)

#5190 Fix Speedcd parsing and add pubdate
  CHANGELOG.md
  medusa/providers/torrent/html/speedcd.py
Labels: Bug, Concluded, Enhancement

#5205 [Tests/CI] Hide pytest warnings, update deps
  setup.cfg
  setup.py
Labels: Bug, Concluded

#5140 Update bencode and PyYAML
  ext/bencode/BTL.py
  ext/bencode/__init__.py
  ext/bencode/exceptions.py
  ext/readme.md
  ext/yaml/__init__.py
  lib/bencode/BTL.py
  lib/bencode/LICENSE.txt
  lib/bencode/__init__.py
  lib/bencode/bencode.py
  lib/readme.md
  medusa/clients/torrent/generic.py
  medusa/init/__init__.py
  medusa/providers/torrent/rss/rsstorrent.py
  medusa/providers/torrent/torrent_provider.py
  requirements.txt
  tests/test_init.py
Labels: Concluded, Update dep (Py)

#5185 Remove loglevel from bower & cleanup
  .build/bower.json
  themes-default/slim/package.json
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/file-browser.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/name-pattern.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/static/js/config/index.js
  themes-default/slim/static/js/config/notifications.js
  themes-default/slim/static/js/vender.js
  themes-default/slim/static/js/vender.min.js
  themes-default/slim/views/manage_manageSearches.mako
  themes/dark/assets/js/config/index.js
  themes/dark/assets/js/config/notifications.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vender.js
  themes/dark/assets/js/vender.min.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/manage_manageSearches.mako
  themes/light/assets/js/config/index.js
  themes/light/assets/js/config/notifications.js
  themes/light/assets/js/index.js
  themes/light/assets/js/vender.js
  themes/light/assets/js/vender.min.js
  themes/light/assets/js/vendors.js
  themes/light/templates/manage_manageSearches.mako
Labels: Concluded, Enhancement, Frontend, Remove dep (JS)

#5090 Split vendors file into 3rd- & 1st-party
  themes-default/slim/src/index.js
  themes-default/slim/vendor/css/open-sans.css
  themes-default/slim/vendor/fonts/open-sans-v15-latin-300.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-300italic.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-600.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-600italic.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-700.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-700italic.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-800.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-800italic.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-italic.ttf
  themes-default/slim/vendor/fonts/open-sans-v15-latin-regular.ttf
  themes-default/slim/views/apiBuilder.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/webpack.config.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/apiBuilder.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
  themes/light/templates/apiBuilder.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#5129 Add BTDB.to search engine. Closes #5084
  medusa/providers/__init__.py
  medusa/providers/torrent/__init__.py
  medusa/providers/torrent/html/btdb.py
Labels: Enhancement, In progress, Provider

#5215 Move tablesorter to webpack
  .build/Gruntfile.js
  .build/bower.json
  themes-default/slim/package.json
  themes-default/slim/src/index.js
  themes-default/slim/static/css/vender.min.css
  themes-default/slim/static/js/vender.js
  themes-default/slim/static/js/vender.min.js
  themes-default/slim/vendor/js/tablesorter.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/css/vender.min.css
  themes/dark/assets/css/vendors.css
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vender.js
  themes/dark/assets/js/vender.min.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/displayShow.mako
  themes/light/assets/css/vender.min.css
  themes/light/assets/css/vendors.css
  themes/light/assets/js/index.js
  themes/light/assets/js/vender.js
  themes/light/assets/js/vender.min.js
  themes/light/assets/js/vendors.js
  themes/light/templates/displayShow.mako
Labels: Enhancement, Update dep (JS)

#5216 Custom WebSocket mutation messages
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/mutation-types.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement, Frontend

#5103 Vueify: Quality Pill
  CHANGELOG.md
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/quality-pill.vue
  themes-default/slim/src/index.js
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/ajax-episode-search.js
  themes-default/slim/test/helpers/generators.js
  themes-default/slim/test/specs/quality-pill.spec.js
  themes-default/slim/test/specs/snapshots/quality-pill.spec.js.md
  themes-default/slim/test/specs/snapshots/quality-pill.spec.js.snap
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/history.mako
  themes-default/slim/views/inc_defs.mako
  themes-default/slim/views/manage.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes-default/slim/views/partials/home/banner.mako
  themes-default/slim/views/partials/home/poster.mako
  themes-default/slim/views/partials/home/simple.mako
  themes-default/slim/views/partials/home/small.mako
  themes-default/slim/views/partials/schedule/banner.mako
  themes-default/slim/views/partials/schedule/list.mako
  themes-default/slim/views/partials/schedule/poster.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/views/snatchSelection.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/ajax-episode-search.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/displayShow.mako
  themes/dark/templates/history.mako
  themes/dark/templates/inc_defs.mako
  themes/dark/templates/manage.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/dark/templates/partials/home/banner.mako
  themes/dark/templates/partials/home/poster.mako
  themes/dark/templates/partials/home/simple.mako
  themes/dark/templates/partials/home/small.mako
  themes/dark/templates/partials/schedule/banner.mako
  themes/dark/templates/partials/schedule/list.mako
  themes/dark/templates/partials/schedule/poster.mako
  themes/dark/templates/partials/showheader.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/ajax-episode-search.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/displayShow.mako
  themes/light/templates/history.mako
  themes/light/templates/inc_defs.mako
  themes/light/templates/manage.mako
  themes/light/templates/manage_backlogOverview.mako
  themes/light/templates/partials/home/banner.mako
  themes/light/templates/partials/home/poster.mako
  themes/light/templates/partials/home/simple.mako
  themes/light/templates/partials/home/small.mako
  themes/light/templates/partials/schedule/banner.mako
  themes/light/templates/partials/schedule/list.mako
  themes/light/templates/partials/schedule/poster.mako
  themes/light/templates/partials/showheader.mako
  themes/light/templates/snatchSelection.mako
Labels: Concluded, Enhancement, Frontend, Needs review

#5125 Feature/fix adba logger and unicode
  CHANGELOG.md
  ext/adba/__init__.py
  ext/adba/aniDBAbstracter.py
  ext/adba/aniDBfileInfo.py
  ext/adba/aniDBlink.py
  ext/readme.md
  medusa/logger/__init__.py
Labels: Bug, Concluded, Needs review

#5293 Add 502 to handled codes for BTN. Fixes #5291
  medusa/providers/torrent/json/btn.py
Labels: Concluded, Enhancement

#5236 Remove encoding hack, replace with warning
  medusa/__main__.py
  medusa/init/filesystem.py
Labels: Concluded, Enhancement

#5300 Fixed trakt icon not showing on the displayShow page, when a trakt id…
  CHANGELOG.md
  medusa/tv/series.py
Labels: Bug, Concluded

#5309 Fix strftime() incompatibility with unicode (for Python 2). Fixes #5301
  medusa/sbdatetime.py
  themes-default/slim/views/config_general.mako
  themes-default/slim/views/partials/footer.mako
  themes-default/slim/views/snatchSelection.mako
  themes-default/slim/views/status.mako
  themes/dark/templates/config_general.mako
  themes/dark/templates/partials/footer.mako
  themes/dark/templates/snatchSelection.mako
  themes/dark/templates/status.mako
  themes/light/templates/config_general.mako
  themes/light/templates/partials/footer.mako
  themes/light/templates/snatchSelection.mako
  themes/light/templates/status.mako
Labels: Bug, Concluded, Needs review

#5314 Feature/fix anidb release group high mem usage
  CHANGELOG.md
  themes-default/slim/src/components/anidb-release-group-ui.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded
