Repository pymedusa/Medusa, pull requests merged in 2018-10, with the labels that each got.

#5356 Fix StateSwitch theme, missed subtitle download, popularShows router path
  CHANGELOG.md
  themes-default/slim/src/router.js
  themes-default/slim/views/manage_subtitleMissed.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/views/restart.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/manage_subtitleMissed.mako
  themes/dark/templates/partials/showheader.mako
  themes/dark/templates/restart.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/manage_subtitleMissed.mako
  themes/light/templates/partials/showheader.mako
  themes/light/templates/restart.mako
Labels: Bug, Concluded, Frontend

#5079 Feature/apiv2 add config search attributes
  CHANGELOG.md
  dredd/api-description.yml
  medusa/server/api/v2/config.py
Labels: Backend, Changelog, Concluded, Enhancement

#5343 Fix _encode and _decode in subtitles.py, move encoding check after lo…
  medusa/__main__.py
  medusa/clients/nzb/sab.py
  medusa/logger/adapters/style.py
  medusa/refiners/release.py
  medusa/refiners/tv_episode.py
  medusa/subtitles.py
Labels: Concluded, Needs review, Needs testing

#5375 Fix BraceException on SABnzbd snatch. Fixes #5364
  medusa/clients/nzb/sab.py
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#5385 Add support for SABnzbd's Direct Unpack feature. Fixes #5379
  CHANGELOG.md
  medusa/process_tv.py
Labels: Bug, Concluded, Enhancement

#5386 Replace generic Exception with RequestException, demote to warning. F…
  CHANGELOG.md
  medusa/show_queue.py
Labels: Bug, Concluded

#5389 Fix subtitleMissed
  themes-default/slim/views/manage_subtitleMissed.mako
  themes/dark/templates/manage_subtitleMissed.mako
  themes/light/templates/manage_subtitleMissed.mako
Labels: Bug, Concluded

#5400 Fix metadata settings not being saved. Fixes #5352
  CHANGELOG.md
  medusa/server/api/v2/base.py
Labels: Bug, Concluded, Needs review, Needs testing, Priority: 2. Medium

#5175 Remove NZB splitting option. "Fixes" #5141
  medusa/nzb_splitter.py
  medusa/search/core.py
Labels: Bug, Concluded

#5440 Update imdbpie to v5.6.3
  ext/attr/__init__.py
  ext/attr/__init__.pyi
  ext/attr/_compat.py
  ext/attr/_funcs.py
  ext/attr/_make.py
  ext/attr/converters.py
  ext/attr/converters.pyi
  ext/attr/exceptions.py
  ext/attr/exceptions.pyi
  ext/attr/filters.pyi
  ext/attr/py.typed
  ext/attr/validators.py
  ext/attr/validators.pyi
  ext/imdbpie/imdbpie.py
  ext/readme.md
  ext/trans.py
  requirements.txt
Labels: Concluded

#5443 Fix Synology DS missing location and wrong icon
  CHANGELOG.md
  dredd/api-description.yml
  themes-default/slim/static/css/style.css
  themes-default/slim/views/config_search.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/css/style.css
  themes/dark/templates/config_search.mako
  themes/light/assets/css/style.css
  themes/light/templates/config_search.mako
Labels: Bug, Concluded, Needs review

#5444 Replace cdn.rawgit.com with rawcdn.githack.com
  medusa/version_checker.py
Labels: Concluded

#5439 Update guessit to v3.0.1, rebulk to v1.0.0
  ext/guessit/__version__.py
  ext/guessit/config/options.json
  ext/guessit/jsonutils.py
  ext/guessit/rules/common/date.py
  ext/guessit/rules/common/formatters.py
  ext/guessit/rules/properties/audio_codec.py
  ext/guessit/rules/properties/country.py
  ext/guessit/rules/properties/episodes.py
  ext/guessit/rules/properties/language.py
  ext/guessit/rules/properties/other.py
  ext/guessit/rules/properties/release_group.py
  ext/guessit/rules/properties/title.py
  ext/guessit/rules/properties/video_codec.py
  ext/guessit/rules/properties/website.py
  ext/guessit/test/episodes.yml
  ext/guessit/test/movies.yml
  ext/guessit/test/rules/title.yml
  ext/guessit/test/rules/video_codec.yml
  ext/guessit/test/test_yml.py
  ext/guessit/test/various.yml
  ext/readme.md
  ext/rebulk/__version__.py
  ext/rebulk/loose.py
  ext/rebulk/match.py
  ext/rebulk/processors.py
  ext/rebulk/rules.py
  ext/rebulk/utils.py
  medusa/name_parser/rules/rules.py
  requirements.txt
  tests/test_guessit.yml
Labels: Concluded

#5398 Fix exception when forcing daily search with season results
  medusa/tv/cache.py
Labels: Bug, Concluded

#5464 Fix word getting parsed as language with multiple fileparts. Fixes #5181
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded, Guessit

#5472 Avoid exception in uTorrent client when ROOT_DIRS aren't set. Fixes #…
  medusa/clients/torrent/utorrent_client.py
Labels: Bug, Concluded, Needs review

#5473 Move changelog item from 0.2.9 to unreleased.
  CHANGELOG.md
Labels: Concluded

#5471 Standardize processing method
  medusa/name_parser/rules/rules.py
  medusa/post_processor.py
  medusa/process_tv.py
Labels: Concluded, Enhancement

#5482 Fix saving of the config - postprocess frequency.
  CHANGELOG.md
  medusa/__main__.py
  medusa/app.py
  medusa/config.py
  medusa/name_parser/rules/properties.py
  medusa/notifiers/emby.py
  medusa/providers/torrent/html/bjshare.py
  medusa/providers/torrent/html/hebits.py
  medusa/providers/torrent/html/pretome.py
  medusa/providers/torrent/html/shanaproject.py
  medusa/providers/torrent/json/animebytes.py
  medusa/server/api/v2/config.py
  medusa/subtitle_providers/itasa.py
  setup.cfg
  setup.py
  themes-default/slim/src/components/config-post-processing.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#5519 Update guessit to v3.0.3
  ext/guessit/__init__.py
  ext/guessit/__main__.py
  ext/guessit/__version__.py
  ext/guessit/api.py
  ext/guessit/config/options.json
  ext/guessit/jsonutils.py
  ext/guessit/monkeypatch.py
  ext/guessit/options.py
  ext/guessit/rules/processors.py
  ext/guessit/rules/properties/audio_codec.py
  ext/guessit/rules/properties/crc.py
  ext/guessit/rules/properties/date.py
  ext/guessit/rules/properties/episode_title.py
  ext/guessit/rules/properties/episodes.py
  ext/guessit/rules/properties/other.py
  ext/guessit/rules/properties/release_group.py
  ext/guessit/test/enable_disable_properties.yml
  ext/guessit/test/episodes.yml
  ext/guessit/test/movies.yml
  ext/guessit/test/rules/audio_codec.yml
  ext/guessit/test/rules/country.yml
  ext/guessit/test/rules/episodes.yml
  ext/guessit/test/rules/other.yml
  ext/guessit/test/rules/screen_size.yml
  ext/guessit/test/test_options.py
  ext/guessit/test/test_yml.py
  ext/guessit/test/various.yml
  ext/readme.md
  medusa/name_parser/rules/rules.py
  requirements.txt
  tests/test_guessit.yml
Labels: Bug, Concluded

#5524 Make rebulk rules Py2/3 compatible
  medusa/name_parser/rules/rules.py
Labels: Bug, Concluded

#5530 move helper components to dir and fix coverage
  themes-default/slim/package.json
  themes-default/slim/src/components/add-recommended.vue
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/add-shows.vue
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/config.vue
  themes-default/slim/src/components/helpers/app-link.vue
  themes-default/slim/src/components/helpers/asset.vue
  themes-default/slim/src/components/helpers/config-textbox-number.vue
  themes-default/slim/src/components/helpers/config-textbox.vue
  themes-default/slim/src/components/helpers/config-toggle-slider.vue
  themes-default/slim/src/components/helpers/file-browser.vue
  themes-default/slim/src/components/helpers/index.js
  themes-default/slim/src/components/helpers/language-select.vue
  themes-default/slim/src/components/helpers/name-pattern.vue
  themes-default/slim/src/components/helpers/plot-info.vue
  themes-default/slim/src/components/helpers/quality-pill.vue
  themes-default/slim/src/components/helpers/scroll-buttons.vue
  themes-default/slim/src/components/helpers/select-list.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/components/helpers/state-switch.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/show.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement, Frontend

#5532 Fixed sql command, for getting snatch selection history.
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#5533 Update YggTorrent URL
  medusa/providers/torrent/html/yggtorrent.py
Labels: Concluded, Enhancement

#5526 Fix single episodes released as multi not being snatched
  medusa/search/core.py
Labels: Bug, Concluded

#5509 Feature/bootstrap add new show
  CHANGELOG.md
  themes-default/slim/static/css/dark.css
  themes-default/slim/static/css/style.css
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/css/themed.css
  themes/dark/templates/addShows_newShow.mako
  themes/light/assets/css/style.css
  themes/light/templates/addShows_newShow.mako
Labels: Enhancement

#5543 Fix database always trying to update
  medusa/databases/cache_db.py
  medusa/databases/failed_db.py
  medusa/databases/main_db.py
  medusa/db.py
Labels: Bug, Concluded, Priority: 1. High

#5357 use router-link when both pages are vueified
  themes-default/slim/.babelrc
  themes-default/slim/package.json
  themes-default/slim/src/components/helpers/app-link.vue
  themes-default/slim/src/router.js
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement, Frontend

#5561 Fix test not working for Download Station. Fixes #5559
  CHANGELOG.md
  medusa/clients/torrent/downloadstation_client.py
  tests/test_clients.py
Labels: Bug, Concluded

#5562 Fix wrong placeholder reference in log. Fixes #5560
  CHANGELOG.md
  medusa/tv/series.py
Labels: Bug, Concluded

#5557 Fix config/notifications page after breaking it in vueifying
  medusa/server/api/v2/config.py
  themes-default/slim/src/components/helpers/config-textbox-number.vue
  themes-default/slim/src/components/helpers/config-textbox.vue
  themes-default/slim/src/components/helpers/config-toggle-slider.vue
  themes-default/slim/test/specs/snapshots/config-toggle-slider.spec.js.md
  themes-default/slim/test/specs/snapshots/config-toggle-slider.spec.js.snap
  themes-default/slim/views/config_notifications.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_notifications.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_notifications.mako
Labels: Bug, Concluded, Frontend

#5573 Fix Download Station BraceAdapter exception. Fixes #5572
  CHANGELOG.md
  medusa/clients/torrent/downloadstation_client.py
Labels: Bug, Concluded
