Repository pymedusa/Medusa, pull requests merged in 2018-12, with the labels that each got.

#5813 Fix episode status comparison in subtitleMissedPP
  CHANGELOG.md
  medusa/server/web/manage/handler.py
Labels: Bug, Concluded

#5823 Restore the ability to change the daily search interval.
  .travis.yml
  tests/test_process_tv.py
  themes-default/slim/views/config_search.mako
  themes/dark/templates/config_search.mako
  themes/light/templates/config_search.mako
Labels: Bug, Concluded

#5854 Add provider nordicbits
  CHANGELOG.md
  medusa/providers/__init__.py
  medusa/providers/torrent/__init__.py
  medusa/providers/torrent/html/nordicbits.py
  themes-default/slim/static/images/providers/nordicbits.png
  themes/dark/assets/img/providers/nordicbits.png
  themes/light/assets/img/providers/nordicbits.png
Labels: Concluded, Feature request

#5865 Update LimeTorrents domain. Fixes #5859
  medusa/providers/torrent/html/limetorrents.py
Labels: Bug, Concluded

#5864 Fix trakt exception message str format.
  medusa/notifiers/trakt.py
Labels: Bug, Concluded

#5867 Feature/fix trakt ex others
  medusa/notifiers/trakt.py
Labels: Bug, Concluded

#5871 Fix saving setting notifiers - kodi allways on.
  medusa/server/api/v2/config.py
Labels: Backend, Bug, Concluded

#5872 Document the absolute numbering in the naming pattern legend. (%AB)
  themes-default/slim/src/components/helpers/name-pattern.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#5888 Add convert_size to missing providers
  medusa/providers/nzb/anizb.py
  medusa/providers/torrent/json/animebytes.py
  medusa/providers/torrent/json/btn.py
  medusa/providers/torrent/json/hdbits.py
  medusa/providers/torrent/json/xthor.py
Labels: Concluded, Enhancement

#5889 Don't add multiple alias (guessit)
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#5892 Store the python version on startup in config
  SickBeard.py
  medusa/__main__.py
  medusa/app.py
  medusa/cache.py
  start.py
Labels: Concluded, Enhancement

#5896 Add 30m proper search interval
  themes-default/slim/views/config_search.mako
  themes/dark/templates/config_search.mako
  themes/light/templates/config_search.mako
Labels: Bug, Concluded, Enhancement

#5897 Fix wrong param for add_to_mylist(), fix SABnzbd test button
  medusa/post_processor.py
  themes-default/slim/views/config_search.mako
  themes/dark/templates/config_search.mako
  themes/light/templates/config_search.mako
Labels: Bug, Concluded

#5901 Sync master to develop
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#5904 Fix git_reset_branches saved as bytes, update six
  ext/readme.md
  ext/six.py
  medusa/helpers/__init__.py
  medusa/server/web/config/general.py
  requirements.txt
Labels: Bug, Concluded

#5906 Added workaround for searching shows like 'Мажор' with imdbpie.
  medusa/helpers/__init__.py
Labels: Bug, Concluded

#5908 Update requirements subliminal entry
  requirements.txt
Labels: Bug, Concluded

#5912 Fix config encryption exception. Fixes #5910
  dredd/dredd_hook.py
  medusa/__main__.py
  medusa/helpers/__init__.py
Labels: Bug, Concluded

#5918 Feature/fix save api key
  CHANGELOG.md
  themes-default/slim/views/config_providers.mako
  themes/dark/templates/config_providers.mako
  themes/light/templates/config_providers.mako
Labels: Bug, Concluded

#5926 Fix API v1 arguments values as bytes. Fixes #5819
  medusa/server/api/v1/core.py
  themes-default/slim/views/apiBuilder.mako
  themes/dark/templates/apiBuilder.mako
  themes/light/templates/apiBuilder.mako
Labels: Bug, Concluded

#5874 Feature configure per show daily search airdate offset
  CHANGELOG.md
  dredd/api-description.yml
  medusa/databases/main_db.py
  medusa/search/core.py
  medusa/search/daily.py
  medusa/server/api/v2/series.py
  medusa/tv/series.py
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/partials/showheader.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/editShow.mako
  themes/dark/templates/partials/showheader.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/editShow.mako
  themes/light/templates/partials/showheader.mako
Labels: Concluded, Feature request, Needs review

#5936 Fix block size computation for log viewer. Fixes #5931
  medusa/logger/__init__.py
  medusa/server/web/core/error_logs.py
Labels: Bug, Concluded

#5945 Update vendored lib & list: urllib3 [1.23 -> 1.24.1]
  .gitignore
  ext/jwt/contrib/__init__.py
  ext/jwt/contrib/algorithms/__init__.py
  ext/jwt/contrib/algorithms/py_ecdsa.py
  ext/jwt/contrib/algorithms/pycrypto.py
  ext/readme.md
  ext/urllib3/__init__.py
  ext/urllib3/_collections.py
  ext/urllib3/connection.py
  ext/urllib3/connectionpool.py
  ext/urllib3/contrib/__init__.py
  ext/urllib3/contrib/_appengine_environ.py
  ext/urllib3/contrib/_securetransport/__init__.py
  ext/urllib3/contrib/_securetransport/bindings.py
  ext/urllib3/contrib/_securetransport/low_level.py
  ext/urllib3/contrib/appengine.py
  ext/urllib3/contrib/ntlmpool.py
  ext/urllib3/contrib/pyopenssl.py
  ext/urllib3/contrib/securetransport.py
  ext/urllib3/contrib/socks.py
  ext/urllib3/packages/backports/makefile.py
  ext/urllib3/packages/ordered_dict.py
  ext/urllib3/packages/ssl_match_hostname/_implementation.py
  ext/urllib3/poolmanager.py
  ext/urllib3/request.py
  ext/urllib3/response.py
  ext/urllib3/util/connection.py
  ext/urllib3/util/response.py
  ext/urllib3/util/retry.py
  ext/urllib3/util/ssl_.py
  ext/urllib3/util/wait.py
Labels: Concluded, Update dep (Py)
