Repository pymedusa/Medusa, pull requests merged in 2018-05, with the labels that each got.

#4112 Fixes for newShow and existingShow (+move it to vue)
  medusa/metadata/generic.py
  medusa/server/api/v2/internal.py
  medusa/server/api/v2/series.py
  medusa/server/core.py
  medusa/server/web/home/add_shows.py
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/add-shows/new-show.js
  themes-default/slim/static/js/root-dirs.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/home_massAddTable.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/add-shows/new-show.js
  themes/dark/assets/js/add-shows/new-show.js.map
  themes/dark/assets/js/root-dirs.js
  themes/dark/assets/js/root-dirs.js.map
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/home_massAddTable.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/add-shows/new-show.js
  themes/light/assets/js/add-shows/new-show.js.map
  themes/light/assets/js/root-dirs.js
  themes/light/assets/js/root-dirs.js.map
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/home_massAddTable.mako
Labels: Bug, Enhancement

#4148 UI Fixes
  themes-default/slim/static/js/lib/axios.min.js
  themes-default/slim/views/404.mako
  themes-default/slim/views/500.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/manage.mako
  themes-default/slim/views/partials/home/banner.mako
  themes-default/slim/views/partials/home/simple.mako
  themes-default/slim/views/partials/home/small.mako
  themes/dark/assets/js/common/init.js.map
  themes/dark/assets/js/lib/axios.min.js
  themes/dark/templates/404.mako
  themes/dark/templates/500.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/manage.mako
  themes/dark/templates/partials/home/banner.mako
  themes/dark/templates/partials/home/simple.mako
  themes/dark/templates/partials/home/small.mako
  themes/light/assets/js/common/init.js.map
  themes/light/assets/js/lib/axios.min.js
  themes/light/templates/404.mako
  themes/light/templates/500.mako
  themes/light/templates/editShow.mako
  themes/light/templates/manage.mako
  themes/light/templates/partials/home/banner.mako
  themes/light/templates/partials/home/simple.mako
  themes/light/templates/partials/home/small.mako
Labels: Bug, Concluded

#4149 Ignore more files to skip Python tests
  .github/check_changes.py
Labels: Priority: 3. Low

#4147 Fix CloudFlare Bypass
  medusa/providers/generic_provider.py
  medusa/session/core.py
  medusa/session/handlers.py
  medusa/session/hooks.py
Labels: Bug, Discussion, Help wanted

#4144 Fix metadata issues
  medusa/metadata/generic.py
  medusa/metadata/mede8er.py
  medusa/metadata/media_browser.py
  medusa/metadata/tivo.py
  medusa/metadata/wdtv.py
Labels: Bug, Concluded, Needs review

#4136 GitUpdateManager: Always prune when fetching
  medusa/version_checker.py
Labels: Concluded, Priority: 3. Low

#4152 guessit expected_groups should be a set
  medusa/name_parser/guessit_parser.py
Labels: Bug, Concluded, Needs testing

#4169 Fix qBittorrent resume/pause command
  medusa/clients/torrent/qbittorrent_client.py
Labels: Bug, Needs review

#4177 MedusaSession: Remove dot after url in log
  medusa/session/core.py
Labels: Concluded

#4171 Don't use unicode for guessit rules and options
  medusa/name_parser/guessit_parser.py
  medusa/name_parser/rules/rules.py
Labels: Bug, In progress

#4175 Fix failed Python tests not failing build
  .travis.yml
Labels: Concluded

#4176 Update internal resources API
  medusa/server/api/v2/internal.py
Labels: Concluded, Needs review, Needs testing

#4163 Update editShow UI (select-list, releasegroups, link back to displayShow)
  themes-default/slim/static/images/refresh.png
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/vue-components/anidb-release-group-ui.mako
  themes-default/slim/views/vue-components/file-browser.mako
  themes-default/slim/views/vue-components/language-select.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes-default/slim/views/vue-components/select-list-ui.mako
  themes/dark/assets/img/refresh.png
  themes/dark/templates/editShow.mako
  themes/dark/templates/vue-components/anidb-release-group-ui.mako
  themes/dark/templates/vue-components/file-browser.mako
  themes/dark/templates/vue-components/language-select.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/dark/templates/vue-components/select-list-ui.mako
  themes/light/assets/img/refresh.png
  themes/light/templates/editShow.mako
  themes/light/templates/vue-components/anidb-release-group-ui.mako
  themes/light/templates/vue-components/file-browser.mako
  themes/light/templates/vue-components/language-select.mako
  themes/light/templates/vue-components/quality-chooser.mako
  themes/light/templates/vue-components/select-list-ui.mako
Labels: Concluded

#4188 Travis: Stop skipping Python tests
  .github/check_changes.py
  .travis.yml
Labels: Concluded

#4157 Feature/fix setting status back to wanted
  medusa/common.py
  medusa/databases/main_db.py
  medusa/numdict.py
  medusa/search/core.py
  medusa/search/daily.py
  medusa/server/api/v1/core.py
  medusa/server/web/home/handler.py
  medusa/tv/episode.py
  medusa/tv/series.py
  pytest.ini
  tests/conftest.py
  tests/legacy/numdict_tests.py
  tests/test_should_refresh.py
  tests/test_update_status.py
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Bug, In progress

#4088 Don't decode scene exceptions as they are already unicode, reorder im…
  medusa/scene_exceptions.py
  requirements.txt
Labels: Bug, Concluded

#4189 flake8: Fix all import order warnings
  medusa/bs4_parser.py
  medusa/helper/encoding.py
  medusa/helper/exceptions.py
  medusa/helpers/quality.py
  medusa/media/banner.py
  medusa/media/fan_art.py
  medusa/media/generic.py
  medusa/media/network_logo.py
  medusa/media/poster.py
  medusa/metadata/__init__.py
  medusa/metadata/kodi.py
  medusa/metadata/media_browser.py
  medusa/metadata/ps3.py
  medusa/name_parser/rules/__init__.py
  medusa/name_parser/rules/properties.py
  medusa/notifiers/__init__.py
  medusa/notifiers/nmj.py
  medusa/notifiers/telegram.py
  medusa/nzb_splitter.py
  medusa/providers/torrent/html/hdtorrents.py
  medusa/providers/torrent/html/morethantv.py
  medusa/providers/torrent/html/thepiratebay.py
  medusa/providers/torrent/html/tntvillage.py
  medusa/providers/torrent/json/torrentday.py
  medusa/rss_feeds.py
  medusa/server/api/v2/alias.py
  medusa/server/api/v2/alias_source.py
  medusa/server/api/v2/log.py
  medusa/server/api/v2/series_legacy.py
  medusa/server/api/v2/series_operation.py
  medusa/server/api/v2/stats.py
  medusa/server/web/__init__.py
  medusa/server/web/config/__init__.py
  medusa/server/web/config/anime.py
  medusa/server/web/config/post_processing.py
  medusa/server/web/core/__init__.py
  medusa/server/web/core/error_logs.py
  medusa/server/web/core/token.py
  medusa/server/web/home/__init__.py
  medusa/server/web/home/handler.py
  medusa/server/web/home/post_process.py
  medusa/server/web/manage/__init__.py
  medusa/show/recommendations/__init__.py
  medusa/statistics/__init__.py
  medusa/subtitle_providers/itasa.py
  medusa/subtitle_providers/utils.py
  medusa/themes/__init__.py
  medusa/tv/__init__.py
  medusa/tv/indexer.py
  medusa/ws/MedusaWebSocketHandler.py
  pytest.ini
Labels: Concluded

#4187 Update DownloadStation
  medusa/clients/torrent/download_station_client.py
Labels: Needs review

#4106 IssueSubmitter: Add option to override title diff ratios
  medusa/issue_submitter.py
Labels: Enhancement

#4191 Fix show link obstructed by poster link (Fixes #4060)
  themes-default/slim/static/css/dark.css
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/home/display-show.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/views/vue-components/asset.mako
  themes/dark/assets/css/dark.css
  themes/dark/assets/css/style.css
  themes/dark/assets/css/themed.css
  themes/dark/assets/js/home/display-show.js
  themes/dark/assets/js/home/display-show.js.map
  themes/dark/templates/displayShow.mako
  themes/dark/templates/partials/showheader.mako
  themes/dark/templates/vue-components/asset.mako
  themes/light/assets/css/dark.css
  themes/light/assets/css/style.css
  themes/light/assets/js/home/display-show.js
  themes/light/assets/js/home/display-show.js.map
  themes/light/templates/displayShow.mako
  themes/light/templates/partials/showheader.mako
  themes/light/templates/vue-components/asset.mako
Labels: Concluded, Needs review

#4194 Force representation on BraceMessage exception
  medusa/logger/adapters/style.py
Labels: Bug, Concluded

#4179 More UI fixes for the release
  themes-default/slim/static/css/lib/vue-snotify-material.css
  themes-default/slim/static/js/home/snatch-selection.js
  themes-default/slim/static/js/lib/vue-snotify.min.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/inc_addShowOptions.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_massEdit.mako
  themes-default/slim/views/vue-components/file-browser.mako
  themes-default/slim/views/vue-components/saved-message.mako
  themes/dark/assets/css/lib/vue-snotify-material.css
  themes/dark/assets/js/home/snatch-selection.js
  themes/dark/assets/js/home/snatch-selection.js.map
  themes/dark/assets/js/lib/vue-snotify.min.js
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/inc_addShowOptions.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_massEdit.mako
  themes/dark/templates/vue-components/file-browser.mako
  themes/dark/templates/vue-components/saved-message.mako
  themes/light/assets/css/lib/vue-snotify-material.css
  themes/light/assets/js/home/snatch-selection.js
  themes/light/assets/js/home/snatch-selection.js.map
  themes/light/assets/js/lib/vue-snotify.min.js
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/editShow.mako
  themes/light/templates/inc_addShowOptions.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_massEdit.mako
  themes/light/templates/vue-components/file-browser.mako
  themes/light/templates/vue-components/saved-message.mako
Labels: Concluded

#4199 Update Emby Notifier
  medusa/notifiers/emby.py
  pytest.ini
Labels: Bug, Enhancement, Needs review, Needs testing

#4203 Fix Nebulance's size parsing.
  medusa/providers/torrent/html/nebulance.py
Labels: Bug, Concluded

#4210 Fix changing status from displayShow.
  medusa/server/web/home/handler.py
Labels: Bug, Confirmed, Priority: 1. High

#4215 IssueSubmitter: Fix AttributeError
  medusa/issue_submitter.py
  medusa/search/core.py
Labels: Bug, Needs testing

#4231 Emby: Add info logs
  medusa/notifiers/emby.py
Labels: Concluded, Enhancement

#4230 app-link: Fix anonymised webcal and multiple location hashes
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/light/templates/vue-components/app-link.mako
Labels: Concluded

#4233 indexerApi.config: Fix sorting
  medusa/indexers/indexer_api.py
Labels: Concluded, Needs review

#4219 Encode the filename utf-8 before sending it to q-bittorrent.
  medusa/clients/torrent/generic.py
  medusa/clients/torrent/qbittorrent_client.py
Labels: Bug

#4056 Feature/utorrent dest folder
  medusa/clients/torrent/utorrent_client.py
  themes-default/slim/static/js/config/search.js
  themes-default/slim/views/config_search.mako
  themes/dark/assets/js/config/search.js
  themes/dark/assets/js/config/search.js.map
  themes/dark/templates/config_search.mako
  themes/light/assets/js/config/search.js
  themes/light/assets/js/config/search.js.map
  themes/light/templates/config_search.mako
Labels: Concluded, Enhancement

#4239 imdb-popular: Only get 'year' item if available
  medusa/imdb_popular.py
  medusa/show/recommendations/imdb.py
Labels: Concluded

#4238 Fix missed class changes: btn -> btn-medusa
  themes-default/slim/static/js/config/init.js
  themes-default/slim/views/config_notifications.mako
  themes-default/slim/views/manage_episodeStatuses.mako
  themes-default/slim/views/manage_subtitleMissed.mako
  themes/dark/assets/js/config/init.js
  themes/dark/assets/js/config/init.js.map
  themes/dark/templates/config_notifications.mako
  themes/dark/templates/manage_episodeStatuses.mako
  themes/dark/templates/manage_subtitleMissed.mako
  themes/light/assets/js/config/init.js
  themes/light/assets/js/config/init.js.map
  themes/light/templates/config_notifications.mako
  themes/light/templates/manage_episodeStatuses.mako
  themes/light/templates/manage_subtitleMissed.mako
Labels: Concluded

#4240 Catch BTN "524 Origin Time-out" error
  medusa/providers/torrent/json/btn.py
Labels: Concluded

#4236 Update root yarn.lock
  .travis.yml
  themes/light/package.json
  yarn.lock
Labels: Concluded, Priority: 3. Low

#4232 Update frisbee to 2.0.4
  themes-default/slim/static/js/lib/frisbee.min.js
  themes-default/slim/static/js/lib/frisbee@2.0.4.min.js
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/assets/js/lib/frisbee.min.js
  themes/dark/assets/js/lib/frisbee@2.0.4.min.js
  themes/dark/templates/addShows_newShow.mako
  themes/light/assets/js/lib/frisbee.min.js
  themes/light/assets/js/lib/frisbee@2.0.4.min.js
  themes/light/templates/addShows_newShow.mako
Labels: Concluded, Enhancement, Needs review

#4253 Update imdbpie to 5.4.5 + builds failing
  ext/imdbpie/__init__.py
  ext/imdbpie/auth.py
  ext/imdbpie/constants.py
  ext/imdbpie/imdbpie.py
  medusa/tv/series.py
  requirements.txt
Labels: Concluded, Needs review

#4264 Fix #3988 - API v2 pagination links
  medusa/server/api/v2/base.py
Labels: Bug, Concluded, Needs review, Needs testing

#4280 Fix TypeError: cannot serialize 6.9 (type float)
  medusa/indexers/tvmaze/tvmaze_api.py
Labels: Bug, Concluded

#4283 Update axios to v0.18.0
  themes-default/slim/static/js/lib/axios.min.js
  themes/dark/assets/js/lib/axios.min.js
  themes/light/assets/js/lib/axios.min.js
Labels: Concluded, Enhancement, Needs review

#4269 enable vue perf stats for devs
  themes-default/slim/views/layouts/main.mako
  themes/dark/templates/layouts/main.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4237 Remove NotifyMyAndroid
  ext/pynma/__init__.py
  ext/pynma/pynma.py
  medusa/__main__.py
  medusa/app.py
  medusa/config.py
  medusa/notifiers/__init__.py
  medusa/notifiers/nma.py
  medusa/server/web/config/notifications.py
  medusa/server/web/home/handler.py
  pytest.ini
  requirements.txt
  themes-default/slim/resources/32x_sprite_colored_notifiers.psd
  themes-default/slim/static/css/style.css
  themes-default/slim/static/images/32x_sprite_colored_notifiers.png
  themes-default/slim/static/js/config/notifications.js
  themes-default/slim/views/config_anime.mako
  themes-default/slim/views/config_notifications.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/img/32x_sprite_colored_notifiers.png
  themes/dark/assets/js/config/notifications.js
  themes/dark/assets/js/config/notifications.js.map
  themes/dark/templates/config_anime.mako
  themes/dark/templates/config_notifications.mako
  themes/light/assets/css/style.css
  themes/light/assets/img/32x_sprite_colored_notifiers.png
  themes/light/assets/js/config/notifications.js
  themes/light/assets/js/config/notifications.js.map
  themes/light/templates/config_anime.mako
  themes/light/templates/config_notifications.mako
Labels: Concluded, Needs review, Squash / Rebase

#4235 newShow: Fix #4256, Fix #3359
  themes-default/slim/static/js/add-shows/new-show.js
  themes-default/slim/static/js/config/init.js
  themes-default/slim/static/js/config/subtitles.js
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/assets/js/add-shows/new-show.js
  themes/dark/assets/js/add-shows/new-show.js.map
  themes/dark/assets/js/config/init.js
  themes/dark/assets/js/config/init.js.map
  themes/dark/assets/js/config/subtitles.js
  themes/dark/assets/js/config/subtitles.js.map
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/light/assets/js/add-shows/new-show.js
  themes/light/assets/js/add-shows/new-show.js.map
  themes/light/assets/js/config/init.js
  themes/light/assets/js/config/init.js.map
  themes/light/assets/js/config/subtitles.js
  themes/light/assets/js/config/subtitles.js.map
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/vue-components/app-link.mako
Labels: Concluded, Needs review

#4268 Deluge: Check that the request didn't fail
  medusa/clients/torrent/deluge_client.py
Labels: Bug, Concluded, Needs review, Needs testing

#4262 Add YouTube Red network icon
  themes-default/slim/static/images/network/youtube red.png
  themes/dark/assets/img/network/youtube red.png
  themes/light/assets/img/network/youtube red.png
Labels: Concluded, Enhancement
