Repository pymedusa/Medusa, pull requests merged in 2018-02, with the labels that each got.

#3737 Parse error code to string before passing on to logger.
  medusa/clients/torrent/download_station_client.py
Labels: Bug, Concluded

#3738 Cast season to list, if passed as integer.
  medusa/tv/series.py
Labels: Bug, Concluded

#3739 Use fixed value of 1, self.indexer as a direct TVDBv2 attribute.
  medusa/indexers/tvdbv2/tvdbv2_api.py
Labels: Concluded

#3740 Use fixed value of 1, self.indexer as a direct TVDBv2 attribute
  medusa/indexers/tvdbv2/tvdbv2_api.py
Labels: Concluded

#3754 Fix exception when deleting a tvmaze show, with trakt enabled.
  medusa/trakt_checker.py
Labels: Bug, Concluded

#3761 Try to enable API tests
  .travis.yml
  dredd/api-description.yml
  dredd/dredd.yml
  package.json
Labels: Concluded

#3775 Fix branches missing in list when using git token in General Configuration
  themes-default/legacy/views/config_general.mako
  themes-default/slim/views/config_general.mako
  themes/dark/templates/config_general.mako
  themes/legacy/templates/config_general.mako
  themes/light/templates/config_general.mako
Labels: Bug, Concluded

#3773 Fix light theme when used icw a reverse proxy.
  themes-default/legacy/views/layouts/main.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/templates/layouts/main.mako
  themes/light/package.json
  themes/light/templates/layouts/main.mako
Labels: Bug, Concluded, Priority: 1. High

#3786 Update Medusa logo in readme.md
  readme.md
Labels: Concluded

#3768 Recommended series: Use dogpile for caching of the imdb, trakt and anidb shows
  medusa/cache.py
  medusa/show/recommendations/anidb.py
  medusa/show/recommendations/imdb.py
  medusa/show/recommendations/recommended.py
  medusa/show/recommendations/trakt.py
Labels: Concluded, Enhancement

#3787 Update Torrent9 domain, improve search query
  medusa/cache.py
  medusa/providers/torrent/html/torrent9.py
  tests/providers/torrent/torrent9/torrent9_test.yaml
Labels: Concluded, Enhancement

#3794 Replace jsonrpclib with Py3 compatible jsonrpclib-pelix, update msgpa…
  ext/jsonrpclib/SimpleJSONRPCServer.py
  ext/jsonrpclib/__init__.py
  ext/jsonrpclib/config.py
  ext/jsonrpclib/history.py
  ext/jsonrpclib/jsonclass.py
  ext/jsonrpclib/jsonrpc.py
  ext/jsonrpclib/threadpool.py
  ext/jsonrpclib/utils.py
  ext/msgpack/__init__.py
  ext/msgpack/_version.py
  ext/msgpack/fallback.py
  requirements.txt
Labels: Concluded, Enhancement

#3800 Update core.py
  medusa/server/api/v1/core.py
Labels: Bug, Concluded

#3803 Fix Newpct download parsing, update domain
  medusa/providers/torrent/html/newpct.py
  tests/providers/torrent/newpct/newpct_test.yaml
Labels: Bug, Concluded

#3807 Lazy load the anidb (simpleanidb) object on module level.
  medusa/show/recommendations/recommended.py
Labels: Bug, Concluded

#3813 Update indexer_base.py
  medusa/indexers/indexer_base.py
Labels: Concluded

#3816 Fix systemd startup
  runscripts/init.systemd
Labels: Bug, Concluded
