Repository pymedusa/Medusa, pull requests merged in 2018-06, with the labels that each got.

#4294 Fix sports shows not post-processing. Fixes #3708
  medusa/post_processor.py
Labels: Bug, Concluded

#4295 Fix UnicodeDecodeError on guessit guess
  medusa/name_parser/rules/rules.py
Labels: Bug, Concluded

#4297 Fix #3821 - anime naming %E with only absolute number
  medusa/tv/episode.py
Labels: Bug, Concluded

#4310 Fix changing status to Downloaded
  medusa/server/web/home/handler.py
Labels: Bug, Concluded, Needs review

#4309 Update enzyme - fixes embedded English subs tagged as undetermined
  ext/enzyme/__init__.py
  ext/enzyme/mkv.py
  ext/enzyme/tests/test_mkv.py
  requirements.txt
Labels: Bug, Concluded, Needs review

#4307 Fix ShowDirectoryNotFoundException on massEdit
  medusa/server/web/home/handler.py
Labels: Bug, Concluded, Needs review, Needs testing

#4298 Fix adding 2+ shows (that need searching) using Add Existing Show
  medusa/server/web/home/add_shows.py
  themes-default/slim/static/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js.map
  themes/light/assets/js/vue-submit-form.js
  themes/light/assets/js/vue-submit-form.js.map
Labels: Bug, Concluded, Needs review

#4312 Update Websocket
  medusa/server/core.py
  medusa/ui.py
  medusa/ws/MedusaWebSocketHandler.py
  pytest.ini
Labels: Bug, Concluded, Needs review

#4308 Fix IndexerShowNotFound when adding existing shows
  medusa/show_queue.py
Labels: Bug, Concluded, Needs review, Needs testing

#4045 switch config/search to vue
  themes-default/slim/static/js/config/search.js
  themes-default/slim/views/config_search.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/config/search.js
  themes/dark/assets/js/config/search.js.map
  themes/dark/templates/config_search.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/config/search.js
  themes/light/assets/js/config/search.js.map
  themes/light/templates/config_search.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4319 HeBits: Change BS4 parser to html.parser
  medusa/providers/torrent/html/hebits.py
Labels: Bug, Concluded

#4321 Fix LogLine.format_to_html on Windows systems
  medusa/logger/__init__.py
Labels: Bug, Concluded

#4328 Fix #4327 by converting quality to unsigned int
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/templates/editShow.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Bug, Concluded

#4059 Vueify Root Dirs
  medusa/server/api/v2/config.py
  medusa/server/api/v2/internal.py
  medusa/server/web/config/general.py
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/add-shows/init.js
  themes-default/slim/static/js/add-shows/new-show.js
  themes-default/slim/static/js/root-dirs.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/addShows_trendingShows.mako
  themes-default/slim/views/config_general.mako
  themes-default/slim/views/inc_rootDirs.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/root-dirs.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/add-shows/init.js
  themes/dark/assets/js/add-shows/init.js.map
  themes/dark/assets/js/add-shows/new-show.js
  themes/dark/assets/js/add-shows/new-show.js.map
  themes/dark/assets/js/root-dirs.js
  themes/dark/assets/js/root-dirs.js.map
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/addShows_trendingShows.mako
  themes/dark/templates/config_general.mako
  themes/dark/templates/inc_rootDirs.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/root-dirs.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/add-shows/init.js
  themes/light/assets/js/add-shows/init.js.map
  themes/light/assets/js/add-shows/new-show.js
  themes/light/assets/js/add-shows/new-show.js.map
  themes/light/assets/js/root-dirs.js
  themes/light/assets/js/root-dirs.js.map
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/addShows_trendingShows.mako
  themes/light/templates/config_general.mako
  themes/light/templates/inc_rootDirs.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/root-dirs.mako
Labels: Concluded, Enhancement

#4055 Vueify config
  themes-default/slim/static/js/config/backup-restore.js
  themes-default/slim/static/js/config/post-processing.js
  themes-default/slim/static/js/config/subtitles.js
  themes-default/slim/views/config_backuprestore.mako
  themes-default/slim/views/config_postProcessing.mako
  themes-default/slim/views/config_subtitles.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/config/backup-restore.js
  themes/dark/assets/js/config/backup-restore.js.map
  themes/dark/assets/js/config/post-processing.js
  themes/dark/assets/js/config/post-processing.js.map
  themes/dark/assets/js/config/subtitles.js
  themes/dark/assets/js/config/subtitles.js.map
  themes/dark/templates/config_backuprestore.mako
  themes/dark/templates/config_postProcessing.mako
  themes/dark/templates/config_subtitles.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/config/backup-restore.js
  themes/light/assets/js/config/backup-restore.js.map
  themes/light/assets/js/config/post-processing.js
  themes/light/assets/js/config/post-processing.js.map
  themes/light/assets/js/config/subtitles.js
  themes/light/assets/js/config/subtitles.js.map
  themes/light/templates/config_backuprestore.mako
  themes/light/templates/config_postProcessing.mako
  themes/light/templates/config_subtitles.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement, Needs review

#4336 Fix #4338 - addExistingShows dupe + skipping shows
  medusa/server/web/home/add_shows.py
  themes-default/slim/static/js/add-shows/new-show.js
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/assets/js/add-shows/new-show.js
  themes/dark/assets/js/add-shows/new-show.js.map
  themes/dark/templates/addShows_newShow.mako
  themes/light/assets/js/add-shows/new-show.js
  themes/light/assets/js/add-shows/new-show.js.map
  themes/light/templates/addShows_newShow.mako
Labels: Bug, Concluded, Needs review

#4337 Make sure all boolean values are returned as boolean
  medusa/app.py
  medusa/server/api/v2/config.py
Labels: Bug, Concluded

#4313 Feature/always pp manual searched files
  medusa/post_processor.py
  medusa/process_tv.py
Labels: Concluded, Enhancement, Needs testing

#4332 add puex store and vuex websockets
  themes-default/slim/static/js/lib/puex.js
  themes-default/slim/static/js/lib/vue-native-websocket-2.0.7.js
  themes-default/slim/static/js/store.js
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/lib/puex.js
  themes/dark/assets/js/lib/vue-native-websocket-2.0.7.js
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/lib/puex.js
  themes/light/assets/js/lib/vue-native-websocket-2.0.7.js
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4353 Fix Series.to_json
  medusa/tv/series.py
Labels: Bug, Concluded

#4352 Update issue submitter
  medusa/issue_submitter.py
  medusa/logger/__init__.py
  tests/test_logger.py
Labels: Concluded, Enhancement

#4357 move notifications to vue
  themes-default/slim/static/js/core.js
  themes-default/slim/static/js/notifications.js
  themes-default/slim/static/js/store.js
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/core.js
  themes/dark/assets/js/notifications.js
  themes/dark/assets/js/store.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/core.js
  themes/light/assets/js/notifications.js
  themes/light/assets/js/store.js
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement, Needs review

#4359 Handle exceptions on download method test web endpoints
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#4360 Fix WebSocket connection error message and gulp
  themes-default/slim/static/js/store.js
  themes/dark/assets/js/core.js.map
  themes/dark/assets/js/notifications.js.map
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/light/assets/js/core.js.map
  themes/light/assets/js/notifications.js.map
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
Labels: Concluded

#4348 Refactor file-browser component and use in select pages
  themes-default/slim/views/config_backuprestore.mako
  themes-default/slim/views/config_search.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/vue-components/file-browser.mako
  themes/dark/templates/config_backuprestore.mako
  themes/dark/templates/config_search.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/vue-components/file-browser.mako
  themes/light/templates/config_backuprestore.mako
  themes/light/templates/config_search.mako
  themes/light/templates/editShow.mako
  themes/light/templates/vue-components/file-browser.mako
Labels: Bug, Concluded

#4351 Strip more invalid filename characters - Fixes #3839
  medusa/helper/common.py
  tests/helper/__init__.py
  tests/helper/test_common.py
  tests/legacy/helper/common_tests.py
Labels: Bug, Concluded, Needs review

#4364 BTN: Fix AttributeError on DownloadURL
  medusa/providers/torrent/json/btn.py
Labels: Bug, Concluded

#4361 move more of schedule to vue
  themes-default/slim/static/js/store.js
  themes-default/slim/views/schedule.mako
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/templates/schedule.mako
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/templates/schedule.mako
Labels: Concluded, Enhancement

#4267 Vueify/new show
  medusa/classes.py
  medusa/server/api/v2/internal.py
  medusa/server/web/home/add_shows.py
  themes-default/slim/static/css/dark.css
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/add-show-options.js
  themes-default/slim/static/js/add-shows/new-show.js
  themes-default/slim/static/js/lib/formwizard.js
  themes-default/slim/static/js/lib/frisbee@2.0.4.min.js
  themes-default/slim/static/js/lib/vue-frisbee.min.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/css/dark.css
  themes/dark/assets/css/style.css
  themes/dark/assets/css/themed.css
  themes/dark/assets/js/add-show-options.js
  themes/dark/assets/js/add-show-options.js.map
  themes/dark/assets/js/add-shows/new-show.js
  themes/dark/assets/js/lib/formwizard.js
  themes/dark/assets/js/lib/frisbee@2.0.4.min.js
  themes/dark/assets/js/lib/vue-frisbee.min.js
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/css/dark.css
  themes/light/assets/css/style.css
  themes/light/assets/js/add-show-options.js
  themes/light/assets/js/add-show-options.js.map
  themes/light/assets/js/add-shows/new-show.js
  themes/light/assets/js/lib/formwizard.js
  themes/light/assets/js/lib/frisbee@2.0.4.min.js
  themes/light/assets/js/lib/vue-frisbee.min.js
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4339 editShow: Replace checkboxes with toggle-button
  themes-default/slim/static/js/lib/vue-js-toggle-button.js
  themes-default/slim/static/js/vue-submit-form.js
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/medusa-toggle.mako
  themes/dark/assets/js/lib/vue-js-toggle-button.js
  themes/dark/assets/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js.map
  themes/dark/templates/editShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/medusa-toggle.mako
  themes/light/assets/js/lib/vue-js-toggle-button.js
  themes/light/assets/js/vue-submit-form.js
  themes/light/assets/js/vue-submit-form.js.map
  themes/light/templates/editShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/medusa-toggle.mako
Labels: Enhancement

#4366 NZBget: Handle socket.error gracefully. Fixes #4340
  medusa/clients/nzb/nzbget.py
Labels: Bug, Concluded

#4363 Add new values to the config API endpoint
  dredd/api-description.yml
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/static/js/store.js
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
Labels: Concluded, Enhancement

#4372 fix assets not loading in some home layouts
  themes-default/slim/views/partials/home/banner.mako
  themes-default/slim/views/partials/home/small.mako
  themes-default/slim/views/vue-components/asset.mako
  themes/dark/templates/partials/home/banner.mako
  themes/dark/templates/partials/home/small.mako
  themes/dark/templates/vue-components/asset.mako
  themes/light/templates/partials/home/banner.mako
  themes/light/templates/partials/home/small.mako
  themes/light/templates/vue-components/asset.mako
Labels: Bug, Concluded

#4380 Fix some spelling mistakes in the code
  medusa/helpers/externals.py
  medusa/indexers/indexer_exceptions.py
  medusa/show/recommendations/trakt.py
  medusa/show_queue.py
  themes-default/slim/gulpfile.js
Labels: Concluded, Enhancement

#4378 Fix add show search keeps requesting spinner image
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/light/templates/addShows_newShow.mako
Labels: Concluded

#4383 add more config fields to store
  themes-default/slim/static/js/store.js
  themes/dark/assets/js/store.js
  themes/light/assets/js/store.js
Labels: Concluded, Enhancement, Needs review

#4392 Ignore .@__thumb folders.
  medusa/process_tv.py
Labels: Concluded

#4400 API v1 - Fix fetching history with type
  medusa/show/history.py
Labels: Bug, Concluded

#4393 BTN: Catch 500 Internal Server Error
  medusa/providers/torrent/json/btn.py
Labels: Bug, Concluded

#4397 Gulp sync
  themes/dark/assets/js/store.js.map
  themes/light/assets/js/store.js.map
Labels: Concluded

#4395 Render restart page before updating to prevent errors
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#4401 Fix toggle-button.
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/medusa-toggle.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/medusa-toggle.mako
  themes/light/templates/editShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/medusa-toggle.mako
Labels: Bug, Concluded

#4377 Fix similar issues tests and empty issue titles
  medusa/github_client.py
  medusa/issue_submitter.py
  medusa/logger/__init__.py
  tests/conftest.py
  tests/test_issue_submitter.py
  tests/test_logger.py
Labels: Concluded

#4388 Improve shutil_custom. Should fix #4362
  lib/shutil_custom/__init__.py
  medusa/process_tv.py
Labels: Bug, Concluded, Needs review, Needs testing

#4394 Fix #4375 - support unicode chars in censored items
  medusa/logger/__init__.py
Labels: Bug, Concluded

#4406 Make sure the file exists before checking is_rarfile(). Fixes #4405
  medusa/post_processor.py
Labels: Bug, Concluded

#4379 Fix #4369 - exception when getting TVDB actors
  medusa/indexers/tvdbv2/tvdbv2_api.py
Labels: Bug, Concluded

#4409 Fix issue submitter speed
  medusa/github_client.py
  medusa/issue_submitter.py
  tests/test_issue_submitter.py
Labels: Bug, Concluded

#4398 Fix Tornado request logging
  medusa/server/core.py
Labels: Concluded, Enhancement

#4403 Fix #4402 - Only Absolute Number broken for SxxExx format
  medusa/tv/episode.py
Labels: Bug, Concluded, Needs testing

#4445 TVDB: Fix exception when no updates are returned. Fixes #4419
  medusa/indexers/tvdbv2/tvdbv2_api.py
Labels: Bug, Concluded

#4410 Improve detection of quality from filename
  medusa/common.py
  medusa/providers/generic_provider.py
  medusa/recompiled/tags.py
  medusa/tagger/episode.py
  tests/test_common.py
Labels: Concluded, Enhancement

#4288 Add vue component name-pattern.mako
  themes-default/slim/static/js/lib/date_fns.min.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/name-pattern.mako
  themes/dark/assets/js/lib/date_fns.min.js
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/name-pattern.mako
  themes/light/assets/js/lib/date_fns.min.js
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/name-pattern.mako
Labels: Concluded, Enhancement

#4452 Fix exception when Transmission is unreachable
  medusa/clients/torrent/transmission_client.py
  medusa/search/queue.py
Labels: Bug, Concluded, Needs review, Needs testing

#4453 Fix #4408 - Search delay UI bug with fractions
  themes-default/slim/views/config_providers.mako
  themes/dark/templates/config_providers.mako
  themes/light/templates/config_providers.mako
Labels: Bug, Concluded

#4396 addShows: Fix Windows paths
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
Labels: Concluded

#4454 Patch race condition when changing schedule layout
  themes-default/slim/static/js/lib/date_fns.min.js
  themes-default/slim/static/js/store.js
  themes/dark/assets/js/lib/date_fns.min.js
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/light/assets/js/lib/date_fns.min.js
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
Labels: Bug, Concluded

#4460 EditShow: Fix saving dvdOrder
  themes-default/slim/views/editShow.mako
  themes/dark/templates/editShow.mako
  themes/light/templates/editShow.mako
Labels: Bug, Concluded

#4457 Feature/vueiy backstretch
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/backstretch.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/backstretch.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/backstretch.mako
Labels: Concluded, Enhancement

#4404 add more fields to config including patch
  dredd/api-description.yml
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/static/js/store.js
  themes/dark/assets/js/store.js
  themes/light/assets/js/store.js
Labels: Concluded, Enhancement

#4455 Update TVDB urls
  medusa/indexers/indexer_config.py
  medusa/indexers/tvdbv2/tvdbv2_api.py
  medusa/show/recommendations/trakt.py
Labels: Concluded, Enhancement, Priority: 3. Low

#4465 Add feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Concluded, Enhancement

#4464 Add bug report issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Concluded, Enhancement

#4469 Delete ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE.md
Labels: Concluded, Enhancement

#4470 Add logs section to bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Bug, Concluded

#4376 fix asset 404
  medusa/media/generic.py
  medusa/server/api/v2/series_asset.py
  medusa/tv/series.py
  themes-default/slim/static/js/core.js
  themes-default/slim/views/partials/schedule/banner.mako
  themes-default/slim/views/partials/schedule/calendar.mako
  themes-default/slim/views/partials/schedule/poster.mako
  themes-default/slim/views/vue-components/asset.mako
  themes/dark/assets/js/core.js
  themes/dark/assets/js/core.js.map
  themes/dark/templates/partials/schedule/banner.mako
  themes/dark/templates/partials/schedule/calendar.mako
  themes/dark/templates/partials/schedule/poster.mako
  themes/dark/templates/vue-components/asset.mako
  themes/light/assets/js/core.js
  themes/light/assets/js/core.js.map
  themes/light/templates/partials/schedule/banner.mako
  themes/light/templates/partials/schedule/calendar.mako
  themes/light/templates/partials/schedule/poster.mako
  themes/light/templates/vue-components/asset.mako
Labels: Bug, Concluded, Discussion

#4473 Fix CI tests
  .travis.yml
  setup.py
Labels: Concluded

#4476 Update yarn.lock
  yarn.lock
Labels: Concluded

#4462 Vueify/misc changes
  medusa/server/api/v2/config.py
  themes-default/slim/static/js/core.js
  themes-default/slim/static/js/home/index.js
  themes-default/slim/static/js/store.js
  themes-default/slim/views/config_notifications.mako
  themes-default/slim/views/config_providers.mako
  themes-default/slim/views/config_search.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/history.mako
  themes-default/slim/views/home.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage.mako
  themes-default/slim/views/manage_failedDownloads.mako
  themes-default/slim/views/partials/home/poster.mako
  themes-default/slim/views/partials/schedule/banner.mako
  themes-default/slim/views/partials/schedule/calendar.mako
  themes-default/slim/views/partials/schedule/poster.mako
  themes-default/slim/views/schedule.mako
  themes-default/slim/views/vue-components/asset.mako
  themes/dark/assets/js/core.js
  themes/dark/assets/js/home/index.js
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/templates/config_notifications.mako
  themes/dark/templates/config_providers.mako
  themes/dark/templates/config_search.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/history.mako
  themes/dark/templates/home.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage.mako
  themes/dark/templates/manage_failedDownloads.mako
  themes/dark/templates/partials/home/poster.mako
  themes/dark/templates/partials/schedule/banner.mako
  themes/dark/templates/partials/schedule/calendar.mako
  themes/dark/templates/partials/schedule/poster.mako
  themes/dark/templates/schedule.mako
  themes/dark/templates/vue-components/asset.mako
  themes/light/assets/js/core.js
  themes/light/assets/js/home/index.js
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/templates/config_notifications.mako
  themes/light/templates/config_providers.mako
  themes/light/templates/config_search.mako
  themes/light/templates/editShow.mako
  themes/light/templates/history.mako
  themes/light/templates/home.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage.mako
  themes/light/templates/manage_failedDownloads.mako
  themes/light/templates/partials/home/poster.mako
  themes/light/templates/partials/schedule/banner.mako
  themes/light/templates/partials/schedule/calendar.mako
  themes/light/templates/partials/schedule/poster.mako
  themes/light/templates/schedule.mako
  themes/light/templates/vue-components/asset.mako
Labels: Concluded, Enhancement

#4477 Fix missing Medusa Info on config page
  themes-default/slim/views/config.mako
  themes/dark/templates/config.mako
  themes/light/templates/config.mako
Labels: Concluded, Enhancement

#4478 Fix bugs in schedule banner layout
  themes-default/slim/views/partials/schedule/banner.mako
  themes/dark/assets/js/core.js.map
  themes/dark/assets/js/home/index.js.map
  themes/dark/templates/partials/schedule/banner.mako
  themes/light/assets/js/core.js.map
  themes/light/assets/js/home/index.js.map
  themes/light/templates/partials/schedule/banner.mako
Labels: Bug, Concluded

#4311 Refactor search/core.py: Fixes #4201 & fixes #4168. Maybe fixes #4208
  medusa/classes.py
  medusa/common.py
  medusa/search/core.py
  medusa/search/proper.py
  medusa/server/web/home/handler.py
  tests/conftest.py
  tests/test_common.py
  tests/test_search_core.py
  themes-default/slim/views/config_providers.mako
  themes/dark/templates/config_providers.mako
  themes/light/templates/config_providers.mako
Labels: Bug, Concluded, Needs review, Needs testing

#4479 remove unused isMeta
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
  themes-default/slim/static/js/blackwhite.js
  themes-default/slim/static/js/browser.js
  themes-default/slim/static/js/config/index.js
  themes-default/slim/static/js/core.js
  themes-default/slim/static/js/home/display-show.js
  themes-default/slim/static/js/home/index.js
  themes-default/slim/static/js/home/snatch-selection.js
  themes-default/slim/static/js/manage/backlog-overview.js
  themes-default/slim/static/js/manage/manage-searches.js
  themes-default/slim/static/js/mass-update.js
  themes-default/slim/static/js/vue-submit-form.js
  themes/dark/assets/js/blackwhite.js
  themes/dark/assets/js/browser.js
  themes/dark/assets/js/browser.js.map
  themes/dark/assets/js/config/index.js
  themes/dark/assets/js/config/index.js.map
  themes/dark/assets/js/core.js
  themes/dark/assets/js/core.js.map
  themes/dark/assets/js/home/display-show.js
  themes/dark/assets/js/home/display-show.js.map
  themes/dark/assets/js/home/index.js
  themes/dark/assets/js/home/index.js.map
  themes/dark/assets/js/home/snatch-selection.js
  themes/dark/assets/js/home/snatch-selection.js.map
  themes/dark/assets/js/manage/backlog-overview.js
  themes/dark/assets/js/manage/backlog-overview.js.map
  themes/dark/assets/js/manage/manage-searches.js
  themes/dark/assets/js/manage/manage-searches.js.map
  themes/dark/assets/js/mass-update.js
  themes/dark/assets/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js.map
  themes/dark/package.json
  themes/light/assets/js/blackwhite.js
  themes/light/assets/js/browser.js
  themes/light/assets/js/browser.js.map
  themes/light/assets/js/config/index.js
  themes/light/assets/js/config/index.js.map
  themes/light/assets/js/core.js
  themes/light/assets/js/core.js.map
  themes/light/assets/js/home/display-show.js
  themes/light/assets/js/home/display-show.js.map
  themes/light/assets/js/home/index.js
  themes/light/assets/js/home/index.js.map
  themes/light/assets/js/home/snatch-selection.js
  themes/light/assets/js/home/snatch-selection.js.map
  themes/light/assets/js/manage/backlog-overview.js
  themes/light/assets/js/manage/backlog-overview.js.map
  themes/light/assets/js/manage/manage-searches.js
  themes/light/assets/js/manage/manage-searches.js.map
  themes/light/assets/js/mass-update.js
  themes/light/assets/js/vue-submit-form.js
  themes/light/assets/js/vue-submit-form.js.map
  themes/light/package.json
Labels: Concluded, Enhancement

#4481 Vueify show selector
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/home/display-show.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/partials/showSelector.mako
  themes-default/slim/views/partials/submenu.mako
  themes-default/slim/views/vue-components/show-selector.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/home/display-show.js
  themes/dark/assets/js/home/display-show.js.map
  themes/dark/templates/displayShow.mako
  themes/dark/templates/partials/showSelector.mako
  themes/dark/templates/partials/submenu.mako
  themes/dark/templates/vue-components/show-selector.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/home/display-show.js
  themes/light/assets/js/home/display-show.js.map
  themes/light/templates/displayShow.mako
  themes/light/templates/partials/showSelector.mako
  themes/light/templates/partials/submenu.mako
  themes/light/templates/vue-components/show-selector.mako
Labels: Concluded, Enhancement

#4485 Fix YggTorrent size parsing + enable tests
  medusa/helper/common.py
  medusa/providers/torrent/html/yggtorrent.py
  tests/helper/test_common.py
  tests/providers/conftest.py
  tests/providers/test_search.py
  tests/providers/torrent/yggtorrent/yggtorrent_backlog.yaml
  tests/providers/torrent/yggtorrent/yggtorrent_daily.yaml
  tests/providers/torrent/yggtorrent/yggtorrent_test.yaml
Labels: Bug, Concluded, Enhancement

#4487 Refactor provider tests
  tests/providers/test_search.py
Labels: Enhancement

#4490 Fix Travis JS tests & cleanup
  .travis.yml
  gulpfile.js
  package.json
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  yarn.lock
Labels: Concluded, Enhancement

#4456 WebSocket: Message class and configUpdated event
  medusa/server/api/v2/config.py
  medusa/server/core.py
  medusa/ui.py
  medusa/ws/__init__.py
  medusa/ws/handler.py
  pytest.ini
  tests/test_ws.py
  themes-default/slim/static/js/store.js
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4494 Fix build, sync themes
  gulpfile.js
  themes-default/slim/static/js/store.js
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/package.json
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/package.json
Labels: Concluded, Enhancement

#4506 Fix asset sizes
  themes-default/slim/views/partials/home/small.mako
  themes-default/slim/views/partials/schedule/poster.mako
  themes/dark/templates/partials/home/small.mako
  themes/dark/templates/partials/schedule/poster.mako
  themes/light/templates/partials/home/small.mako
  themes/light/templates/partials/schedule/poster.mako
Labels: Bug, Concluded

#4507 Simplify/Improve YggTorrent pubdate parsing
  medusa/providers/torrent/html/yggtorrent.py
  tests/providers/torrent/yggtorrent/yggtorrent_test.yaml
Labels: Concluded, Enhancement

#4491 Update pickManualSearch - fixes #3134
  medusa/server/web/home/handler.py
  themes-default/slim/views/snatchSelection.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/templates/snatchSelection.mako
Labels: Bug, Concluded, Needs review
