Repository pymedusa/Medusa, pull requests merged in 2018-03, with the labels that each got.

#3809 Feature/anime parsing
  medusa/name_parser/parser.py
  medusa/scene_exceptions.py
  medusa/scene_numbering.py
  medusa/server/web/home/handler.py
  tests/conftest.py
  tests/name_parser/__init__.py
  tests/name_parser/parse_air_by_date.py
  tests/name_parser/test_parse_anime.py
  tests/name_parser/test_parse_series.py
Labels: Bug, Concluded

#3826 apiv1: Add error handling, for looking up show artwork through apiv1.
  medusa/server/api/v1/core.py
  themes-default/legacy/views/apiBuilder.mako
  themes-default/slim/views/apiBuilder.mako
  themes/dark/templates/apiBuilder.mako
  themes/light/templates/apiBuilder.mako
Labels: Bug, Concluded

#3832 Use future xmlrpc.client instead of six.moves.xmlrpc_client
  medusa/clients/nzb/nzbget.py
Labels: Bug, Concluded

#3837 Use absolute_number argument instead of absolute. Fixes #3836
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#3852 More changes for Python 3 compatibility
  medusa/failed_history.py
  medusa/notifiers/prowl.py
Labels: Bug, Concluded

#3853 Fix deluge client reference to wrong variable. Fixes #3850
  medusa/clients/torrent/deluge_client.py
Labels: Bug, Concluded

#3855 Parse runtime (int) to str.
  medusa/metadata/kodi_12plus.py
Labels: Bug, Concluded

#3864 Fix missing credential when submiting issues using git token
  medusa/issue_submitter.py
Labels: Bug, Concluded

#3867 Fix ConnectionError reported as exception in ShowUpdater
  medusa/show_updater.py
Labels: Concluded, Enhancement

#3868 Translate "à l'instant" for Yggtorrent provider. Fixes #3865
  medusa/providers/torrent/html/yggtorrent.py
Labels: Concluded, Enhancement

#3877 Feature/add vue components
  themes-default/slim/static/js/lib/vue-in-viewport-mixin.min.js
  themes-default/slim/views/vue-components/app-link.mako
  themes-default/slim/views/vue-components/asset.mako
  themes-default/slim/views/vue-components/file-browser.mako
  themes/dark/assets/js/lib/vue-in-viewport-mixin.min.js
  themes/dark/templates/vue-components/app-link.mako
  themes/dark/templates/vue-components/asset.mako
  themes/dark/templates/vue-components/file-browser.mako
  themes/light/assets/js/lib/vue-in-viewport-mixin.min.js
  themes/light/templates/vue-components/app-link.mako
  themes/light/templates/vue-components/asset.mako
  themes/light/templates/vue-components/file-browser.mako
Labels: Concluded, Enhancement, Priority: 2. Medium

#3900 Add truth_to_bool to support a wide range of truth values
  medusa/helpers/utils.py
  medusa/server/web/core/file_browser.py
Labels: Concluded, Enhancement

#3903 Fix/app link
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/light/templates/vue-components/app-link.mako
Labels: Bug, Concluded

#3902 Fix blackwhite.js
  themes-default/slim/static/js/blackwhite.js
  themes/dark/assets/js/blackwhite.js
  themes/light/assets/js/blackwhite.js
Labels: Bug, Concluded

#3912 Add back pkg_resources to /lib as it is required by babelfish
  lib/pkg_resources/__init__.py
  lib/pkg_resources/_vendor/__init__.py
  lib/pkg_resources/_vendor/appdirs.py
  lib/pkg_resources/_vendor/packaging/__about__.py
  lib/pkg_resources/_vendor/packaging/__init__.py
  lib/pkg_resources/_vendor/packaging/_compat.py
  lib/pkg_resources/_vendor/packaging/_structures.py
  lib/pkg_resources/_vendor/packaging/markers.py
  lib/pkg_resources/_vendor/packaging/requirements.py
  lib/pkg_resources/_vendor/packaging/specifiers.py
  lib/pkg_resources/_vendor/packaging/utils.py
  lib/pkg_resources/_vendor/packaging/version.py
  lib/pkg_resources/_vendor/pyparsing.py
  lib/pkg_resources/_vendor/six.py
  lib/pkg_resources/_vendor/vendored.txt
  lib/pkg_resources/api_tests.txt
  lib/pkg_resources/extern/__init__.py
  lib/pkg_resources/py31compat.py
  lib/pkg_resources/tests/__init__.py
  lib/pkg_resources/tests/test_find_distributions.py
  lib/pkg_resources/tests/test_markers.py
  lib/pkg_resources/tests/test_pkg_resources.py
  lib/pkg_resources/tests/test_resources.py
  lib/pkg_resources/tests/test_working_set.py
Labels: Concluded

#3913 Change fanart to use series-slug in edit-show.js
  themes-default/slim/static/js/home/edit-show.js
  themes/dark/assets/js/blackwhite.js
  themes/dark/assets/js/blackwhite.js.map
  themes/dark/assets/js/home/edit-show.js
  themes/dark/assets/js/home/edit-show.js.map
  themes/light/assets/js/blackwhite.js.map
  themes/light/assets/js/home/edit-show.js
  themes/light/assets/js/home/edit-show.js.map
Labels: Concluded, Enhancement

#3924 Upgrade Subliminal to 879c0c8d18618e32ad466bb63bd939edb268bc60
  ext/subliminal/core.py
  ext/subliminal/providers/addic7ed.py
  ext/subliminal/providers/opensubtitles.py
  ext/subliminal/providers/tvsubtitles.py
  ext/subliminal/subtitle.py
  ext/subliminal/video.py
  requirements.txt
Labels: Concluded
