Repository pymedusa/Medusa, pull requests merged in 2018-04, with the labels that each got.

#3491 Don't allow save custom provider if bad name
  medusa/server/web/config/providers.py
Labels: Concluded, Enhancement

#3959 Fix Newznab providers without supportedParams. Fixes #1729
  medusa/providers/nzb/newznab.py
  medusa/providers/torrent/torznab/torznab.py
Labels: Bug, Concluded

#3962 Remove GFTracker (dead), add default URL to Bitcannon
  medusa/providers/__init__.py
  medusa/providers/generic_provider.py
  medusa/providers/torrent/__init__.py
  medusa/providers/torrent/html/gftracker.py
  medusa/providers/torrent/html/torrent9.py
  medusa/providers/torrent/json/bitcannon.py
  medusa/providers/torrent/json/hdbits.py
  themes-default/legacy/static/images/providers/gftracker.png
  themes-default/slim/static/images/providers/gftracker.png
  themes/dark/assets/img/providers/gftracker.png
  themes/legacy/assets/img/providers/gftracker.png
  themes/light/assets/img/providers/gftracker.png
Labels: Concluded, Enhancement

#3905 Move js to vue
  themes-default/slim/static/js/history/index.js
  themes-default/slim/static/js/manage/mass-edit.js
  themes-default/slim/static/js/mass-edit.js
  themes-default/slim/static/js/schedule/index.js
  themes-default/slim/views/history.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_massEdit.mako
  themes-default/slim/views/schedule.mako
  themes/dark/assets/js/history/index.js
  themes/dark/assets/js/history/index.js.map
  themes/dark/assets/js/manage/mass-edit.js
  themes/dark/assets/js/manage/mass-edit.js.map
  themes/dark/assets/js/mass-edit.js
  themes/dark/assets/js/mass-edit.js.map
  themes/dark/assets/js/schedule/index.js
  themes/dark/assets/js/schedule/index.js.map
  themes/dark/templates/history.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_massEdit.mako
  themes/dark/templates/schedule.mako
  themes/light/assets/js/history/index.js
  themes/light/assets/js/history/index.js.map
  themes/light/assets/js/manage/mass-edit.js
  themes/light/assets/js/manage/mass-edit.js.map
  themes/light/assets/js/mass-edit.js
  themes/light/assets/js/mass-edit.js.map
  themes/light/assets/js/schedule/index.js
  themes/light/assets/js/schedule/index.js.map
  themes/light/templates/history.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_massEdit.mako
  themes/light/templates/schedule.mako
Labels: Concluded, Enhancement

#3947 Fixes for non-Vue scripts
  themes-default/slim/static/js/add-show-options.js
  themes-default/slim/static/js/mass-update.js
  themes-default/slim/static/js/quality-chooser.js
  themes-default/slim/views/config_subtitles.mako
  themes-default/slim/views/history.mako
  themes/dark/assets/js/add-show-options.js
  themes/dark/assets/js/add-show-options.js.map
  themes/dark/assets/js/mass-update.js
  themes/dark/assets/js/mass-update.js.map
  themes/dark/assets/js/quality-chooser.js
  themes/dark/assets/js/quality-chooser.js.map
  themes/dark/templates/config_subtitles.mako
  themes/dark/templates/history.mako
  themes/light/assets/js/add-show-options.js
  themes/light/assets/js/add-show-options.js.map
  themes/light/assets/js/mass-update.js
  themes/light/assets/js/mass-update.js.map
  themes/light/assets/js/quality-chooser.js
  themes/light/assets/js/quality-chooser.js.map
  themes/light/templates/config_subtitles.mako
  themes/light/templates/history.mako
Labels: Concluded

#3986 Move /schedule route out of base, use get_argument, remove post = get, update Tornado
  ext/pytz/__init__.py
  ext/pytz/lazy.py
  ext/pytz/tzinfo.py
  ext/pytz/zoneinfo/Africa/Bissau
  ext/pytz/zoneinfo/Africa/Sao_Tome
  ext/pytz/zoneinfo/America/Grand_Turk
  ext/pytz/zoneinfo/America/Jamaica
  ext/pytz/zoneinfo/America/Montevideo
  ext/pytz/zoneinfo/Antarctica/Casey
  ext/pytz/zoneinfo/Asia/Gaza
  ext/pytz/zoneinfo/Asia/Hebron
  ext/pytz/zoneinfo/Asia/Macao
  ext/pytz/zoneinfo/Asia/Macau
  ext/pytz/zoneinfo/Atlantic/Azores
  ext/pytz/zoneinfo/Atlantic/Cape_Verde
  ext/pytz/zoneinfo/Atlantic/Madeira
  ext/pytz/zoneinfo/Europe/Lisbon
  ext/pytz/zoneinfo/Jamaica
  ext/pytz/zoneinfo/Pacific/Enderbury
  ext/pytz/zoneinfo/Pacific/Kiritimati
  ext/pytz/zoneinfo/Portugal
  ext/pytz/zoneinfo/tzdata.zi
  ext/pytz/zoneinfo/zone.tab
  ext/pytz/zoneinfo/zone1970.tab
  ext/tornado/__init__.py
  ext/tornado/httpclient.py
  ext/tornado/ioloop.py
  ext/tornado/platform/asyncio.py
  ext/tornado/test/asyncio_test.py
  ext/tornado/test/ioloop_test.py
  ext/tornado/test/testing_test.py
  ext/tornado/testing.py
  medusa/server/web/__init__.py
  medusa/server/web/core/__init__.py
  medusa/server/web/core/base.py
  medusa/server/web/core/schedule.py
  pytest.ini
  requirements.txt
  setup.py
  themes-default/legacy/views/schedule.mako
  themes-default/slim/views/schedule.mako
  themes/dark/templates/schedule.mako
  themes/legacy/assets/img/providers/acid_lounge.png
  themes/legacy/assets/img/providers/acidlounge.png
  themes/legacy/assets/img/providers/btdb.png
  themes/legacy/assets/img/providers/filelist.png
  themes/legacy/assets/img/providers/sickbeardindex.png
  themes/legacy/templates/schedule.mako
  themes/light/templates/schedule.mako
Labels: Concluded, Enhancement

#3990 Fix Growl registration. Fixes #3974
  medusa/notifiers/growl.py
Labels: Bug, Concluded

#3991 Fix email notification settings not saving. Fixes #3971
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#4016 update vue-in-viewport-mixin
  themes-default/slim/static/js/lib/vue-in-viewport-mixin.min.js
  themes/dark/assets/js/lib/vue-in-viewport-mixin.min.js
  themes/light/assets/js/lib/vue-in-viewport-mixin.min.js
Labels: Bug, Concluded

#4011 Configure subtitle cache after "erase subtitle cache" action
  medusa/__main__.py
Labels: Bug, Concluded

#4010 Fix 3 torrent providers using naive time zones
  medusa/providers/torrent/html/sdbits.py
  medusa/providers/torrent/json/danishbits.py
  medusa/providers/torrent/json/hdbits.py
Labels: Bug, Concluded

#4012 Torrent Checker: Show warning when connection error
  medusa/torrent_checker.py
Labels: Concluded

#4031 move js to viewlogs page
  themes-default/slim/static/js/errorlogs/viewlogs.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/viewlogs.mako
  themes/dark/assets/js/errorlogs/viewlogs.js
  themes/dark/assets/js/errorlogs/viewlogs.js.map
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/viewlogs.mako
  themes/light/assets/js/errorlogs/viewlogs.js
  themes/light/assets/js/errorlogs/viewlogs.js.map
  themes/light/templates/layouts/main.mako
  themes/light/templates/viewlogs.mako
Labels: Concluded, Enhancement

#4035 Added component for showing saving, saved, or error messages.
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/saved-message.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/saved-message.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/saved-message.mako
Labels: Concluded, Enhancement

#4036 Fix client download for Jackett providers with magnet redirects
  medusa/clients/torrent/qbittorrent_client.py
  medusa/providers/generic_provider.py
  medusa/providers/torrent/torrent_provider.py
  medusa/search/core.py
  medusa/server/core.py
  medusa/session/core.py
Labels: Bug, Concluded

#4027 Fix exception when trying to save default show settings. Fixes #4002
  themes-default/slim/static/js/add-show-options.js
  themes-default/slim/static/js/add-shows/init.js
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/inc_addShowOptions.mako
  themes/dark/assets/js/add-show-options.js
  themes/dark/assets/js/add-show-options.js.map
  themes/dark/assets/js/add-shows/init.js
  themes/dark/assets/js/add-shows/init.js.map
  themes/dark/templates/editShow.mako
  themes/dark/templates/inc_addShowOptions.mako
  themes/light/assets/js/add-show-options.js
  themes/light/assets/js/add-show-options.js.map
  themes/light/assets/js/add-shows/init.js
  themes/light/assets/js/add-shows/init.js.map
  themes/light/templates/editShow.mako
  themes/light/templates/inc_addShowOptions.mako
Labels: Bug, Concluded

#4047 Fix sab when there's no connection
  medusa/clients/nzb/sab.py
Labels: Bug

#4050 Fix BTN API exception on connection error
  medusa/providers/torrent/json/btn.py
Labels: Bug, Concluded

#4051 Delete nextgen.png from themes-default/slim
  themes-default/slim/static/images/providers/nextgen.png
Labels: Concluded, Priority: 3. Low

#3818 move quality-chooser to vue
  themes-default/slim/static/js/add-show-options.js
  themes-default/slim/static/js/add-shows/new-show.js
  themes-default/slim/static/js/quality-chooser.js
  themes-default/slim/static/js/vue-submit-form.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/addShows_trendingShows.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/inc_addShowOptions.mako
  themes-default/slim/views/inc_qualityChooser.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_massEdit.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/assets/js/add-show-options.js
  themes/dark/assets/js/add-show-options.js.map
  themes/dark/assets/js/add-shows/new-show.js
  themes/dark/assets/js/add-shows/new-show.js.map
  themes/dark/assets/js/quality-chooser.js
  themes/dark/assets/js/quality-chooser.js.map
  themes/dark/assets/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js.map
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/addShows_trendingShows.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/inc_addShowOptions.mako
  themes/dark/templates/inc_qualityChooser.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_massEdit.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/assets/js/add-show-options.js
  themes/light/assets/js/add-show-options.js.map
  themes/light/assets/js/add-shows/new-show.js
  themes/light/assets/js/add-shows/new-show.js.map
  themes/light/assets/js/quality-chooser.js
  themes/light/assets/js/quality-chooser.js.map
  themes/light/assets/js/vue-submit-form.js
  themes/light/assets/js/vue-submit-form.js.map
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/addShows_trendingShows.mako
  themes/light/templates/editShow.mako
  themes/light/templates/inc_addShowOptions.mako
  themes/light/templates/inc_qualityChooser.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_massEdit.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Concluded, Enhancement, Needs review, Needs testing

#4024 Fix "Add Existing Show" page
  themes-default/slim/static/js/add-shows/add-existing-show.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/home_massAddTable.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/add-shows/add-existing-show.js
  themes/dark/assets/js/add-shows/add-existing-show.js.map
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/home_massAddTable.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/add-shows/add-existing-show.js
  themes/light/assets/js/add-shows/add-existing-show.js.map
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/home_massAddTable.mako
  themes/light/templates/layouts/main.mako
Labels: Bug, Concluded, Needs review

#4057 Always show "Keep" option for quality chooser on mass edit page
  themes-default/slim/views/manage_massEdit.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/templates/manage_massEdit.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/templates/manage_massEdit.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Concluded, Discussion, Enhancement

#4082 Never split torrent files on NZB providers. Fix #3946
  medusa/nzb_splitter.py
  medusa/providers/generic_provider.py
  medusa/search/core.py
Labels: Bug, Concluded, Needs review, Needs testing

#4086 Fix import for gntp. Fixes #4084
  medusa/notifiers/growl.py
Labels: Bug, Concluded

#4089 Replace cmp with itemgetter/attrgetter or key
  medusa/browser.py
  medusa/generic_queue.py
  medusa/server/web/core/base.py
  medusa/server/web/home/handler.py
  medusa/show/coming_episodes.py
  themes-default/slim/static/js/home/index.js
  themes-default/slim/static/js/parsers.js
  themes-default/slim/views/manage.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes-default/slim/views/partials/home/banner.mako
  themes-default/slim/views/partials/home/poster.mako
  themes-default/slim/views/partials/home/simple.mako
  themes-default/slim/views/partials/home/small.mako
  themes-default/slim/views/viewlogs.mako
  themes/dark/assets/js/home/index.js
  themes/dark/assets/js/parsers.js
  themes/dark/templates/manage.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/dark/templates/partials/home/banner.mako
  themes/dark/templates/partials/home/poster.mako
  themes/dark/templates/partials/home/simple.mako
  themes/dark/templates/partials/home/small.mako
  themes/dark/templates/viewlogs.mako
  themes/light/assets/js/home/index.js
  themes/light/assets/js/parsers.js
  themes/light/templates/manage.mako
  themes/light/templates/manage_backlogOverview.mako
  themes/light/templates/partials/home/banner.mako
  themes/light/templates/partials/home/poster.mako
  themes/light/templates/partials/home/simple.mako
  themes/light/templates/partials/home/small.mako
  themes/light/templates/viewlogs.mako
Labels: Concluded, Needs testing

#4096 Cache: Fix incorrect return value
  medusa/db.py
  medusa/tv/cache.py
Labels: Bug, Concluded, Needs review, Needs testing

#4075 Fixes for editShow
  .travis.yml
  medusa/server/api/v2/series.py
  medusa/server/web/home/handler.py
  medusa/tv/episode.py
  medusa/tv/series.py
  themes-default/slim/static/images/curved-arrow-left.png
  themes-default/slim/static/images/curved-arrow-right.png
  themes-default/slim/static/js/browser.js
  themes-default/slim/static/js/edit-show.js
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/anidb-release-group-ui.mako
  themes-default/slim/views/vue-components/file-browser.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes-default/slim/views/vue-components/select-list-ui.mako
  themes/dark/assets/js/browser.js
  themes/dark/assets/js/browser.js.map
  themes/dark/assets/js/edit-show.js
  themes/dark/assets/js/edit-show.js.map
  themes/dark/templates/editShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/anidb-release-group-ui.mako
  themes/dark/templates/vue-components/file-browser.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/dark/templates/vue-components/select-list-ui.mako
  themes/light/assets/img/curved-arrow-left.png
  themes/light/assets/img/curved-arrow-right.png
  themes/light/assets/js/browser.js
  themes/light/assets/js/browser.js.map
  themes/light/assets/js/edit-show.js
  themes/light/assets/js/edit-show.js.map
  themes/light/templates/editShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/anidb-release-group-ui.mako
  themes/light/templates/vue-components/file-browser.mako
  themes/light/templates/vue-components/quality-chooser.mako
  themes/light/templates/vue-components/select-list-ui.mako
Labels: Bug, Concluded

#4111 Fix exception_handler exception
  medusa/exception_handler.py
Labels: Bug, Concluded

#4109 Newznab|Torznab: Replace newstr with six.text_type
  medusa/providers/nzb/newznab.py
  medusa/providers/torrent/torznab/torznab.py
Labels: Bug, Concluded

#4122 Fix torznab for providers without seeders/leechers
  medusa/providers/torrent/json/torrentday.py
  medusa/providers/torrent/torznab/torznab.py
Labels: Bug, Concluded

#4118 Don't stop newznab search if params are missing. Fixes #4115
  medusa/providers/nzb/newznab.py
Labels: Bug, Concluded

#4113 qBittorent: Don't error when torrent queueing is disabled
  medusa/clients/torrent/qbittorrent_client.py
Labels: Concluded, Enhancement

#4130 fix touchscreen hack causing menu double tap to apply base twice
  themes-default/slim/static/js/common/init.js
  themes/dark/assets/js/common/init.js
  themes/light/assets/js/common/init.js
Labels: Bug, Concluded, Needs review

#4131 disable codecov comments
  .codecov.yml
Labels: Concluded, Enhancement

#4126 convert addShows and addrecommended to vue
  themes-default/slim/views/addRecommended.mako
  themes-default/slim/views/addShows.mako
  themes/dark/templates/addRecommended.mako
  themes/dark/templates/addShows.mako
  themes/light/templates/addRecommended.mako
  themes/light/templates/addShows.mako
Labels: Concluded, Enhancement, Needs review

#4137 Fix reference to import of anidb_setup_connection().
  medusa/post_processor.py
Labels: Bug, Concluded

#4138 Fix manual search UI bugs
  themes-default/slim/static/js/ajax-episode-search.js
  themes-default/slim/static/js/ajax-episode-subtitles.js
  themes-default/slim/static/js/home/snatch-selection.js
  themes/dark/assets/js/ajax-episode-search.js
  themes/dark/assets/js/ajax-episode-search.js.map
  themes/dark/assets/js/ajax-episode-subtitles.js
  themes/dark/assets/js/ajax-episode-subtitles.js.map
  themes/dark/assets/js/home/snatch-selection.js
  themes/dark/assets/js/home/snatch-selection.js.map
  themes/light/assets/js/ajax-episode-search.js
  themes/light/assets/js/ajax-episode-search.js.map
  themes/light/assets/js/ajax-episode-subtitles.js
  themes/light/assets/js/ajax-episode-subtitles.js.map
  themes/light/assets/js/home/snatch-selection.js
  themes/light/assets/js/home/snatch-selection.js.map
Labels: Bug, Concluded, Needs review

#4100 app-link: Fix undefined url with empty anonRedirect
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/light/templates/vue-components/app-link.mako
Labels: Bug, Concluded

#4139 Travis: Skip Python tests if the changes are only to specific files
  .github/check_changes.py
  .github/check_version.py
  .travis.yml
Labels: Concluded, Enhancement
