Repository pymedusa/Medusa, pull requests merged in 2018-11, with the labels that each got.

#5522 Send episode object to download and subtitle notifications
  medusa/notifiers/__init__.py
  medusa/notifiers/boxcar2.py
  medusa/notifiers/emailnotify.py
  medusa/notifiers/freemobile.py
  medusa/notifiers/growl.py
  medusa/notifiers/kodi.py
  medusa/notifiers/libnotify.py
  medusa/notifiers/plex.py
  medusa/notifiers/prowl.py
  medusa/notifiers/pushalot.py
  medusa/notifiers/pushbullet.py
  medusa/notifiers/pushover.py
  medusa/notifiers/slack.py
  medusa/notifiers/synology_notifier.py
  medusa/notifiers/telegram.py
  medusa/notifiers/tweet.py
  medusa/post_processor.py
  medusa/tv/episode.py
Labels: Backend, Enhancement

#5581 Created class for medusa's global app config
  medusa/__init__.py
  medusa/app.py
  themes-default/slim/views/partials/footer.mako
  themes/dark/templates/partials/footer.mako
  themes/light/templates/partials/footer.mako
Labels: Concluded, Enhancement

#5585 Replace six.viewitems with items() in app.py
  medusa/app.py
Labels: Concluded

#5241 add join notifier support
  dredd/api-description.yml
  dredd/dredd_hook.py
  medusa/__main__.py
  medusa/app.py
  medusa/notifiers/__init__.py
  medusa/notifiers/join.py
  medusa/server/api/v2/config.py
  medusa/server/web/config/notifications.py
  medusa/server/web/home/handler.py
  themes-default/slim/src/store/modules/notifiers.js
  themes-default/slim/src/store/modules/notifiers/index.js
  themes-default/slim/src/store/modules/notifiers/join.js
  themes-default/slim/static/css/style.css
  themes-default/slim/static/images/32x_sprite_colored_notifiers.png
  themes-default/slim/test/__fixtures__/app-header.json
  themes-default/slim/views/config_notifications.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/img/32x_sprite_colored_notifiers.png
  themes/dark/assets/js/config/notifications.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_notifications.mako
  themes/light/assets/css/style.css
  themes/light/assets/img/32x_sprite_colored_notifiers.png
  themes/light/assets/js/config/notifications.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_notifications.mako
  yarn.lock
Labels: Needs review, Needs testing

#5576 Fix save multiple metadata providers
  CHANGELOG.md
  themes-default/slim/src/components/config-post-processing.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Confirmed

#5604 Update notifiers PSD and minify image
  themes-default/slim/resources/32x_sprite_colored_notifiers.psd
  themes-default/slim/static/images/32x_sprite_colored_notifiers.png
  themes/dark/assets/img/32x_sprite_colored_notifiers.png
  themes/light/assets/img/32x_sprite_colored_notifiers.png
Labels: Concluded

#5621 Revert "Update JS dependency vue-async-computed to v3.5.0"
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Bug, Concluded

#5518 Utilize the SnatchQueueItem
  ext/readme.md
  ext2/__init__.py
  ext2/enum/LICENSE
  ext2/enum/README
  ext2/enum/__init__.py
  medusa/classes.py
  medusa/search/__init__.py
  medusa/search/queue.py
  medusa/server/web/home/handler.py
Labels: Concluded, Enhancement

#5623 Fix show-selector for libraries with more than 1k shows
  CHANGELOG.md
  medusa/server/api/v2/base.py
  themes-default/slim/src/store/modules/shows.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded

#5622 Update JS dependency vue-async-computed to v3.5.0
  themes-default/slim/package.json
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/vendors.js
  themes/light/templates/layouts/main.mako
Labels: Concluded

#5636 Fix the evaluation for the snatch_queue item.
  medusa/search/queue.py
Labels: Bug, Concluded

#5584 Refactor notify_snatch to use title, message instead of episode name
  medusa/notifiers/__init__.py
  medusa/notifiers/boxcar2.py
  medusa/notifiers/emailnotify.py
  medusa/notifiers/freemobile.py
  medusa/notifiers/growl.py
  medusa/notifiers/join.py
  medusa/notifiers/kodi.py
  medusa/notifiers/libnotify.py
  medusa/notifiers/nmj.py
  medusa/notifiers/nmjv2.py
  medusa/notifiers/plex.py
  medusa/notifiers/prowl.py
  medusa/notifiers/pushalot.py
  medusa/notifiers/pushbullet.py
  medusa/notifiers/pushover.py
  medusa/notifiers/pytivo.py
  medusa/notifiers/slack.py
  medusa/notifiers/synoindex.py
  medusa/notifiers/synology_notifier.py
  medusa/notifiers/telegram.py
  medusa/notifiers/trakt.py
  medusa/notifiers/tweet.py
  medusa/search/core.py
Labels: Bug, Concluded, Enhancement

#5644 Fix Download Station BraceAdapter exception (2). Fixes #5588, #5632
  medusa/clients/torrent/downloadstation_client.py
Labels: Bug, Concluded

#5624 Number of small fixes for saving config_notifications.mako.
  medusa/server/api/v2/config.py
  themes-default/slim/views/config_notifications.mako
  themes/dark/templates/config_notifications.mako
  themes/light/templates/config_notifications.mako
Labels: Bug, Concluded

#5684 Fix Growl registration error
  CHANGELOG.md
  medusa/notifiers/growl.py
Labels: Bug, Concluded

#5681 Enable non-anime search on Anidex
  medusa/providers/torrent/html/anidex.py
Labels: Concluded, Enhancement, Provider

#5692 Minor UI changes
  medusa/__main__.py
  medusa/server/web/home/handler.py
  setup.cfg
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/helpers/app-link.vue
  themes-default/slim/src/router.js
  themes-default/slim/test/specs/app-header.spec.js
  themes-default/slim/test/specs/snapshots/add-recommended.spec.js.md
  themes-default/slim/test/specs/snapshots/add-recommended.spec.js.snap
  themes-default/slim/test/specs/snapshots/add-shows.spec.js.md
  themes-default/slim/test/specs/snapshots/add-shows.spec.js.snap
  themes-default/slim/test/specs/snapshots/app-header.spec.js.md
  themes-default/slim/test/specs/snapshots/app-header.spec.js.snap
  themes-default/slim/test/specs/snapshots/app-link.spec.js.md
  themes-default/slim/test/specs/snapshots/app-link.spec.js.snap
  themes-default/slim/test/specs/snapshots/config.spec.js.md
  themes-default/slim/test/specs/snapshots/config.spec.js.snap
  themes-default/slim/test/specs/snapshots/select-list.spec.js.md
  themes-default/slim/test/specs/snapshots/select-list.spec.js.snap
  themes-default/slim/views/errorlogs.mako
  themes-default/slim/views/viewlogs.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/errorlogs.mako
  themes/dark/templates/viewlogs.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/errorlogs.mako
  themes/light/templates/viewlogs.mako
Labels: Concluded, Frontend

#5680 Enable non-anime search on Nyaa
  CHANGELOG.md
  medusa/providers/torrent/rss/nyaa.py
Labels: Concluded, Enhancement, Provider

#5685 Added DELETE method for deleting an episode to the apiv2.
  CHANGELOG.md
  dredd/api-description.yml
  medusa/server/api/v2/episodes.py
  medusa/tv/episode.py
  tests/test_tv_identifiers.py
Labels: Backend, Concluded

#5136 CI: Test on Python 3.6
  .codecov.yml
  .travis.yml
  dredd/dredd_hook.py
  tox.ini
Labels: Backend, Concluded, Needs review

#5709 Fix add-show-options toggle buttons.
  themes-default/slim/src/components/add-show-options.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#5701 Do not allow to set anime option(s) when adding shows through tmdb or…
  CHANGELOG.md
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/light/templates/addShows_newShow.mako
Labels: Concluded, Enhancement

#5700 Feature/enable check runs in docker
  dredd/api-description.yml
  medusa/server/api/v2/config.py
  medusa/version_checker.py
  tests/apiv2/test_config.py
  themes-default/slim/src/components/config.vue
  themes-default/slim/static/css/style.css
  themes-default/slim/static/images/16x_sprite_colored_help-info.png
  themes-default/slim/test/specs/snapshots/config.spec.js.md
  themes-default/slim/test/specs/snapshots/config.spec.js.snap
  themes-default/slim/test/specs/snapshots/select-list.spec.js.md
  themes-default/slim/test/specs/snapshots/select-list.spec.js.snap
  themes/dark/assets/css/style.css
  themes/dark/assets/img/16x_sprite_colored_help-info.png
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/css/style.css
  themes/light/assets/img/16x_sprite_colored_help-info.png
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#5721 Make FixParentFolderReplacingTitle more strict. Fixes #5713
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#5553 Feature/vueify config search
  CHANGELOG.md
  dredd/api-description.yml
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/src/components/helpers/config-textbox-number.vue
  themes-default/slim/src/components/helpers/config-textbox.vue
  themes-default/slim/src/components/helpers/select-list.vue
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/modules/clients.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/src/store/modules/index.js
  themes-default/slim/src/store/modules/search.js
  themes-default/slim/test/specs/config-textbox-number.spec.js
  themes-default/slim/test/specs/snapshots/config-textbox-number.spec.js.md
  themes-default/slim/test/specs/snapshots/config-textbox-number.spec.js.snap
  themes-default/slim/views/config_search.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_search.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_search.mako
Labels: Backend, Concluded, Frontend

#5725 Sync master to develop
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#5736 fix clients.torrents.path path type
  CHANGELOG.md
  medusa/server/api/v2/config.py
Labels: Bug, Concluded

#5748 Rename DS client name in clients.torrent init
  CHANGELOG.md
  medusa/clients/torrent/__init__.py
Labels: Bug, Concluded

#5740 Perfect match for subtitles is too strict
  CHANGELOG.md
  medusa/subtitles.py
  tests/test_subtitles.py
Labels: Discussion, Enhancement, In progress

#5761 Fix synology/Downloadstation not selected in config/search after rest…
  CHANGELOG.md
  medusa/__main__.py
  medusa/server/web/manage/handler.py
Labels: Bug, Concluded

#5763 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#5790 Add logging and return statement, to detect None indexer.
  medusa/scene_exceptions.py
Labels: Bug, Concluded

#5801 Attempt to fix double absolute_numbers getting in
  CHANGELOG.md
  medusa/scene_numbering.py
Labels: Bug, Concluded
