Repository pymedusa/Medusa, pull requests merged in 2018-07, with the labels that each got.

#4510 set todo config
  .github/config.yml
Labels: Concluded, Enhancement

#4515 Update todo config to exclude vendored packages
  .github/config.yml
Labels: Concluded, Enhancement

#4514 Fix better allowed quality versions not being downloaded. Fixes #4511
  medusa/common.py
  tests/test_should_replace.py
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Bug, Concluded, Needs review

#4450 Patch email notifier episode parsing. Fixes #4159
  medusa/notifiers/emailnotify.py
  pytest.ini
  tests/notifiers/__init__.py
  tests/notifiers/test_emailnotify.py
Labels: Bug, Concluded

#4522 Feature/misc vue changes
  themes-default/slim/.eslintrc
  themes-default/slim/package.json
  themes-default/slim/static/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js
  themes/dark/assets/js/vue-submit-form.js.map
  themes/dark/package.json
  themes/light/assets/js/vue-submit-form.js
  themes/light/assets/js/vue-submit-form.js.map
  themes/light/package.json
Labels: Concluded, Enhancement, Needs review

#4523 add vue linting to gulp
  themes-default/slim/gulpfile.js
Labels: Concluded, Enhancement

#4524 Fix #4518
  medusa/tv/series.py
Labels: Bug, Concluded

#4471 Fix "already added" link using incorrect indexer and show id
  medusa/server/api/v2/internal.py
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/light/templates/addShows_newShow.mako
Labels: Bug, Concluded, Needs review

#4509 Fix proper search downloading multiple propers. Fixes #4495
  medusa/search/proper.py
Labels: Bug, Concluded, Needs review, Needs testing

#4529 Remove `app.ANON_REDIRECT` references from `mako`
  medusa/helpers/__init__.py
  themes-default/slim/views/partials/header.mako
  themes/dark/templates/partials/header.mako
  themes/light/templates/partials/header.mako
Labels: Concluded, Enhancement

#4531 Rename errno.EXIST to errno.EEXIST. Fixes #4084
  medusa/helpers/__init__.py
Labels: Bug, Concluded

#4534 Bump version to v0.2.6
  medusa/common.py
Labels: Concluded

#4550 Disable Pyup pull requests
  .pyup.yml
Labels: Concluded

#4549 Initial changelog
  CHANGELOG.md
Labels: Concluded

#4555 fix store typo
  themes-default/slim/static/js/templates/config.vue
  themes/dark/assets/js/templates/config.vue
  themes/light/assets/js/templates/config.vue
Labels: Bug, Concluded

#4492 Decode log lines from UTF-8 on Windows
  medusa/logger/__init__.py
Labels: Bug, Concluded, Confirmed

#4557 Remove vcrpy & wrapt from vendored packages
  ext/readme.md
  ext/vcr/__init__.py
  ext/vcr/_handle_coroutine.py
  ext/vcr/cassette.py
  ext/vcr/compat.py
  ext/vcr/config.py
  ext/vcr/errors.py
  ext/vcr/filters.py
  ext/vcr/matchers.py
  ext/vcr/migration.py
  ext/vcr/patch.py
  ext/vcr/persist.py
  ext/vcr/persisters/__init__.py
  ext/vcr/persisters/filesystem.py
  ext/vcr/request.py
  ext/vcr/serialize.py
  ext/vcr/serializers/__init__.py
  ext/vcr/serializers/compat.py
  ext/vcr/serializers/jsonserializer.py
  ext/vcr/serializers/yamlserializer.py
  ext/vcr/stubs/__init__.py
  ext/vcr/stubs/aiohttp_stubs.py
  ext/vcr/stubs/aiohttp_stubs/__init__.py
  ext/vcr/stubs/boto3_stubs.py
  ext/vcr/stubs/boto_stubs.py
  ext/vcr/stubs/compat.py
  ext/vcr/stubs/httplib2_stubs.py
  ext/vcr/stubs/requests_stubs.py
  ext/vcr/stubs/tornado_stubs.py
  ext/vcr/stubs/urllib3_stubs.py
  ext/vcr/util.py
  ext/wrapt/__init__.py
  ext/wrapt/arguments.py
  ext/wrapt/decorators.py
  ext/wrapt/importer.py
  ext/wrapt/wrappers.py
  setup.py
Labels: Concluded

#4559 Remove click from vendored packages
  ext/click/__init__.py
  ext/click/_bashcomplete.py
  ext/click/_compat.py
  ext/click/_termui_impl.py
  ext/click/_textwrap.py
  ext/click/_unicodefun.py
  ext/click/_winconsole.py
  ext/click/core.py
  ext/click/decorators.py
  ext/click/exceptions.py
  ext/click/formatting.py
  ext/click/globals.py
  ext/click/parser.py
  ext/click/termui.py
  ext/click/testing.py
  ext/click/types.py
  ext/click/utils.py
  ext/readme.md
Labels: Concluded

#4526 cleanup app-link for tests
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/light/templates/vue-components/app-link.mako
Labels: Concluded, Enhancement, Needs review

#4564 add missing addShows template
  CHANGELOG.md
  medusa/server/web/home/add_recommended.py
  medusa/server/web/home/add_shows.py
  themes-default/slim/static/js/router.js
  themes-default/slim/static/js/templates/add-recommended.vue
  themes-default/slim/static/js/templates/add-shows.vue
  themes-default/slim/views/addRecommended.mako
  themes-default/slim/views/addShows.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/router.js
  themes/dark/assets/js/router.js.map
  themes/dark/assets/js/templates/add-recommended.vue
  themes/dark/assets/js/templates/add-shows.vue
  themes/dark/templates/addRecommended.mako
  themes/dark/templates/addShows.mako
  themes/light/assets/js/router.js
  themes/light/assets/js/router.js.map
  themes/light/assets/js/templates/add-recommended.vue
  themes/light/assets/js/templates/add-shows.vue
  themes/light/templates/addRecommended.mako
  themes/light/templates/addShows.mako
Labels: Bug, Concluded

#4570 Use develop as base branch for Renovate
  renovate.json
Labels: Concluded

#4580 add test for app-link to
  themes-default/slim/package.json
  themes-default/slim/static/js/templates/app-link.vue
  themes-default/slim/test/specs/app-link.spec.js
  themes-default/slim/test/specs/snapshots/app-link.spec.js.md
  themes-default/slim/test/specs/snapshots/app-link.spec.js.snap
  themes-default/slim/yarn.lock
  themes/dark/assets/js/templates/app-link.vue
  themes/dark/package.json
  themes/light/assets/js/templates/app-link.vue
  themes/light/package.json
Labels: Concluded, Enhancement

#4565 Remove `/ui/` route, add fallback 404/500
  CHANGELOG.md
  medusa/server/web/__init__.py
  medusa/server/web/core/__init__.py
  medusa/server/web/core/base.py
Labels: Concluded, Enhancement

#4589 Upgrade eslint to 5.0.1
  themes-default/slim/package.json
  themes-default/slim/test/specs/app-link.spec.js
  themes-default/slim/yarn.lock
  themes/dark/package.json
  themes/light/package.json
Labels: Concluded, Enhancement

#4586 Split travis builds into jobs
  .travis.yml
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
  themes/dark/package.json
  themes/light/package.json
Labels: Concluded, Enhancement

#4592 Remove vcrpy
  requirements.txt
Labels: Concluded

#4597 Fix event handlers by restoring app-link to a mako file
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/app-link.mako
Labels: Bug, Concluded

#4623 Fix dependency listing
  ext/readme.md
Labels: Concluded

#4622 Fix Emby test notification
  CHANGELOG.md
  medusa/notifiers/emby.py
Labels: Bug, Concluded

#4601 Fix gulp sync for now
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
Labels: Bug, Concluded

#4488 Add PATCH capabilities for APIv2 episodes
  dredd/api-description.yml
  medusa/server/api/v2/auth.py
  medusa/server/api/v2/base.py
  medusa/server/api/v2/config.py
  medusa/server/api/v2/episode.py
  medusa/server/api/v2/episodes.py
  medusa/server/api/v2/internal.py
  medusa/server/api/v2/log.py
  medusa/server/api/v2/series.py
  medusa/server/core.py
Labels: Concluded, Enhancement

#4627 Update docstrings for addShows/addRecommended
  medusa/server/web/home/add_recommended.py
  medusa/server/web/home/add_shows.py
Labels: Concluded

#4631 Update renovate/todo config
  .github/config.yml
  renovate.json
Labels: Concluded

#4641 Simplify built themes' package.json
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
  themes/dark/package.json
  themes/light/package.json
Labels: Concluded, Enhancement

#4629 Display a soft "Loading..." mask until page is ready
  CHANGELOG.md
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/snatchSelection.mako
  themes/dark/templates/displayShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/templates/displayShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/snatchSelection.mako
Labels: Bug, Concluded, Enhancement

#4643 Update changelog information with NorBits fix
  CHANGELOG.md
Labels: Concluded

#4636 Move $.rootDirCheck to correct file
  themes-default/slim/static/js/add-shows/init.js
  themes-default/slim/static/js/common/init.js
  themes/dark/assets/js/add-shows/init.js
  themes/dark/assets/js/add-shows/init.js.map
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/common/init.js.map
  themes/light/assets/js/add-shows/init.js
  themes/light/assets/js/add-shows/init.js.map
  themes/light/assets/js/common/init.js
  themes/light/assets/js/common/init.js.map
Labels: Concluded

#4628 Don't create a gist if context lines equal error
  medusa/issue_submitter.py
  tests/test_issue_submitter.py
Labels: Concluded, Enhancement

#4595 Remove `gulp-xo`, use native `xo`
  gulpfile.js
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded, Enhancement

#4647 Expand episode status management functionality. Fixes #4562
  themes-default/slim/views/manage_episodeStatuses.mako
  themes-default/slim/views/manage_massEdit.mako
  themes/dark/templates/manage_episodeStatuses.mako
  themes/dark/templates/manage_massEdit.mako
  themes/light/templates/manage_episodeStatuses.mako
  themes/light/templates/manage_massEdit.mako
Labels: Concluded, Enhancement

#4463 Fix reference linking
  medusa/helpers/__init__.py
  medusa/post_processor.py
  medusa/process_tv.py
  medusa/server/api/v1/core.py
Labels: Bug, Concluded, Needs testing

#4630 Remove root gulp, use simple yargs script
  package.json
  themes-default/helper.js
  yarn.lock
Labels: Concluded, Enhancement

#4648 Update changelog
  CHANGELOG.md
Labels: Concluded

#4625 Fix show-selector not honoring option to split shows & anime
  CHANGELOG.md
  medusa/server/web/home/handler.py
  themes-default/slim/views/vue-components/show-selector.mako
  themes/dark/templates/vue-components/show-selector.mako
  themes/light/templates/vue-components/show-selector.mako
Labels: Bug, Concluded

#4602 Fix schedule page navigating to /not-found
  themes-default/slim/static/js/router.js
  themes-default/slim/views/schedule.mako
  themes/dark/assets/js/router.js
  themes/dark/assets/js/router.js.map
  themes/dark/templates/schedule.mako
  themes/light/assets/js/router.js
  themes/light/assets/js/router.js.map
  themes/light/templates/schedule.mako
Labels: Bug, Concluded

#4639 Fix unhandled request error on existingShow
  CHANGELOG.md
  themes-default/slim/views/addShows_addExistingShow.mako
  themes/dark/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_addExistingShow.mako
Labels: Bug, Concluded, Needs review

#4657 Fix Telegram/Growl notifiers message encodings
  CHANGELOG.md
  medusa/notifiers/growl.py
  medusa/notifiers/telegram.py
Labels: Bug, Concluded

#4634 vueify login page
  CHANGELOG.md
  medusa/server/web/core/authentication.py
  themes-default/slim/package.json
  themes-default/slim/static/js/api.js
  themes-default/slim/static/js/core.js
  themes-default/slim/static/js/router.js
  themes-default/slim/static/js/store.js
  themes-default/slim/static/js/templates/login.vue
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/login.mako
  themes-default/slim/views/partials/header.mako
  themes-default/slim/views/vue-components/asset.mako
  themes/dark/assets/js/api.js
  themes/dark/assets/js/api.js.map
  themes/dark/assets/js/core.js
  themes/dark/assets/js/core.js.map
  themes/dark/assets/js/router.js
  themes/dark/assets/js/router.js.map
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/assets/js/templates/login.vue
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/login.mako
  themes/dark/templates/partials/header.mako
  themes/dark/templates/vue-components/asset.mako
  themes/light/assets/js/api.js
  themes/light/assets/js/api.js.map
  themes/light/assets/js/core.js
  themes/light/assets/js/core.js.map
  themes/light/assets/js/router.js
  themes/light/assets/js/router.js.map
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/assets/js/templates/login.vue
  themes/light/templates/layouts/main.mako
  themes/light/templates/login.mako
  themes/light/templates/partials/header.mako
  themes/light/templates/vue-components/asset.mako
Labels: Bug, Concluded

#4666 Add more config values and update store
  dredd/api-description.yml
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/static/js/store.js
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4467 Vueify/manage
  themes-default/slim/static/js/manage/backlog-overview.js
  themes-default/slim/static/js/manage/episode-statuses.js
  themes-default/slim/static/js/manage/manage-searches.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes-default/slim/views/manage_episodeStatuses.mako
  themes-default/slim/views/manage_manageSearches.mako
  themes/dark/assets/js/manage/backlog-overview.js
  themes/dark/assets/js/manage/backlog-overview.js.map
  themes/dark/assets/js/manage/episode-statuses.js
  themes/dark/assets/js/manage/episode-statuses.js.map
  themes/dark/assets/js/manage/manage-searches.js
  themes/dark/assets/js/manage/manage-searches.js.map
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/dark/templates/manage_episodeStatuses.mako
  themes/dark/templates/manage_manageSearches.mako
  themes/light/assets/js/manage/backlog-overview.js
  themes/light/assets/js/manage/backlog-overview.js.map
  themes/light/assets/js/manage/episode-statuses.js
  themes/light/assets/js/manage/episode-statuses.js.map
  themes/light/assets/js/manage/manage-searches.js
  themes/light/assets/js/manage/manage-searches.js.map
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_backlogOverview.mako
  themes/light/templates/manage_episodeStatuses.mako
  themes/light/templates/manage_manageSearches.mako
Labels: Concluded, Enhancement, Needs review, Needs testing

#4659 Fix plot info & APIv2 exception
  medusa/server/api/v2/base.py
  themes-default/slim/static/css/style.css
  themes-default/slim/views/vue-components/plot-info.mako
  themes/dark/assets/css/style.css
  themes/dark/templates/vue-components/plot-info.mako
  themes/light/assets/css/style.css
  themes/light/templates/vue-components/plot-info.mako
Labels: Bug, Concluded

#4654 Enable codecov flags
  .codecov.yml
  themes-default/slim/package.json
  tox.ini
Labels: Concluded

#4656 Fix UI bugs
  CHANGELOG.md
  medusa/server/web/core/base.py
  themes-default/slim/static/js/templates/app-link.vue
  themes-default/slim/test/specs/app-link.spec.js
  themes-default/slim/test/specs/snapshots/app-link.spec.js.md
  themes-default/slim/test/specs/snapshots/app-link.spec.js.snap
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/assets/js/templates/app-link.vue
  themes/dark/templates/vue-components/app-link.mako
  themes/light/assets/js/templates/app-link.vue
  themes/light/templates/vue-components/app-link.mako
Labels: Bug, Concluded, Enhancement, Needs review

#4662 Update CHANGELOG.md
  CHANGELOG.md
Labels: Concluded

#4519 Vueify header
  CHANGELOG.md
  medusa/server/web/config/anime.py
  medusa/server/web/config/backup_restore.py
  medusa/server/web/config/general.py
  medusa/server/web/config/handler.py
  medusa/server/web/config/notifications.py
  medusa/server/web/config/post_processing.py
  medusa/server/web/config/providers.py
  medusa/server/web/config/search.py
  medusa/server/web/config/subtitles.py
  medusa/server/web/core/authentication.py
  medusa/server/web/core/base.py
  medusa/server/web/core/error_logs.py
  medusa/server/web/core/history.py
  medusa/server/web/core/schedule.py
  medusa/server/web/home/add_recommended.py
  medusa/server/web/home/add_shows.py
  medusa/server/web/home/change_log.py
  medusa/server/web/home/handler.py
  medusa/server/web/home/irc.py
  medusa/server/web/home/news.py
  medusa/server/web/home/post_process.py
  medusa/server/web/manage/handler.py
  medusa/server/web/manage/searches.py
  themes-default/slim/static/js/common/init.js
  themes-default/slim/static/js/templates/app-header.vue
  themes-default/slim/test/__fixtures__/app-header.json
  themes-default/slim/test/specs/app-header.spec.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/partials/header.mako
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/common/init.js.map
  themes/dark/assets/js/templates/app-header.vue
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/partials/header.mako
  themes/light/assets/js/common/init.js
  themes/light/assets/js/common/init.js.map
  themes/light/assets/js/templates/app-header.vue
  themes/light/templates/layouts/main.mako
  themes/light/templates/partials/header.mako
Labels: Concluded, Enhancement

#4668 switch puex with vuex
  themes-default/slim/static/js/lib/puex.js
  themes-default/slim/static/js/lib/vuex.js
  themes-default/slim/static/js/store.js
  themes-default/slim/test/specs/app-header.spec.js
  themes-default/slim/test/specs/app-link.spec.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes-default/slim/views/schedule.mako
  themes-default/slim/views/vue-components/show-selector.mako
  themes/dark/assets/js/lib/puex.js
  themes/dark/assets/js/lib/vuex.js
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/dark/templates/schedule.mako
  themes/dark/templates/vue-components/show-selector.mako
  themes/light/assets/js/lib/puex.js
  themes/light/assets/js/lib/vuex.js
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_backlogOverview.mako
  themes/light/templates/schedule.mako
  themes/light/templates/vue-components/show-selector.mako
Labels: Bug, Concluded

#4667 Fix app-header simple render test
  themes-default/slim/static/js/templates/app-link.vue
  themes-default/slim/test/helpers/setup.js
  themes-default/slim/test/specs/app-header.spec.js
  themes-default/slim/test/specs/app-link.spec.js
  themes-default/slim/test/specs/snapshots/app-header.spec.js.md
  themes-default/slim/test/specs/snapshots/app-header.spec.js.snap
  themes-default/slim/views/vue-components/app-link.mako
  themes/dark/assets/js/templates/app-link.vue
  themes/dark/templates/vue-components/app-link.mako
  themes/light/assets/js/templates/app-link.vue
  themes/light/templates/vue-components/app-link.mako
Labels: Bug, Concluded

#4669 Rename Season search mode to Backlog search mode
  themes-default/slim/views/config_providers.mako
  themes/dark/templates/config_providers.mako
  themes/light/templates/config_providers.mako
Labels: Concluded, Enhancement

#4671 Fix KeyError on show removal. Fixes #4670
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#4672 Move scroll-buttons into a Vue component
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/common/init.js
  themes-default/slim/static/js/templates/scroll-buttons.vue
  themes-default/slim/test/specs/scroll-buttons.spec.js
  themes-default/slim/test/specs/snapshots/scroll-buttons.spec.js.md
  themes-default/slim/test/specs/snapshots/scroll-buttons.spec.js.snap
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/partials/footer.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/common/init.js.map
  themes/dark/assets/js/templates/scroll-buttons.vue
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/partials/footer.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/common/init.js
  themes/light/assets/js/common/init.js.map
  themes/light/assets/js/templates/scroll-buttons.vue
  themes/light/templates/layouts/main.mako
  themes/light/templates/partials/footer.mako
Labels: Concluded, Enhancement

#4658 Add ability to manually change episode quality. Fixes #4474
  CHANGELOG.md
  medusa/server/web/home/handler.py
  medusa/server/web/manage/handler.py
  themes-default/slim/.eslintrc
  themes-default/slim/static/js/home/display-show.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/views/testRename.mako
  themes/dark/assets/js/home/display-show.js
  themes/dark/assets/js/home/display-show.js.map
  themes/dark/templates/displayShow.mako
  themes/dark/templates/partials/showheader.mako
  themes/dark/templates/testRename.mako
  themes/light/assets/js/home/display-show.js
  themes/light/assets/js/home/display-show.js.map
  themes/light/templates/displayShow.mako
  themes/light/templates/partials/showheader.mako
  themes/light/templates/testRename.mako
Labels: Concluded, Enhancement, Needs review

#4680 Fixes schedule banner and poster links
  themes-default/slim/views/partials/schedule/banner.mako
  themes-default/slim/views/partials/schedule/poster.mako
  themes/dark/templates/partials/schedule/banner.mako
  themes/dark/templates/partials/schedule/poster.mako
  themes/light/templates/partials/schedule/banner.mako
  themes/light/templates/partials/schedule/poster.mako
Labels: Bug, Concluded

#4679 Fix bj-share animes
  medusa/providers/torrent/html/bjshare.py
Labels: Bug, Needs review, Needs testing

#4703 Improve Travis
  .github/build-themes-check.sh
  .travis.yml
Labels: Concluded, Enhancement

#4702 Sync themes
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/editShow.mako
  themes/dark/assets/img/network/viaplay.png
  themes/dark/templates/displayShow.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/vue-components/anidb-release-group-ui.mako
  themes/dark/templates/vue-components/app-link.mako
  themes/dark/templates/vue-components/asset.mako
  themes/dark/templates/vue-components/backstretch.mako
  themes/dark/templates/vue-components/file-browser.mako
  themes/dark/templates/vue-components/language-select.mako
  themes/dark/templates/vue-components/name-pattern.mako
  themes/dark/templates/vue-components/plot-info.mako
  themes/dark/templates/vue-components/root-dirs.mako
  themes/dark/templates/vue-components/select-list-ui.mako
  themes/dark/templates/vue-components/show-selector.mako
  themes/light/assets/img/network/viaplay.png
  themes/light/assets/img/providers/french_adn.png
  themes/light/assets/img/providers/french_adn_com.png
  themes/light/templates/displayShow.mako
  themes/light/templates/editShow.mako
  themes/light/templates/vue-components/anidb-release-group-ui.mako
  themes/light/templates/vue-components/app-link.mako
  themes/light/templates/vue-components/asset.mako
  themes/light/templates/vue-components/backstretch.mako
  themes/light/templates/vue-components/file-browser.mako
  themes/light/templates/vue-components/language-select.mako
  themes/light/templates/vue-components/name-pattern.mako
  themes/light/templates/vue-components/plot-info.mako
  themes/light/templates/vue-components/root-dirs.mako
  themes/light/templates/vue-components/select-list-ui.mako
  themes/light/templates/vue-components/show-selector.mako
Labels: Concluded

#4707 Fix tabs (addShows/*)
  themes-default/slim/static/js/templates/root-dirs.vue
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/addShows_trendingShows.mako
  themes/dark/assets/js/templates/root-dirs.vue
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/addShows_trendingShows.mako
  themes/light/assets/js/templates/root-dirs.vue
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/addShows_trendingShows.mako
Labels: Bug, Concluded

#4704 Fix Github error 500 exception
  medusa/version_checker.py
Labels: Bug, Concluded

#4713 More fixes for addShows
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
Labels: Bug, Concluded

#4706 Fix Vue linting errors
  themes-default/slim/package.json
  themes-default/slim/static/js/templates/anidb-release-group-ui.vue
  themes-default/slim/static/js/templates/asset.vue
  themes-default/slim/static/js/templates/file-browser.vue
  themes-default/slim/static/js/templates/root-dirs.vue
  themes-default/slim/static/js/templates/select-list.vue
  themes-default/slim/static/js/templates/show-selector.vue
  themes/dark/assets/js/add-shows/new-show.js.map
  themes/dark/assets/js/templates/anidb-release-group-ui.vue
  themes/dark/assets/js/templates/asset.vue
  themes/dark/assets/js/templates/file-browser.vue
  themes/dark/assets/js/templates/root-dirs.vue
  themes/dark/assets/js/templates/select-list.vue
  themes/dark/assets/js/templates/show-selector.vue
  themes/light/assets/js/add-shows/new-show.js.map
  themes/light/assets/js/templates/anidb-release-group-ui.vue
  themes/light/assets/js/templates/asset.vue
  themes/light/assets/js/templates/file-browser.vue
  themes/light/assets/js/templates/root-dirs.vue
  themes/light/assets/js/templates/select-list.vue
  themes/light/assets/js/templates/show-selector.vue
Labels: Concluded

#4714 Add .eggs to Travis cache
  .travis.yml
Labels: Concluded, Enhancement

#4716 Enable CSS linting for Vue SFC
  package.json
  themes-default/slim/static/js/templates/add-recommended.vue
  themes-default/slim/static/js/templates/add-shows.vue
  themes-default/slim/static/js/templates/anidb-release-group-ui.vue
  themes-default/slim/static/js/templates/asset.vue
  themes-default/slim/static/js/templates/backstretch.vue
  themes-default/slim/static/js/templates/config.vue
  themes-default/slim/static/js/templates/file-browser.vue
  themes-default/slim/static/js/templates/http/404.vue
  themes-default/slim/static/js/templates/language-select.vue
  themes-default/slim/static/js/templates/login.vue
  themes-default/slim/static/js/templates/name-pattern.vue
  themes-default/slim/static/js/templates/select-list.vue
  themes-default/slim/views/errorlogs.mako
  themes-default/slim/views/viewlogs.mako
  themes/dark/assets/js/templates/add-recommended.vue
  themes/dark/assets/js/templates/add-shows.vue
  themes/dark/assets/js/templates/anidb-release-group-ui.vue
  themes/dark/assets/js/templates/asset.vue
  themes/dark/assets/js/templates/backstretch.vue
  themes/dark/assets/js/templates/config.vue
  themes/dark/assets/js/templates/file-browser.vue
  themes/dark/assets/js/templates/http/404.vue
  themes/dark/assets/js/templates/language-select.vue
  themes/dark/assets/js/templates/login.vue
  themes/dark/assets/js/templates/name-pattern.vue
  themes/dark/assets/js/templates/select-list.vue
  themes/dark/templates/errorlogs.mako
  themes/dark/templates/viewlogs.mako
  themes/light/assets/js/templates/add-recommended.vue
  themes/light/assets/js/templates/add-shows.vue
  themes/light/assets/js/templates/anidb-release-group-ui.vue
  themes/light/assets/js/templates/asset.vue
  themes/light/assets/js/templates/backstretch.vue
  themes/light/assets/js/templates/config.vue
  themes/light/assets/js/templates/file-browser.vue
  themes/light/assets/js/templates/http/404.vue
  themes/light/assets/js/templates/language-select.vue
  themes/light/assets/js/templates/login.vue
  themes/light/assets/js/templates/name-pattern.vue
  themes/light/assets/js/templates/select-list.vue
  themes/light/templates/errorlogs.mako
  themes/light/templates/viewlogs.mako
  yarn.lock
Labels: Concluded, Enhancement

#4725 Update YggTorrent URL. Fixes #4723
  medusa/providers/torrent/html/yggtorrent.py
Labels: Concluded

#4727 Fix Abnormal provider login check. Fixes #4724
  CHANGELOG.md
  medusa/providers/torrent/html/abnormal.py
Labels: Concluded

#4719 Fixes for addShows
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_newShow.mako
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_newShow.mako
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_newShow.mako
Labels: Bug, Concluded

#4748 Revert "Add .eggs to Travis cache (#4714)"
  .travis.yml
Labels: Concluded

#4751 Fix forced search and subtitle search
  themes-default/slim/static/js/home/display-show.js
  themes-default/slim/static/js/manage/subtitle-missed-post-process.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_subtitleMissedPP.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/views/schedule.mako
  themes/dark/assets/js/home/display-show.js
  themes/dark/assets/js/home/display-show.js.map
  themes/dark/assets/js/manage/subtitle-missed-post-process.js
  themes/dark/assets/js/manage/subtitle-missed-post-process.js.map
  themes/dark/templates/displayShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_subtitleMissedPP.mako
  themes/dark/templates/partials/showheader.mako
  themes/dark/templates/schedule.mako
  themes/light/assets/js/home/display-show.js
  themes/light/assets/js/home/display-show.js.map
  themes/light/assets/js/manage/subtitle-missed-post-process.js
  themes/light/assets/js/manage/subtitle-missed-post-process.js.map
  themes/light/templates/displayShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_subtitleMissedPP.mako
  themes/light/templates/partials/showheader.mako
  themes/light/templates/schedule.mako
Labels: Bug, Concluded

#4749 Fix manage/manageSearches
  themes-default/slim/views/manage_manageSearches.mako
  themes/dark/templates/manage_manageSearches.mako
  themes/light/templates/manage_manageSearches.mako
Labels: Bug, Concluded, Enhancement

#4758 Fix API error when an episode airdate is `datetime.date.min`
  dredd/api-description.yml
  medusa/server/api/v2/alias.py
  medusa/tv/episode.py
  medusa/tv/series.py
Labels: Bug, Concluded

#4756 Update editShow
  CHANGELOG.md
  themes-default/slim/static/css/vue/editshow.css
  themes-default/slim/views/editShow.mako
  themes/dark/assets/css/vue/editshow.css
  themes/dark/templates/editShow.mako
  themes/light/assets/css/vue/editshow.css
  themes/light/templates/editShow.mako
Labels: Bug, Concluded

#4739 Convert submenu to Vue
  CHANGELOG.md
  medusa/server/web/core/schedule.py
  medusa/server/web/home/handler.py
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/common/init.js
  themes-default/slim/static/js/router.js
  themes-default/slim/static/js/templates/show-selector.vue
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/partials/submenu.mako
  themes-default/slim/views/vue-components/sub-menu.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/common/init.js.map
  themes/dark/assets/js/router.js
  themes/dark/assets/js/router.js.map
  themes/dark/assets/js/templates/show-selector.vue
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/partials/submenu.mako
  themes/dark/templates/vue-components/sub-menu.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/common/init.js
  themes/light/assets/js/common/init.js.map
  themes/light/assets/js/router.js
  themes/light/assets/js/router.js.map
  themes/light/assets/js/templates/show-selector.vue
  themes/light/templates/layouts/main.mako
  themes/light/templates/partials/submenu.mako
  themes/light/templates/vue-components/sub-menu.mako
Labels: Bug, Concluded

#4759 displayShow: Fix asset errors and rating tooltip
  themes-default/slim/static/js/rating-tooltip.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/snatchSelection.mako
  themes/dark/assets/js/rating-tooltip.js
  themes/dark/assets/js/rating-tooltip.js.map
  themes/dark/templates/displayShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/assets/js/rating-tooltip.js
  themes/light/assets/js/rating-tooltip.js.map
  themes/light/templates/displayShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/snatchSelection.mako
Labels: Bug, Concluded

#4761 Fix massEdit page
  themes-default/slim/views/manage_massEdit.mako
  themes/dark/templates/manage_massEdit.mako
  themes/light/templates/manage_massEdit.mako
Labels: Bug, Concluded

#4717 Prepare v0.2.7 release
  CHANGELOG.md
  medusa/app.py
  medusa/common.py
Labels: Concluded, Discussion

#4764 Fix home tabs
  CHANGELOG.md
  themes-default/slim/views/home.mako
  themes/dark/templates/home.mako
  themes/light/templates/home.mako
Labels: Bug, Concluded, Needs testing

#4774 Hotfix: v0.2.8
  CHANGELOG.md
  medusa/common.py
  themes-default/slim/static/js/core.js
  themes-default/slim/views/home.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/testRename.mako
  themes/dark/assets/js/core.js
  themes/dark/assets/js/core.js.map
  themes/dark/templates/home.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/testRename.mako
  themes/light/assets/js/core.js
  themes/light/assets/js/core.js.map
  themes/light/templates/home.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/testRename.mako
Labels: Bug, Concluded

#4778 Merge master into develop
  CHANGELOG.md
  medusa/common.py
  themes-default/slim/static/js/core.js
  themes-default/slim/views/home.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/testRename.mako
  themes/dark/assets/js/core.js
  themes/dark/assets/js/core.js.map
  themes/dark/templates/home.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/testRename.mako
  themes/light/assets/js/core.js
  themes/light/assets/js/core.js.map
  themes/light/templates/home.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/testRename.mako
Labels: Concluded

#4779 Misc updates in preparation for Vueifying config/postProcessing
  dredd/api-description.yml
  medusa/metadata/generic.py
  medusa/metadata/kodi.py
  medusa/metadata/mede8er.py
  medusa/metadata/media_browser.py
  medusa/metadata/ps3.py
  medusa/metadata/tivo.py
  medusa/metadata/wdtv.py
  medusa/server/api/v2/base.py
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/static/js/store.js
  themes-default/slim/static/js/templates/select-list.vue
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/store.js
  themes/dark/assets/js/store.js.map
  themes/dark/assets/js/templates/select-list.vue
  themes/dark/templates/editShow.mako
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/store.js
  themes/light/assets/js/store.js.map
  themes/light/assets/js/templates/select-list.vue
  themes/light/templates/editShow.mako
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#4783 Fix incorrect identifier on `changeEpisodeStatuses`
  medusa/server/web/manage/handler.py
  themes-default/slim/static/js/manage/init.js
  themes/dark/assets/js/manage/init.js
  themes/dark/assets/js/manage/init.js.map
  themes/light/assets/js/manage/init.js
  themes/light/assets/js/manage/init.js.map
Labels: Bug, Concluded
