Repository pymedusa/Medusa, pull requests merged in 2019-03, with the labels that each got.

#6259 Fix log_url() error if request.body is bytes. Fixes #5819
  medusa/session/hooks.py
Labels: Bug, Concluded

#6262 Use errors='replace' if request.body decoding fails
  medusa/session/hooks.py
Labels: Concluded

#6263 Port strtobool() to avoid distutils.util import as it's not always av…
  medusa/helpers/utils.py
Labels: Concluded

#6264 Default systemd to Type=simple
  runscripts/init.systemd
Labels: Concluded

#6265 Fix History APIv1 call reference, rename tvdbid to show_id
  medusa/server/api/v1/core.py
Labels: Bug, Concluded

#6266 Discard releases with multiple versions. Fixes #5429
  medusa/name_parser/parser.py
  medusa/tv/cache.py
  medusa/tv/series.py
  setup.cfg
Labels: Bug, Concluded

#6268 Change consider adding show suggestion to info
  medusa/helpers/__init__.py
Labels: Concluded, Enhancement

#6279 Replace synchronousdeluge with deluge-client. Fixes #6278
  ext/deluge_client/__init__.py
  ext/deluge_client/client.py
  ext/deluge_client/rencode.py
  ext/deluge_client/tests.py
  ext/readme.md
  lib/readme.md
  lib/synchronousdeluge/__init__.py
  lib/synchronousdeluge/client.py
  lib/synchronousdeluge/exceptions.py
  lib/synchronousdeluge/protocol.py
  lib/synchronousdeluge/transfer.py
  medusa/__main__.py
  medusa/clients/torrent/__init__.py
  medusa/clients/torrent/deluge.py
  medusa/clients/torrent/deluged.py
  medusa/clients/torrent/downloadstation.py
  medusa/clients/torrent/mlnet.py
  medusa/clients/torrent/qbittorrent.py
  medusa/clients/torrent/rtorrent.py
  medusa/clients/torrent/torrent_checker.py
  medusa/clients/torrent/transmission.py
  medusa/clients/torrent/utorrent.py
  requirements.txt
  tests/test_clients.py
Labels: Concluded, Enhancement

#6314 Fix config / notifications not loading on firefox 57.
  themes-default/slim/views/config_notifications.mako
  themes/dark/templates/config_notifications.mako
  themes/light/templates/config_notifications.mako
Labels: Bug, Concluded

#6285 Fix username retrieval inside Docker container
  medusa/__main__.py
Labels: Bug, Concluded, Enhancement

#6323 Sync develop with master
  .github/check_version.py
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#6347 Update pyyaml to version 5.1
  .travis.yml
  ext/readme.md
  ext2/yaml/__init__.py
  ext2/yaml/composer.py
  ext2/yaml/constructor.py
  ext2/yaml/cyaml.py
  ext2/yaml/dumper.py
  ext2/yaml/emitter.py
  ext2/yaml/loader.py
  ext2/yaml/reader.py
  ext2/yaml/representer.py
  ext2/yaml/scanner.py
  ext3/yaml/__init__.py
  ext3/yaml/composer.py
  ext3/yaml/constructor.py
  ext3/yaml/cyaml.py
  ext3/yaml/dumper.py
  ext3/yaml/emitter.py
  ext3/yaml/loader.py
  ext3/yaml/reader.py
  ext3/yaml/representer.py
  ext3/yaml/scanner.py
  setup.py
  tests/providers/conftest.py
  tests/test_guessit.py
Labels: Concluded

#6355 Fix Kodi notifications decoding. Fixes #6354
  CHANGELOG.md
  medusa/notifiers/kodi.py
  medusa/notifiers/slack.py
  medusa/providers/torrent/html/bjshare.py
  medusa/providers/torrent/json/torrentday.py
  medusa/scene_exceptions.py
Labels: Bug, Concluded

#6356 Fix auto update causing DB issues
  CHANGELOG.md
  medusa/app.py
  medusa/databases/main_db.py
  medusa/tv/series.py
  medusa/updater/github_updater.py
  medusa/updater/version_checker.py
Labels: Bug, Concluded

#6380 Fix trying to retrieve 'hash' from an empty dict. Fixes #6377
  medusa/clients/torrent/deluged.py
Labels: Concluded

#6386 Release/release 0.3.1
  .travis.yml
  CHANGELOG.md
  ext/cfscrape/__init__.py
  ext/readme.md
  ext2/yaml/__init__.py
  ext2/yaml/composer.py
  ext2/yaml/constructor.py
  ext2/yaml/cyaml.py
  ext2/yaml/dumper.py
  ext2/yaml/emitter.py
  ext2/yaml/loader.py
  ext2/yaml/reader.py
  ext2/yaml/representer.py
  ext2/yaml/scanner.py
  ext3/yaml/__init__.py
  ext3/yaml/composer.py
  ext3/yaml/constructor.py
  ext3/yaml/cyaml.py
  ext3/yaml/dumper.py
  ext3/yaml/emitter.py
  ext3/yaml/loader.py
  ext3/yaml/reader.py
  ext3/yaml/representer.py
  ext3/yaml/scanner.py
  medusa/app.py
  medusa/clients/torrent/deluged.py
  medusa/common.py
  medusa/databases/main_db.py
  medusa/notifiers/kodi.py
  medusa/notifiers/slack.py
  medusa/providers/torrent/html/bjshare.py
  medusa/providers/torrent/json/torrentday.py
  medusa/scene_exceptions.py
  medusa/tv/series.py
  medusa/updater/github_updater.py
  medusa/updater/version_checker.py
  requirements.txt
  setup.py
  tests/providers/conftest.py
  tests/test_guessit.py
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/js/vendors.js
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#6391 Update cfscrape to version 1.9.7
  ext/cfscrape/__init__.py
  ext/readme.md
  requirements.txt
Labels: Concluded

#6399 Fix sending kodi notifications using python3
  medusa/notifiers/kodi.py
Labels: Bug, Concluded

#6428 Fix running extra scripts in Python 3. Fixes #6395
  CHANGELOG.md
  medusa/post_processor.py
  medusa/subtitles.py
  themes-default/slim/src/components/helpers/select-list.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#6430 Fix Torrenting provider exception when offline
  CHANGELOG.md
  medusa/providers/torrent/html/torrenting.py
Labels: Bug, Concluded
