Repository pymedusa/Medusa, pull requests merged in 2019-04, with the labels that each got.

#6455 Fix showing Quality Preferred in show-header when configured
  CHANGELOG.md
  themes-default/slim/src/components/show-header.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#6457 Fix snatching of air by date shows specials
  CHANGELOG.md
  medusa/classes.py
Labels: Bug, Concluded

#6487 Improve Travis build check by adding size comparison
  .github/build-themes-check.sh
Labels: Concluded, Enhancement

#6498 Fix tablesorter referencing to internal version of jQuery. Fixes #6497
  themes-default/slim/webpack.config.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/vendors.js
Labels: Bug, Concluded

#6525 Don't enable `faulthandler` if running `pythonw`
  lib/unrar2/windows.py
Labels: Concluded

#6527 Fix email notifier name parser. Fixes #6526
  CHANGELOG.md
  medusa/notifiers/emailnotify.py
  tests/notifiers/test_emailnotify.py
Labels: Bug, Concluded

#6532 Fix anime series not being matched to found results
  medusa/__main__.py
  medusa/helper/common.py
  medusa/metadata/tivo.py
  medusa/name_parser/parser.py
  medusa/notifiers/emailnotify.py
  medusa/post_processor.py
  medusa/providers/generic_provider.py
  medusa/providers/torrent/html/elitetracker.py
  medusa/scene_exceptions.py
  medusa/search/core.py
  medusa/server/web/home/add_shows.py
  medusa/server/web/home/handler.py
  medusa/subtitle_providers/wizdom.py
  tests/name_parser/test_parse_anime.py
  tests/name_parser/test_parse_series.py
Labels: Bug, Concluded, Enhancement, Needs test (Python)

#6625 Fix sending to trash not working on Python 3.6+
  CHANGELOG.md
  lib/readme.md
  lib/send2trash/__init__.py
  lib/send2trash/compat.py
  lib/send2trash/exceptions.py
  lib/send2trash/plat_gio.py
  lib/send2trash/plat_osx.py
  lib/send2trash/plat_other.py
  lib/send2trash/plat_win.py
Labels: Bug, Concluded, Update dep (Py)

#6619 Bugfix/issue6617
  medusa/clients/nzb/nzbget.py
  medusa/search/core.py
Labels: Bug, Concluded
