Repository pymedusa/Medusa, pull requests merged in 2019-09, with the labels that each got.

#7103 Fix snatching for Xthor provider with Python 3
  CHANGELOG.md
  medusa/providers/torrent/json/xthor.py
Labels: Bug, Concluded

#7104 Only show warning if app.CREATE_MISSING_SHOW_DIRS is disabled
  medusa/tv/series.py
Labels: Concluded, Enhancement

#6718 Remove forcedSearchQueueItem, in favor of using backlogQueueItem for single ep searches
  CHANGELOG.md
  medusa/search/manual.py
  medusa/search/queue.py
  medusa/server/api/v1/core.py
  medusa/server/api/v2/search.py
  medusa/server/web/home/handler.py
Labels: Concluded

#7109 Update requirement lists
  ext/readme.md
  requirements.txt
  setup.py
Labels: Concluded

#7113 Save updated show info when adding new show
  medusa/show_queue.py
Labels: Bug, Concluded

#7106 Allow to set scene numbering even if disabled
  medusa/providers/generic_provider.py
  medusa/scene_numbering.py
  medusa/search/queue.py
  tests/providers/test_generic_provider.py
Labels: Enhancement, In progress

#7122 Sync master and develop
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded

#7178 Feature/debug ensure list
  medusa/helpers/__init__.py
Labels: Bug, Concluded

#6977 Remove checks that prevent adding show without any episodes.
  CHANGELOG.md
  medusa/databases/main_db.py
  medusa/indexers/indexer_base.py
  medusa/indexers/indexer_config.py
  medusa/indexers/indexer_exceptions.py
  medusa/indexers/tmdb/tmdb.py
  medusa/indexers/tvdbv2/fallback.py
  medusa/indexers/tvdbv2/tvdbv2_api.py
  medusa/network_timezones.py
  medusa/server/api/v1/core.py
  medusa/show_queue.py
  medusa/tv/series.py
Labels: Concluded, Enhancement

#7190 Add multi episode start + end, instead of asuming it starts with 1.
  CHANGELOG.md
  medusa/providers/torrent/json/animebytes.py
Labels: Bug, Concluded

#7189 Feature/add notifier discord
  CHANGELOG.md
  medusa/__main__.py
  medusa/app.py
  medusa/notifiers/__init__.py
  medusa/notifiers/discord.py
  medusa/server/api/v2/config.py
  medusa/server/web/home/handler.py
  themes-default/slim/src/store/modules/notifiers/discord.js
  themes-default/slim/src/store/modules/notifiers/index.js
  themes-default/slim/static/css/style.css
  themes-default/slim/static/images/32x_sprite_colored_notifiers.png
  themes-default/slim/views/config_notifications.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/img/32x_sprite_colored_notifiers.png
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_notifications.mako
  themes/light/assets/css/style.css
  themes/light/assets/img/32x_sprite_colored_notifiers.png
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_notifications.mako
Labels: Concluded, Feature request
