Repository pymedusa/Medusa, pull requests merged in 2019-01, with the labels that each got.

#5967 Fix progressbars (home)
  medusa/version_checker.py
  setup.py
  tests/providers/conftest.py
  tests/providers/test_search.py
  themes-default/slim/views/partials/home/banner.mako
  themes-default/slim/views/partials/home/poster.mako
  themes-default/slim/views/partials/home/simple.mako
  themes-default/slim/views/partials/home/small.mako
  themes/dark/templates/partials/home/banner.mako
  themes/dark/templates/partials/home/poster.mako
  themes/dark/templates/partials/home/simple.mako
  themes/dark/templates/partials/home/small.mako
  themes/light/templates/partials/home/banner.mako
  themes/light/templates/partials/home/poster.mako
  themes/light/templates/partials/home/simple.mako
  themes/light/templates/partials/home/small.mako
Labels: Bug, Concluded

#5977 Fix recommended shows error. Fixes #5962
  medusa/show/recommendations/anidb.py
  medusa/show/recommendations/imdb.py
  medusa/show/recommendations/recommended.py
  medusa/show/recommendations/trakt.py
Labels: Bug, Concluded

#5983 Update soupsieve to v1.7, add missing dependency. Fixes #5968
  ext/readme.md
  ext/soupsieve/__meta__.py
  ext/soupsieve/css_match.py
  ext/soupsieve/css_parser.py
  ext/soupsieve/css_types.py
  ext2/backports/__init__.py
  ext2/backports/functools_lru_cache.py
Labels: Bug, Concluded

#5985 Catch RequestException in torrent clients, make warning. Fixes: #5921
  medusa/clients/torrent/generic.py
Labels: Bug, Concluded

#6000 Fix validate_location usage on episode object. Fixes #5999
  medusa/metadata/generic.py
Labels: Bug, Concluded

#6035 Update Python support information
  readme.md
Labels: Needs review

#6053 Webpack: Always minify vendored CSS
  themes-default/slim/package.json
  themes-default/slim/src/index.js
  themes-default/slim/static/css/lib/vue-snotify-material.css
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/webpack.config.js
  themes-default/slim/yarn.lock
  themes/dark/assets/css/lib/vue-snotify-material.css
  themes/dark/assets/css/vendors.css
  themes/dark/assets/js/index.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/css/lib/vue-snotify-material.css
  themes/light/assets/css/vendors.css
  themes/light/assets/js/index.js
  themes/light/assets/js/vendors.js
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#6067 Fix OrderedDict mutated during iteration in name_parser. Fixes #6064
  medusa/name_parser/parser.py
Labels: Bug, Concluded

#6033 Feature/add ignored required exclude option
  CHANGELOG.md
  dredd/api-description.yml
  medusa/databases/main_db.py
  medusa/server/api/v2/series.py
  medusa/tv/series.py
  tests/test_words.py
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/views/editShow.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/editShow.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/editShow.mako
Labels: Concluded, Enhancement

#6018 Initial version_checker refactor
  CHANGELOG.md
  medusa/__main__.py
  medusa/config.py
  medusa/github_client.py
  medusa/server/api/v1/core.py
  medusa/server/web/core/error_logs.py
  medusa/server/web/home/handler.py
  medusa/updater/__init__.py
  medusa/updater/docker_updater.py
  medusa/updater/github_updater.py
  medusa/updater/source_updater.py
  medusa/updater/update_manager.py
  medusa/updater/version_checker.py
  medusa/version_checker.py
  setup.cfg
  tests/conftest.py
Labels: Concluded, Enhancement

#6077 Fix restart after update
  medusa/__main__.py
Labels: Bug, Concluded

#5948 [WIP] Add initial pagination to the states getShows method.
  medusa/server/api/v2/base.py
  medusa/tv/episode.py
  themes-default/slim/src/components/show.vue
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/displayShow.mako
  themes/dark/templates/partials/showheader.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/displayShow.mako
  themes/light/templates/partials/showheader.mako
Labels: Concluded, Enhancement

#6149 Fix deprecated get_newest_commit_hash() reference. Fixes #6081
  medusa/server/api/v1/core.py
  medusa/updater/version_checker.py
Labels: Bug, Concluded
