Repository pymedusa/Medusa, pull requests merged in 2019-05, with the labels that each got.

#6638 Update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: Concluded, Enhancement

#6636 Fix setting episodes to archived in backlog overview. Fixes #6627
  CHANGELOG.md
  themes-default/slim/views/manage_backlogOverview.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/light/templates/manage_backlogOverview.mako
Labels: Bug, Concluded

#6635 Add gimmepeers torrent provider
  CHANGELOG.md
  medusa/providers/__init__.py
  medusa/providers/torrent/__init__.py
  medusa/providers/torrent/html/gimmepeers.py
  themes-default/slim/static/images/providers/gimmepeers.png
  themes/dark/assets/img/providers/gimmepeers.png
  themes/light/assets/img/providers/gimmepeers.png
Labels: Concluded

#6628 Update requirements
  SickBeard.py
  ext/readme.md
  ext2/backports_abc.py
  ext2/singledispatch.py
  ext2/singledispatch_helpers.py
  lib/readme.md
  medusa/init/__init__.py
  requirements.txt
  start.py
Labels: Concluded

#6643 Open log file as unicode instead of bytes. Fixes #5463
  medusa/logger/__init__.py
Labels: Bug, Concluded, Needs testing

#6656 Change get_redirect_url() to retrieve the last redirect URL. Fixes #6610
  medusa/providers/torrent/torrent_provider.py
Labels: Concluded, Enhancement

#6657 New url for Yggtorrent provider
  medusa/providers/torrent/html/yggtorrent.py
Labels: Concluded

#6678 Add back BTDB torrent provider
  CHANGELOG.md
  medusa/providers/__init__.py
  medusa/providers/torrent/__init__.py
  medusa/providers/torrent/html/btdb.py
  medusa/providers/torrent/html/morethantv.py
  tests/providers/conftest.py
  tests/providers/torrent/btdb/btdb_backlog.yaml
  tests/providers/torrent/btdb/btdb_daily.yaml
  tests/providers/torrent/btdb/btdb_test.yaml
  tests/providers/torrent/tntvillage/tntvillage_backlog.yaml
  tests/providers/torrent/tntvillage/tntvillage_daily.yaml
  tests/providers/torrent/tntvillage/tntvillage_test.yaml
Labels: Bug, Concluded, Enhancement

#6680 Fix Elite-Tracker exception when no result is returned
  CHANGELOG.md
  medusa/providers/torrent/html/elitetracker.py
Labels: Bug, Concluded

#6693 Switch to official cfscrape v2.0.5, patch the lib on init
  ext/cfscrape/__init__.py
  ext/cfscrape/user_agents.json
  ext/readme.md
  medusa/init/__init__.py
  medusa/init/cfscrape.py
  medusa/session/handlers.py
  requirements.txt
Labels: Concluded, Enhancement

#6703 Fix API v2 exception on incorrect API key. Fixes #5425
  CHANGELOG.md
  medusa/server/api/v2/auth.py
  medusa/server/api/v2/base.py
  tests/apiv2/test_auth.py
Labels: Backend, Bug, Concluded

#6705 Remove old regex pattern from `CensoredFormatter`
  CHANGELOG.md
  medusa/logger/__init__.py
Labels: Bug, Concluded

#6706 Fix 2 small mistakes in APIv2
  medusa/server/api/v2/base.py
  medusa/server/api/v2/series.py
Labels: Bug, Concluded

#6710 Update babel config
  themes-default/slim/.babelrc
  themes-default/slim/babel.config.js
  themes-default/slim/package.json
  themes-default/slim/webpack.config.js
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
Labels: Enhancement, Frontend

#6712 IssueSubmitter: Ignore issues marked as duplicates
  medusa/issue_submitter.py
  tests/conftest.py
  tests/test_issue_submitter.py
Labels: Concluded, Enhancement

#6707 Further improvements to API v2 multithreading
  medusa/server/api/v2/alias.py
  medusa/server/api/v2/alias_source.py
  medusa/server/api/v2/auth.py
  medusa/server/api/v2/base.py
  medusa/server/api/v2/config.py
  medusa/server/api/v2/episodes.py
  medusa/server/api/v2/internal.py
  medusa/server/api/v2/log.py
  medusa/server/api/v2/series.py
  medusa/server/api/v2/series_asset.py
  medusa/server/api/v2/series_legacy.py
  medusa/server/api/v2/series_operation.py
  medusa/server/api/v2/stats.py
  medusa/server/core.py
Labels: Concluded, Enhancement, Needs review

#6702 Fix DelugeD remove torrents when ratio is reached. Fixes #6695
  CHANGELOG.md
  medusa/clients/torrent/deluge.py
  medusa/clients/torrent/deluged.py
  medusa/clients/torrent/transmission.py
Labels: Bug, Concluded

#6720 Fix Failed Downloads header
  themes-default/slim/src/router.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#6723 Replace `xo` with `eslint`
  .eslintignore
  .eslintrc
  .travis.yml
  package.json
  themes-default/helper.js
  themes-default/slim/.eslintignore
  themes-default/slim/.eslintrc
  themes-default/slim/.eslintrc.js
  themes-default/slim/.gitignore
  themes-default/slim/package.json
  themes-default/slim/src/components/home.vue
  themes-default/slim/yarn.lock
  yarn.lock
Labels: Concluded

#6724 Complete sub menu
  CHANGELOG.md
  medusa/server/web/config/anime.py
  medusa/server/web/config/backup_restore.py
  medusa/server/web/config/general.py
  medusa/server/web/config/handler.py
  medusa/server/web/config/notifications.py
  medusa/server/web/config/post_processing.py
  medusa/server/web/config/providers.py
  medusa/server/web/config/search.py
  medusa/server/web/config/subtitles.py
  medusa/server/web/core/base.py
  medusa/server/web/core/error_logs.py
  medusa/server/web/core/history.py
  medusa/server/web/home/handler.py
  themes-default/slim/src/app.js
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/sub-menu.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/router.js
  themes-default/slim/test/specs/__snapshots__/sub-menu.spec.js.snap
  themes-default/slim/test/specs/sub-menu.spec.js
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/vue-components/sub-menu.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/layouts/main.mako
  themes/light/templates/vue-components/sub-menu.mako
Labels: Concluded, Enhancement, Frontend

#6732 Remove `NonEmptyDict` and fix DB version
  medusa/__main__.py
  medusa/helper/mappings.py
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/src/components/config-post-processing.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Backend, Concluded

#6733 Vue UI Fixes / Updates
  themes-default/slim/.eslintrc.js
  themes-default/slim/src/api.js
  themes-default/slim/src/app.js
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/config.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/router.js
  themes-default/slim/src/store/modules/qualities.js
  themes-default/slim/src/utils.js
  themes-default/slim/static/js/home/restart.js
  themes-default/slim/static/js/trending-shows.js
  themes-default/slim/test/__fixtures__/app-header.json
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/__snapshots__/config.spec.js.snap
  themes-default/slim/test/specs/utils.spec.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/home/restart.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/trending-shows.js
  themes/light/assets/js/app.js
  themes/light/assets/js/home/restart.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/trending-shows.js
Labels: Concluded, Frontend

#6738 Vueify log viewer (and use Backstretch)
  .travis.yml
  CHANGELOG.md
  dredd/.gitignore
  dredd/api-description.yml
  dredd/dredd_hook.py
  medusa/server/api/v2/config.py
  medusa/server/api/v2/log.py
  medusa/server/web/core/error_logs.py
  tests/apiv2/test_config.py
  tests/apiv2/test_log.py
  themes-default/slim/src/components/backstretch.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/logs.vue
  themes-default/slim/src/router.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/static/css/style.css
  themes-default/slim/static/js/common/init.js
  themes-default/slim/test/__fixtures__/app-header.json
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/__fixtures__/example-logs.json
  themes-default/slim/test/specs/__snapshots__/logs.spec.js.snap
  themes-default/slim/test/specs/logs.spec.js
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/history.mako
  themes-default/slim/views/home.mako
  themes-default/slim/views/schedule.mako
  themes-default/slim/views/snatchSelection.mako
  themes-default/slim/views/status.mako
  themes-default/slim/views/testRename.mako
  themes-default/slim/views/viewlogs.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/displayShow.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/history.mako
  themes/dark/templates/home.mako
  themes/dark/templates/schedule.mako
  themes/dark/templates/snatchSelection.mako
  themes/dark/templates/status.mako
  themes/dark/templates/testRename.mako
  themes/dark/templates/viewlogs.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/common/init.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/displayShow.mako
  themes/light/templates/editShow.mako
  themes/light/templates/history.mako
  themes/light/templates/home.mako
  themes/light/templates/schedule.mako
  themes/light/templates/snatchSelection.mako
  themes/light/templates/status.mako
  themes/light/templates/testRename.mako
  themes/light/templates/viewlogs.mako
Labels: Concluded, Frontend, Needs review

#6748 UI Improvements
  themes-default/slim/src/app.js
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/helpers/app-link.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/store/modules/auth.js
  themes-default/slim/src/store/modules/config.js
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/__snapshots__/app-link.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/config.spec.js.snap
  themes-default/slim/test/specs/app-link.spec.js
  themes-default/slim/test/specs/config.spec.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_episodeStatuses.mako
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_episodeStatuses.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_episodeStatuses.mako
Labels: Concluded, Frontend

#6740 Optimize show_statistics()
  medusa/server/api/v2/stats.py
  medusa/server/web/home/handler.py
Labels: Backend, Discussion, Enhancement, Needs testing

#6751 Fix rare BTDB exception when there are no recent items. Fixes #6729
  medusa/providers/torrent/html/btdb.py
Labels: Bug, Concluded

#6752 Fix missing sub menu on errors page
  themes-default/slim/src/router.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#6754 Fix home page slowdown - layout imported twice
  CHANGELOG.md
  themes-default/slim/views/home.mako
  themes/dark/templates/home.mako
  themes/light/templates/home.mako
Labels: Bug, Concluded, Priority: 2. Medium
