Repository pymedusa/Medusa, pull requests merged in 2019-08, with the labels that each got.

#6810 Avoid post-processor concurrency issues
  medusa/__main__.py
  medusa/app.py
  medusa/auto_post_processor.py
  medusa/config.py
  medusa/process_tv.py
  medusa/server/api/v1/core.py
  medusa/server/web/home/post_process.py
  medusa/subtitles.py
  medusa/system/schedulers.py
  medusa/updater/version_checker.py
  themes-default/slim/package.json
  themes-default/slim/views/status.mako
  themes-default/slim/yarn.lock
  themes/dark/templates/status.mako
  themes/light/templates/status.mako
Labels: Concluded, Enhancement

#7046 Fix loading displayShow using python3 when app.DOWNLOAD_URL is used
  themes-default/slim/views/displayShow.mako
  themes/dark/templates/displayShow.mako
  themes/light/templates/displayShow.mako
Labels: Bug, Concluded

#6976 Fix testing plex media server (PMS)
  CHANGELOG.md
  medusa/notifiers/plex.py
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#6982 Improve postprocessing name parsing.
  .travis.yml
  medusa/common.py
  medusa/recompiled/tags.py
  medusa/tagger/episode.py
  tests/test_postprocessor_parse_info.py
Labels: Bug, Concluded, Enhancement

#7061 Add optional anime argument in name parser recursion
  medusa/common.py
Labels: Concluded

#7069 Escape word used in regex filter. Fixes #7068
  medusa/show/naming.py
Labels: Bug, Concluded

#7094 Fix Torrentz2 size parsing confusing GB with MB
  medusa/providers/torrent/xml/torrentz2.py
Labels: Bug, Concluded

#7085 Enhanced show-header to combine and show local show and global preferred words
  CHANGELOG.md
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/views/config_search.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_search.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_search.mako
Labels: Concluded, Enhancement, Frontend

#7098 Add timezone package
  Dockerfile
Labels: Concluded

#7102 Reset dirty flag when changes to episodes are made
  CHANGELOG.md
  medusa/tv/episode.py
Labels: Bug, Concluded
