Repository pymedusa/Medusa, pull requests merged in 2019-02, with the labels that each got.

#6159 Fix tests by updating flake8 rules
  medusa/helpers/__init__.py
  medusa/indexers/indexer_api.py
  medusa/indexers/indexer_config.py
  medusa/name_cache.py
  medusa/notifiers/__init__.py
  medusa/notifiers/kodi.py
  medusa/post_processor.py
  medusa/providers/nzb/newznab.py
  medusa/sbdatetime.py
  medusa/scene_exceptions.py
  medusa/search/core.py
  medusa/server/api/v2/internal.py
  medusa/server/web/config/providers.py
  medusa/server/web/config/subtitles.py
  medusa/server/web/manage/handler.py
  medusa/show/naming.py
  medusa/updater/source_updater.py
  setup.cfg
Labels: Concluded

#6155 Fix guessit exception when trying to parse music releases
  medusa/name_parser/rules/rules.py
Labels: Bug, Concluded

#6201 Decode other_shows in newShow. Fixes #6185
  medusa/server/web/home/add_shows.py
Labels: Bug, Concluded

#6207 Fix wrong Forced backlog search day(s) description. Fixes #6161
  themes-default/slim/views/config_search.mako
  themes/dark/templates/config_search.mako
  themes/light/templates/config_search.mako
Labels: Concluded, Enhancement

#6206 Fix trying to use error.response while None for Telegram. Fixes #6065
  medusa/notifiers/telegram.py
Labels: Bug, Concluded

#6208 Use response.text instead of content for nzb_check_segment. Fixes #6195
  medusa/providers/nzb/binsearch.py
Labels: Bug, Concluded

#6209 Fix wrong placeholder name causing BraceException. Fixes #6165
  medusa/clients/nzb/nzbget.py
Labels: Bug, Concluded

#6210 Remove esm, @babel/register and @babel/polyfill
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded, Remove dep (JS)

#6213 Fix date added not showing if pubdate is missing
  themes-default/slim/views/snatchSelection.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/templates/snatchSelection.mako
Labels: Bug, Concluded

#6189 Vueify show header
  CHANGELOG.md
  dredd/api-description.yml
  medusa/helpers/utils.py
  medusa/server/web/home/handler.py
  medusa/tv/series.py
  themes-default/slim/package.json
  themes-default/slim/src/app.js
  themes-default/slim/src/components/helpers/state-switch.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/components/show.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/src/store/modules/qualities.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/src/utils.js
  themes-default/slim/static/css/style.css
  themes-default/slim/test/__fixtures__/shows.json
  themes-default/slim/views/displayShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/partials/showheader.mako
  themes-default/slim/views/snatchSelection.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/css/style.css
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/dark/templates/displayShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/partials/showheader.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
  themes/light/templates/displayShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/partials/showheader.mako
  themes/light/templates/snatchSelection.mako
Labels: Concluded

#6225 Fix snatch selection loading detailed show
  themes-default/slim/src/components/snatch-selection.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#6236 Fix synchronousdeluge lib returning bytes. Fixes #5304
  lib/synchronousdeluge/__init__.py
  lib/synchronousdeluge/exceptions.py
  lib/synchronousdeluge/protocol.py
  lib/synchronousdeluge/transfer.py
Labels: Bug, Concluded

#6248 Fix unnecessary float comparison in show_updater. Fixes #6247
  medusa/show_updater.py
Labels: Bug, Concluded

#6246 Clean up naming pattern validation. Fixes #6237
  medusa/__main__.py
  medusa/naming.py
  medusa/server/api/v1/core.py
  medusa/tv/episode.py
  medusa/tv/series.py
  themes-default/slim/views/editShow.mako
  themes/dark/templates/editShow.mako
  themes/light/templates/editShow.mako
Labels: Bug, Concluded

#6252 Decode one more other_shows in add_shows. Fixes #5884
  medusa/server/web/home/add_shows.py
Labels: Bug, Concluded

#6251 Update guessit to latest development version
  ext/guessit/__main__.py
  ext/guessit/__version__.py
  ext/guessit/api.py
  ext/guessit/config/options.json
  ext/guessit/options.py
  ext/guessit/rules/common/formatters.py
  ext/guessit/rules/properties/audio_codec.py
  ext/guessit/rules/properties/bonus.py
  ext/guessit/rules/properties/episodes.py
  ext/guessit/rules/properties/language.py
  ext/guessit/rules/properties/other.py
  ext/guessit/rules/properties/release_group.py
  ext/guessit/rules/properties/source.py
  ext/guessit/rules/properties/streaming_service.py
  ext/guessit/rules/properties/title.py
  ext/guessit/test/enable_disable_properties.yml
  ext/guessit/test/episodes.yml
  ext/guessit/test/movies.yml
  ext/guessit/test/rules/common_words.yml
  ext/guessit/test/rules/country.yml
  ext/guessit/test/rules/other.yml
  ext/guessit/test/suggested.json
  ext/guessit/test/test_api.py
  ext/guessit/test/test_yml.py
  ext/guessit/test/various.yml
  ext/guessit/yamlutils.py
  ext/readme.md
  medusa/name_parser/rules/rules.py
  requirements.txt
  tests/test_guessit.yml
Labels: Concluded, Enhancement
