Repository pymedusa/Medusa, pull requests merged in 2019-10, with the labels that each got.

#7194 Feature/vueify config notifications
  medusa/notifiers/tweet.py
  medusa/server/api/v2/config.py
  medusa/server/web/config/notifications.py
  themes-default/slim/src/components/config-notifications.vue
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/router/routes.js
  themes-default/slim/src/store/modules/notifiers/index.js
  themes-default/slim/src/store/modules/notifiers/twitter.js
  themes-default/slim/views/config_notifications.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_notifications.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_notifications.mako
Labels: Concluded, Enhancement, Frontend

#7192 Fix guessit UnicodeDecodeError on join (Py2)
  CHANGELOG.md
  medusa/name_parser/rules/rules.py
  medusa/search/queue.py
Labels: Bug, Concluded

#7250 Provider maintenance
  CHANGELOG.md
  medusa/clients/torrent/transmission.py
  medusa/providers/torrent/html/beyondhd.py
  medusa/providers/torrent/html/bjshare.py
  medusa/providers/torrent/html/btdb.py
Labels: Backend, Concluded, Provider

#7256 Fix exception when there is no anime XML
  CHANGELOG.md
  ext/adba/aniDBtvDBmaper.py
  ext/readme.md
  requirements.txt
Labels: Bug, Concluded

#7205 Feature/vueify config search
  medusa/server/web/config/search.py
  themes-default/slim/src/components/config-search.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/router/routes.js
  themes-default/slim/views/config_search.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_search.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_search.mako
Labels: Concluded, Frontend

#7297 display-show.vue: fix show fanart
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded
