Repository pymedusa/Medusa, pull requests merged in 2019-12, with the labels that each got.

#7438 Feature/option pagination
  medusa/__main__.py
  medusa/app.py
  medusa/server/api/v2/config.py
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/store/modules/layout.js
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#7445 Fix config-search.vue.
  themes-default/slim/src/components/config-search.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7446 Update bower to version 1.8.8
  .build/package.json
  .build/yarn.lock
Labels: Concluded

#7449 Fix backlog search queue with multiple items. Fixes #7448
  medusa/search/queue.py
Labels: Bug, Concluded

#7452 Fix show number forced searches, in manage_manageSearches.mako.
  themes-default/slim/views/manage_manageSearches.mako
  themes/dark/templates/manage_manageSearches.mako
  themes/light/templates/manage_manageSearches.mako
Labels: Concluded

#7415 When a user makes use of the shows quality preset options, the qualit…
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/store/modules/consts.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement, Frontend

#7460 Bring back code to use season images for TVDB API
  medusa/indexers/tvdbv2/tvdbv2_api.py
Labels: Concluded, Enhancement

#7471 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  setup.cfg
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded

#7472 Fix season pack downloads occurring even if not needed
  CHANGELOG.md
  medusa/classes.py
  medusa/providers/generic_provider.py
  medusa/tv/cache.py
Labels: Bug, Concluded

#7474 qBittorrent client maintenance
  CHANGELOG.md
  medusa/clients/torrent/qbittorrent.py
Labels: Bug, Concluded

#7478 Feature/fix config general
  CHANGELOG.md
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/home.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend

#7480 Release 0.3.9
  CHANGELOG.md
  medusa/classes.py
  medusa/clients/torrent/qbittorrent.py
  medusa/common.py
  medusa/providers/generic_provider.py
  medusa/tv/cache.py
  setup.cfg
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/home.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#7496 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#7490 Fix double loading of episodes.
  themes-default/slim/src/store/modules/shows.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7484 Fix missing qBittorrent category/label logs error
  medusa/clients/torrent/qbittorrent.py
Labels: Bug, Concluded

#7488 Fix plot-info.vue
  themes-default/slim/src/components/helpers/plot-info.vue
  themes-default/slim/views/home.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/home.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/home.mako
Labels: Concluded

#7483 Add `uniqueid` to Kodi 12+ show metadata
  CHANGELOG.md
  medusa/metadata/kodi_12plus.py
Labels: Concluded, Enhancement

#7497 Fix Emby notifier error on Python 3
  CHANGELOG.md
  medusa/notifiers/emby.py
Labels: Bug, Concluded

#7498 Update AppLink to enable native mouse navigation
  CHANGELOG.md
  themes-default/slim/src/components/helpers/app-link.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#7501 Fix more qBittorrent authentication bugs
  CHANGELOG.md
  medusa/clients/torrent/qbittorrent.py
  themes-default/slim/src/components/config-search.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7502 Fixed dragging and saving Anime / Series list handles in Home - Poste…
  CHANGELOG.md
  themes-default/slim/src/components/home.vue
  themes-default/slim/views/home.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/home.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/home.mako
Labels: Bug, Concluded

#7507 Fix adding anime shows with the white or blacklisted release groups set.
  CHANGELOG.md
  medusa/server/web/home/add_shows.py
Labels: Bug, Concluded

#7512 Fix schedule and forced search from schedule
  CHANGELOG.md
  themes-default/slim/src/components/schedule.vue
  themes-default/slim/src/global-vue-shim.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7517 Fix manual search page release name bug - Fixes #7516
  CHANGELOG.md
  setup.py
  themes-default/slim/views/snatchSelection.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/templates/snatchSelection.mako
Labels: Bug, Concluded, Frontend

#7526 Fix #7525 - being unable to save post-processing config
  CHANGELOG.md
  medusa/server/api/v2/config.py
  themes-default/slim/src/components/config-post-processing.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7541 Fix error when torrent queueing is disabled on qBT
  CHANGELOG.md
  medusa/clients/torrent/qbittorrent.py
Labels: Bug, Concluded
