Repository pymedusa/Medusa, pull requests merged in 2019-11, with the labels that each got.

#7303 Fix BTDB manual search & update Xthor domain
  CHANGELOG.md
  medusa/providers/torrent/html/btdb.py
  medusa/providers/torrent/json/xthor.py
Labels: Bug, Concluded

#7305 Add field `identfier` to provider cache tables.
  CHANGELOG.md
  medusa/classes.py
  medusa/databases/cache_db.py
  medusa/providers/generic_provider.py
  medusa/providers/nzb/binsearch.py
  medusa/providers/torrent/torznab/torznab.py
  medusa/tv/cache.py
Labels: Bug, Concluded

#7317 Refactor SearchResult
  medusa/classes.py
  medusa/providers/generic_provider.py
  medusa/providers/nzb/nzb_provider.py
  medusa/providers/torrent/torrent_provider.py
  medusa/providers/torrent/torznab/torznab.py
  medusa/search/core.py
  medusa/search/proper.py
  medusa/server/web/home/handler.py
  medusa/tv/cache.py
  tests/conftest.py
  tests/test_search_core.py
Labels: Bug, Concluded, Enhancement

#7321 Fix vue-cookies expire date.
  themes-default/slim/src/global-vue-shim.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7322 manage_backlogOverview.mako: Fix updating forced search icons.
  themes-default/slim/views/manage_backlogOverview.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/light/templates/manage_backlogOverview.mako
Labels: Bug, Concluded

#7323 Feature/fix behondhd
  CHANGELOG.md
  medusa/providers/generic_provider.py
  medusa/providers/torrent/html/beyondhd.py
Labels: Concluded, Provider

#7333 Fix exception when release groups aren't available for anime shows
  CHANGELOG.md
  medusa/search/core.py
Labels: Bug, Concluded

#7336 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded

#7355 Changes for TVDB API v3
  CHANGELOG.md
  medusa/image_cache.py
  medusa/indexers/tvdbv2/tvdbv2_api.py
  medusa/metadata/generic.py
Labels: Bug, Concluded

#7359 Fix the forced search modal text color, when using light theme.
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7380 Release 0.3.7
  CHANGELOG.md
  ext/readme.md
  ext/soupsieve/__init__.py
  ext/soupsieve/__meta__.py
  ext/soupsieve/css_match.py
  ext/soupsieve/css_parser.py
  ext/soupsieve/css_types.py
  ext/soupsieve/util.py
  ext2/backports/__init__.py
  ext2/backports/functools_lru_cache.py
  ext2/bs4/__init__.py
  ext2/bs4/builder/__init__.py
  ext2/bs4/builder/_html5lib.py
  ext2/bs4/builder/_htmlparser.py
  ext2/bs4/builder/_lxml.py
  ext2/bs4/check_block.py
  ext2/bs4/dammit.py
  ext2/bs4/element.py
  ext2/bs4/formatter.py
  ext2/bs4/testing.py
  ext2/bs4/tests/test_html5lib.py
  ext2/bs4/tests/test_htmlparser.py
  ext2/bs4/tests/test_lxml.py
  ext2/bs4/tests/test_soup.py
  ext2/bs4/tests/test_tree.py
  ext3/bs4/__init__.py
  ext3/bs4/builder/__init__.py
  ext3/bs4/builder/_html5lib.py
  ext3/bs4/builder/_htmlparser.py
  ext3/bs4/builder/_lxml.py
  ext3/bs4/check_block.py
  ext3/bs4/dammit.py
  ext3/bs4/diagnose.py
  ext3/bs4/element.py
  ext3/bs4/formatter.py
  ext3/bs4/testing.py
  ext3/bs4/tests/test_html5lib.py
  ext3/bs4/tests/test_htmlparser.py
  ext3/bs4/tests/test_lxml.py
  ext3/bs4/tests/test_soup.py
  ext3/bs4/tests/test_tree.py
  medusa/common.py
  medusa/image_cache.py
  medusa/indexers/tvdbv2/tvdbv2_api.py
  medusa/metadata/generic.py
  requirements.txt
  themes-default/slim/package.json
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#7401 displayShow: Fix imdb stars
  themes-default/slim/src/components/show-header.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend

#7405 Fix guessit anime titles treated as multiple episodes. Fixes #7396
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#7418 Fix missing episode numbers when anime doesn't have scene season
  medusa/name_parser/parser.py
Labels: Bug, Concluded

#7387 Improve search code consistency
  medusa/search/core.py
  medusa/tv/cache.py
  medusa/tv/series.py
  tests/conftest.py
  tests/test_search_core.py
Labels: Concluded, Enhancement

#7424 Fix dataDir shown at bottom of config pages.
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/config-search.vue
  themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/config-post-processing.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7426 Fix sorting on action and quality columns.
  themes-default/slim/src/components/history.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#7423 addShow: Start backlog search in forced queue, instead scheduled queue.
  medusa/search/backlog.py
  medusa/show_queue.py
  medusa/system/schedulers.py
  medusa/tv/series.py
  themes-default/slim/views/status.mako
  themes/dark/templates/status.mako
  themes/light/templates/status.mako
Labels: Bug, Concluded, Enhancement

#7427 Fix guessit parsing episodes with 1 before release group as multi
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#7429 Fix displaying of date/time in displayShow.vue.
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend
