Repository pymedusa/Medusa, pull requests merged in 2019-06, with the labels that each got.

#6756 Update to next version of date-fns
  themes-default/slim/package.json
  themes-default/slim/src/components/helpers/name-pattern.vue
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
Labels: Concluded

#6746 Restructure API qualities and statuses
  dredd/api-description.yml
  medusa/common.py
  medusa/search/manual.py
  medusa/server/api/v2/config.py
  medusa/tv/episode.py
  tests/apiv2/test_config.py
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/helpers/quality-pill.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/modules/consts.js
  themes-default/slim/src/store/modules/index.js
  themes-default/slim/src/store/modules/qualities.js
  themes-default/slim/src/store/modules/statuses.js
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/__snapshots__/quality-pill.spec.js.snap
  themes-default/slim/test/specs/add-show-options.spec.js
  themes-default/slim/test/specs/quality-pill.spec.js
  themes-default/slim/views/history.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/history.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/history.mako
Labels: Backend, Enhancement, Frontend

#6757 Fix frontend test warnings
  themes-default/slim/src/components/helpers/name-pattern.vue
  themes-default/slim/test/helpers/setup.js
  themes-default/slim/test/specs/__snapshots__/asset.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/logs.spec.js.snap
  themes-default/slim/test/specs/asset.spec.js
  themes-default/slim/test/specs/logs.spec.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#6758 Separate package.json deps and dev-deps
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded

#6737 Convert Quality Chooser to SFC
  CHANGELOG.md
  dredd/api-description.yml
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/helpers/index.js
  themes-default/slim/src/components/helpers/quality-chooser.vue
  themes-default/slim/src/index.js
  themes-default/slim/static/css/style.css
  themes-default/slim/test/specs/__snapshots__/add-show-options.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/quality-chooser.spec.js.snap
  themes-default/slim/test/specs/quality-chooser.spec.js
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage_massEdit.mako
  themes-default/slim/views/vue-components/quality-chooser.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/editShow.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage_massEdit.mako
  themes/dark/templates/vue-components/quality-chooser.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/editShow.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage_massEdit.mako
  themes/light/templates/vue-components/quality-chooser.mako
Labels: Concluded, Frontend, Needs review

#6763 Small UI fixes
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/test/specs/__snapshots__/show-selector.spec.js.snap
  themes-default/slim/test/specs/show-selector.spec.js
  themes-default/slim/views/500.mako
  themes-default/slim/views/config_notifications.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/500.mako
  themes/dark/templates/config_notifications.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/500.mako
  themes/light/templates/config_notifications.mako
Labels: Concluded, Frontend

#6762 Update knowit to 0.3.0-dev
  ext/knowit/__init__.py
  ext/knowit/__main__.py
  ext/knowit/api.py
  ext/knowit/defaults.yml
  ext/knowit/properties/duration.py
  ext/knowit/property.py
  ext/knowit/provider.py
  ext/knowit/providers/enzyme.py
  ext/knowit/providers/ffmpeg.py
  ext/knowit/providers/mediainfo.py
  ext/knowit/rules/__init__.py
  ext/knowit/rules/audio/__init__.py
  ext/knowit/rules/audio/atmos.py
  ext/knowit/rules/audio/dtshd.py
  ext/knowit/rules/language.py
  ext/knowit/serializer.py
  ext/knowit/utils.py
  ext/pint/__init__.py
  ext/pint/compat/__init__.py
  ext/pint/compat/chainmap.py
  ext/pint/compat/nullhandler.py
  ext/pint/context.py
  ext/pint/default_en.txt
  ext/pint/errors.py
  ext/pint/formatting.py
  ext/pint/matplotlib.py
  ext/pint/pint_eval.py
  ext/pint/quantity.py
  ext/pint/registry.py
  ext/pint/registry_helpers.py
  ext/pint/systems.py
  ext/pint/testsuite/__init__.py
  ext/pint/testsuite/compat/__init__.py
  ext/pint/testsuite/helpers.py
  ext/pint/testsuite/parameterized.py
  ext/pint/testsuite/test_contexts.py
  ext/pint/testsuite/test_issues.py
  ext/pint/testsuite/test_numpy.py
  ext/pint/testsuite/test_pint_eval.py
  ext/pint/testsuite/test_quantity.py
  ext/pint/testsuite/test_systems.py
  ext/pint/testsuite/test_umath.py
  ext/pint/testsuite/test_unit.py
  ext/pint/unit.py
  ext/pint/util.py
  ext/readme.md
  lib/pymediainfo/__init__.py
  lib/readme.md
  medusa/common.py
  medusa/subtitles.py
  medusa/tv/episode.py
  requirements.txt
Labels: Bug, Concluded

#6764 Add funcsigs 1.0.2 dependency (Pint 0.9, Python 2.7 only)
  ext/readme.md
  ext2/funcsigs/__init__.py
  ext2/funcsigs/version.py
Labels: Concluded

#6765 Improve DelugeD connect() to only return True if connected
  medusa/clients/torrent/deluged.py
Labels: Bug, Concluded

#6768 Catch RequestException in list_remote_branches(). Fixes #6312, #6767
  medusa/updater/source_updater.py
Labels: Bug, Concluded

#6773 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  readme.md
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
Labels: Concluded

#6784 Fix ShowHeader status/quality selector
  CHANGELOG.md
  themes-default/slim/src/components/show-header.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend

#6722 Update `setup.py`
  .github/check_version.py
  .gitignore
  MANIFEST.in
  ext/__init__.py
  ext3/__init__.py
  lib/__init__.py
  setup.py
Labels: Concluded, Discussion, Enhancement

#6787 Add DC Universe network logo
  themes-default/slim/static/images/network/dc-universe.png
  themes/dark/assets/img/network/dc-universe.png
  themes/light/assets/img/network/dc-universe.png
Labels: Concluded

#6727 Add subtitle search SFC
  themes-default/slim/package.json
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/subtitle-search.vue
  themes-default/slim/test/__fixtures__/show-detailed.json
  themes-default/slim/test/__fixtures__/show-episodes.json
  themes-default/slim/test/__fixtures__/subtitle-search.json
  themes-default/slim/test/specs/__snapshots__/subtitle-search.spec.js.snap
  themes-default/slim/test/specs/subtitle-search.spec.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/webpack.config.js
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/dark/assets/js/vendors~date-fns.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
  themes/light/assets/js/vendors~date-fns.js
  themes/light/templates/layouts/main.mako
Labels: Concluded, Frontend

#6790 Use old method to get the redirect URL for Jackett. Fixes #6788
  medusa/providers/torrent/torrent_provider.py
Labels: Bug, Concluded

#6796 Downgrade pymediainfo to v3.2.1. Fixes #6794 #6793 #6789
  CHANGELOG.md
  lib/pymediainfo/__init__.py
  lib/readme.md
Labels: Bug, Concluded

#6781 Add jQuery utils
  themes-default/slim/src/app.js
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/backstretch.vue
  themes-default/slim/src/components/helpers/quality-chooser.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/index.js
  themes-default/slim/src/utils.js
  themes-default/slim/src/utils/core.js
  themes-default/slim/src/utils/jquery.js
  themes-default/slim/test/specs/utils.spec.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
Labels: Do not merge, Frontend

#6717 Add queue_time and start_time, to get more info on when a specific qu…
  medusa/generic_queue.py
  medusa/search/manual.py
Labels: Concluded

#6807 Update API endpoints and store
  dredd/api-description.yml
  medusa/helpers/__init__.py
  medusa/helpers/utils.py
  medusa/server/api/v2/config.py
  medusa/server/api/v2/stats.py
  medusa/system/schedulers.py
  tests/apiv2/test_config.py
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/modules/index.js
  themes-default/slim/src/store/modules/stats.js
  themes-default/slim/src/store/modules/system.js
  themes-default/slim/src/store/mutation-types.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded

#6802 Added provider Beyond-HD
  CHANGELOG.md
  medusa/providers/__init__.py
  medusa/providers/torrent/__init__.py
  medusa/providers/torrent/html/beyondhd.py
  themes-default/slim/static/images/providers/beyond_hd.png
  themes-default/slim/static/images/providers/beyondhd.png
  themes-default/slim/static/images/providers/beyondhd_me.png
  themes/dark/assets/img/providers/beyond_hd.png
  themes/light/assets/img/providers/beyond_hd.png
Labels: Enhancement

#6821 Fix 'show_dir' referenced before assignment
  medusa/system/schedulers.py
  themes-default/slim/views/apiBuilder.mako
  themes-default/slim/views/layouts/main.mako
  themes/dark/templates/apiBuilder.mako
  themes/dark/templates/layouts/main.mako
  themes/light/templates/apiBuilder.mako
  themes/light/templates/layouts/main.mako
Labels: Backend, Bug, Concluded

#6822 Fix #6820 - RuntimeError: threads can only be started once
  medusa/system/schedulers.py
Labels: Backend, Bug, Concluded

#6825 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded

#6811 Simplify global component registration
  themes-default/slim/.eslintrc.js
  themes-default/slim/src/app.js
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/components/status.vue
  themes-default/slim/src/global-vue-shim.js
  themes-default/slim/src/index.js
  themes-default/slim/src/router/index.js
  themes-default/slim/src/router/routes.js
  themes-default/slim/static/js/add-shows/trending-shows.js
  themes-default/slim/static/js/ajax-episode-search.js
  themes-default/slim/views/config_notifications.mako
  themes-default/slim/views/config_search.mako
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/history.mako
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/manage.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes-default/slim/views/schedule.mako
  themes-default/slim/views/snatchSelection.mako
  themes/dark/assets/js/add-shows/trending-shows.js
  themes/dark/assets/js/ajax-episode-search.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_notifications.mako
  themes/dark/templates/config_search.mako
  themes/dark/templates/editShow.mako
  themes/dark/templates/history.mako
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/manage.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/dark/templates/schedule.mako
  themes/dark/templates/snatchSelection.mako
  themes/light/assets/js/add-shows/trending-shows.js
  themes/light/assets/js/ajax-episode-search.js
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_notifications.mako
  themes/light/templates/config_search.mako
  themes/light/templates/editShow.mako
  themes/light/templates/history.mako
  themes/light/templates/layouts/main.mako
  themes/light/templates/manage.mako
  themes/light/templates/manage_backlogOverview.mako
  themes/light/templates/schedule.mako
  themes/light/templates/snatchSelection.mako
Labels: Concluded, Enhancement, Frontend

#6827 Use alternative method to get the redirect URL for Jackett. Fixes #6826
  CHANGELOG.md
  medusa/providers/torrent/torrent_provider.py
Labels: Bug, Concluded

#6835 Fix APIv2 exception while serializing allowed extensions to JSON
  CHANGELOG.md
  medusa/app.py
Labels: Bug, Concluded

#6837 Sync master develop
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/app.js.map
  themes/dark/assets/js/index.js.map
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/app.js.map
  themes/light/assets/js/index.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded

#4520 Vueify footer
  CHANGELOG.md
  medusa/server/web/core/base.py
  setup.cfg
  setup.py
  themes-default/slim/package.json
  themes-default/slim/src/app.js
  themes-default/slim/src/components/app-footer.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/global-vue-shim.js
  themes-default/slim/src/store/modules/system.js
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/__snapshots__/app-footer.spec.js.snap
  themes-default/slim/test/specs/app-footer.spec.js
  themes-default/slim/views/layouts/main.mako
  themes-default/slim/views/partials/footer.mako
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/layouts/main.mako
  themes/dark/templates/partials/footer.mako
  themes/light/assets/js/app.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/layouts/main.mako
  themes/light/templates/partials/footer.mako
Labels: Concluded, Enhancement, Frontend, Needs review

#6847 Fix pubdate should have the date parsed with the day first
  CHANGELOG.md
  medusa/providers/torrent/html/hdtorrents.py
Labels: Bug, Concluded

#6854 Fix release link on Help & Info
  CHANGELOG.md
  themes-default/slim/src/components/config.vue
  themes-default/slim/test/__fixtures__/common.json
  themes-default/slim/test/specs/__snapshots__/config.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#6846 Update Travis
  .github/build-themes-check.sh
  .travis.yml
  medusa/show_queue.py
Labels: Concluded

#6867 Fix freemobile notifier
  CHANGELOG.md
  medusa/notifiers/freemobile.py
Labels: Concluded

#6879 Fix Vue plugin registration
  themes-default/slim/src/app.js
  themes-default/slim/src/global-vue-shim.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/app.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#6880 Update AniDB component
  dredd/api-description.yml
  medusa/server/api/v2/series.py
  medusa/tv/series.py
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/anidb-release-group-ui.vue
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/test/specs/anidb-release-group-ui.spec.js
  themes-default/slim/views/editShow.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/editShow.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/editShow.mako
Labels: Backend, Concluded, Frontend

#6887 Update `eslint` config
  themes-default/slim/.eslintignore
  themes-default/slim/.eslintrc.js
  themes-default/slim/package.json
  themes-default/slim/src/app.js
  themes-default/slim/src/components/add-recommended.vue
  themes-default/slim/src/components/add-show-options.vue
  themes-default/slim/src/components/add-shows.vue
  themes-default/slim/src/components/anidb-release-group-ui.vue
  themes-default/slim/src/components/app-footer.vue
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/config.vue
  themes-default/slim/src/components/helpers/app-link.vue
  themes-default/slim/src/components/helpers/config-template.vue
  themes-default/slim/src/components/helpers/config-textbox-number.vue
  themes-default/slim/src/components/helpers/config-textbox.vue
  themes-default/slim/src/components/helpers/config-toggle-slider.vue
  themes-default/slim/src/components/helpers/file-browser.vue
  themes-default/slim/src/components/helpers/language-select.vue
  themes-default/slim/src/components/helpers/name-pattern.vue
  themes-default/slim/src/components/helpers/plot-info.vue
  themes-default/slim/src/components/helpers/quality-chooser.vue
  themes-default/slim/src/components/helpers/scroll-buttons.vue
  themes-default/slim/src/components/helpers/select-list.vue
  themes-default/slim/src/components/helpers/state-switch.vue
  themes-default/slim/src/components/irc.vue
  themes-default/slim/src/components/login.vue
  themes-default/slim/src/components/logs.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/components/sub-menu.vue
  themes-default/slim/src/components/subtitle-search.vue
  themes-default/slim/test/specs/__snapshots__/app-footer.spec.js.snap
  themes-default/slim/tsconfig.json
  themes/dark/assets/js/app.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/app.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded

#4486 Convert editShow to Vue store and SFC
  CHANGELOG.md
  medusa/server/web/home/handler.py
  medusa/server/web/manage/handler.py
  themes-default/slim/src/components/anidb-release-group-ui.vue
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/components/helpers/quality-chooser.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/router/routes.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/static/css/style.css
  themes-default/slim/views/editShow.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/editShow.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/editShow.mako
  themes/light/templates/manage_backlogOverview.mako
Labels: Concluded, Enhancement, Frontend

#6894 Fix incorrect cache image type in Series class
  medusa/server/web/home/handler.py
  medusa/server/web/manage/handler.py
  medusa/tv/series.py
Labels: Bug, Concluded

#6897 Delete .codebeatignore
  .codebeatignore
Labels: Concluded

#6899 Remove mako declarations.
  themes-default/slim/views/config_notifications.mako
  themes/dark/templates/config_notifications.mako
  themes/light/templates/config_notifications.mako
Labels: Concluded
