Repository pymedusa/Medusa, pull requests merged in 2019-07, with the labels that each got.

#6903 Use pre-compiled show slug pattern
  medusa/indexers/utils.py
Labels: Concluded, Enhancement

#6895 Push updated show via WebSocket (after saving)
  medusa/server/api/v2/series.py
  medusa/ws/__init__.py
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/store/index.js
  themes-default/slim/src/store/modules/shows.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Backend, Concluded, Enhancement, Frontend

#6900 Add property watched to episode to_json.
  dredd/api-description.yml
  medusa/tv/episode.py
Labels: Backend, Concluded

#6908 Fix select-list: Make sure we add list-items on mounted
  themes-default/slim/src/components/helpers/select-list.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#6918 Fix QualityChooser
  themes-default/slim/src/components/helpers/quality-chooser.vue
  themes-default/slim/test/specs/quality-chooser.spec.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/addShows_trendingShows.mako
  themes-default/slim/views/inc_addShowOptions.mako
  themes-default/slim/views/manage_massEdit.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/addShows_trendingShows.mako
  themes/dark/templates/inc_addShowOptions.mako
  themes/dark/templates/manage_massEdit.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/addShows_trendingShows.mako
  themes/light/templates/inc_addShowOptions.mako
  themes/light/templates/manage_massEdit.mako
Labels: Bug, Concluded, Frontend

#6852 Docker on Python 3.7
  .docker/root/etc/cont-init.d/30-config
  .docker/root/etc/services.d/medusa/run
  .dockerignore
  Dockerfile
  hooks/build
  medusa/__main__.py
  medusa/helpers/__init__.py
Labels: Do not merge, Enhancement, On hold

#6929 Fix saving release groups
  medusa/tv/series.py
Labels: Backend, Bug, Concluded

#6931 API v2 fixes
  CHANGELOG.md
  medusa/server/api/v2/base.py
  medusa/server/api/v2/log.py
Labels: Backend, Bug, Concluded

#6932 Simplify blocks yield logic for lines reader
  CHANGELOG.md
  medusa/logger/__init__.py
Labels: Bug, Concluded

#6937 Fix Guessit issue titles
  medusa/logger/__init__.py
  tests/test_logger.py
Labels: Concluded, Enhancement

#6901 Update `Series.to_json()` and `ShowHeader`
  dredd/api-description.yml
  medusa/helpers/utils.py
  medusa/scene_numbering.py
  medusa/server/api/v2/series.py
  medusa/tv/series.py
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/components/show.vue
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/static/css/style.css
  themes-default/slim/test/__fixtures__/show-detailed.json
  themes/dark/assets/css/style.css
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/css/style.css
  themes/light/assets/js/medusa-runtime.js
Labels: Backend, Concluded, Enhancement, Frontend

#6893 Update & clean up router, prepare for next stage of navigation
  themes-default/slim/src/components/helpers/app-link.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/components/sub-menu.vue
  themes-default/slim/src/router/helpers.js
  themes-default/slim/src/router/index.d.ts
  themes-default/slim/src/router/index.js
  themes-default/slim/src/router/routes.js
  themes-default/slim/src/router/sub-menus.js
  themes-default/slim/test/specs/sub-menu.spec.js
  themes-default/slim/views/manage_manageSearches.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/manage_manageSearches.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/manage_manageSearches.mako
Labels: Concluded, Enhancement, Frontend

#6940 Add ESLint rules
  themes-default/slim/.eslintrc.js
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded

#6945 Fix open file handles
  medusa/themes/base.py
Labels: Bug, Concluded
