Repository pymedusa/Medusa, pull requests merged in 2020-05, with the labels that each got.

#8058 Add feature to search by indexer id.
  CHANGELOG.md
  medusa/classes.py
  medusa/indexers/tmdb/tmdb.py
  medusa/indexers/tvdbv2/tvdbv2_api.py
  medusa/indexers/tvmaze/tvmaze_api.py
Labels: Concluded

#8114 Simplify show summary background code and style
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/static/css/dark.css
  themes-default/slim/static/css/style.css
  themes-default/slim/test/specs/__snapshots__/app-header.spec.js.snap
  themes-default/slim/views/layouts/main.mako
  themes/dark/assets/css/style.css
  themes/dark/assets/css/themed.css
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/layouts/main.mako
  themes/light/assets/css/style.css
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/layouts/main.mako
Labels: Concluded, Enhancement

#8123 bundle upgraded vendors
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  themes/dark/assets/js/vendors.js
  themes/dark/assets/js/vendors~date-fns.js
  themes/light/assets/js/vendors.js
  themes/light/assets/js/vendors~date-fns.js
Labels: Concluded

#8133 Update `tmdbsimple` to 2.2.5
  ext/readme.md
  ext/tmdbsimple/__init__.py
  ext/tmdbsimple/account.py
  ext/tmdbsimple/base.py
  ext/tmdbsimple/changes.py
  ext/tmdbsimple/configuration.py
  ext/tmdbsimple/discover.py
  ext/tmdbsimple/find.py
  ext/tmdbsimple/genres.py
  ext/tmdbsimple/movies.py
  ext/tmdbsimple/people.py
  ext/tmdbsimple/search.py
  ext/tmdbsimple/tv.py
  lib/readme.md
  medusa/indexers/tmdb/api.py
  requirements.txt
Labels: Concluded, Update dep (Py)

#8132 Use tar.gz instead of git
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded, Enhancement

#8134 Use correct version format for `vue-good-table`
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded, Update dep (JS)

#7930 Add python 2 EOL warning
  medusa/__main__.py
Labels: Discussion

#8046 Feature/vue router select show
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/components/sub-menu.vue
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/static/css/dark.css
  themes-default/slim/test/specs/__snapshots__/show-selector.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/sub-menu.spec.js.snap
  themes-default/slim/test/specs/show-selector.spec.js
  themes/dark/assets/css/themed.css
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement, Frontend

#8145 Catch exception on version check. Fixes #7997, #8005
  medusa/updater/update_manager.py
Labels: Bug, Concluded

#8152 Fix associated files matching more files than wanted. Fixes #8051
  medusa/post_processor.py
Labels: Bug, Concluded

#8155 Add scene naming support for non anime shows
  medusa/helpers/__init__.py
  medusa/name_parser/parser.py
  medusa/scene_exceptions.py
  medusa/scene_numbering.py
  tests/conftest.py
  tests/legacy/scene_helpers_tests.py
  tests/name_parser/test_parse_anime.py
  tests/name_parser/test_parse_series.py
Labels: Concluded, Enhancement
