Repository pymedusa/Medusa, pull requests merged in 2020-07, with the labels that each got.

#8243 Sort by article (The / A)
  themes-default/slim/src/components/show-list/index.vue
  themes-default/slim/src/components/show-list/poster.vue
  themes-default/slim/src/mixins/show-list.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug

#8247 Run prev_episode() and next_episode() whenever we want to get the pre…
  medusa/tv/series.py
Labels: Bug

#8258 Rework `bencodepy` integration
  medusa/clients/torrent/generic.py
  medusa/init/__init__.py
  medusa/providers/torrent/rss/rsstorrent.py
  medusa/providers/torrent/torrent_provider.py
  tests/test_init.py
Labels: Bug, Concluded

#8259 Don't empty array and add new items.
  themes-default/slim/src/store/modules/provider.js
  themes-default/slim/src/store/mutation-types.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend

#8261 Update `pytimeparse` and integrate `certgen.py` into source
  ext/pytimeparse/__init__.py
  ext/pytimeparse/timeparse.py
  ext/readme.md
  lib/pytimeparse/VERSION
  lib/pytimeparse/__init__.py
  lib/pytimeparse/tests/__init__.py
  lib/pytimeparse/tests/testtimeparse.py
  lib/readme.md
  medusa/helpers/__init__.py
  medusa/helpers/certgen.py
  requirements.txt
Labels: Enhancement

#8268 re-add horizontal-scroll class.
  themes-default/slim/src/components/show-history.vue
  themes-default/slim/src/components/show-results.vue
  themes-default/slim/test/specs/__snapshots__/show-history.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/show-results.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8270 Replace custom timed cache decorator with ttl-cache
  ext/readme.md
  ext/ttl_cache.py
  medusa/helpers/utils.py
  medusa/tv/series.py
Labels: Concluded
