Repository pymedusa/Medusa, pull requests merged in 2020-04, with the labels that each got.

#7918 Feature/guessit expected titles dash
  CHANGELOG.md
  medusa/name_parser/guessit_parser.py
Labels: Concluded

#7921 Fix home: RootDirs not always shown, due to a race condition.
  CHANGELOG.md
  themes-default/slim/src/components/home.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Fixed

#7890 Feature/season aliases
  dredd/api-description.yml
  medusa/databases/cache_db.py
  medusa/databases/main_db.py
  medusa/helpers/__init__.py
  medusa/name_cache.py
  medusa/name_parser/guessit_parser.py
  medusa/name_parser/parser.py
  medusa/providers/generic_provider.py
  medusa/scene_exceptions.py
  medusa/server/api/v2/alias.py
  medusa/tv/series.py
  setup.py
  tests/name_parser/test_parse_anime.py
  tests/test_guessit.py
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/components/helpers/config-scene-exceptions.vue
  themes-default/slim/src/components/helpers/index.js
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/store/modules/defaults.js
  themes-default/slim/src/store/modules/shows.js
  themes-default/slim/src/store/mutation-types.js
  themes-default/slim/test/__fixtures__/show-detailed.json
  themes-default/slim/test/__fixtures__/shows.json
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded

#7940 Run WindowsSelectorEventLoop event loop explicit on windows and py3.
  .travis.yml
  CHANGELOG.md
  medusa/server/core.py
Labels: Bug, Concluded

#7942 Fix setting event loop policy
  medusa/server/core.py
Labels: Concluded

#7954 Revert jQuery to v3.4.1
  renovate.json
  themes-default/slim/package.json
  themes-default/slim/src/components/config-notifications.vue
  themes-default/slim/test/specs/quality-pill.spec.js
  themes-default/slim/test/specs/state-switch.spec.js
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
Labels: Bug, Concluded

#7956 Fix size changed during iteration.
  medusa/scene_exceptions.py
Labels: Bug, Concluded

#7962 Fix schedule calendar view
  CHANGELOG.md
  themes-default/slim/views/partials/schedule/calendar.mako
  themes/dark/templates/partials/schedule/calendar.mako
  themes/light/templates/partials/schedule/calendar.mako
Labels: Bug, Concluded

#7963 Fix running of Scheduler with specific start time
  CHANGELOG.md
  medusa/scheduler.py
Labels: Bug, Concluded

#7970 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded

#7985 displayShow.vue: Debounce reflowLayout
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Enhancement, Frontend

#7989 Fix subliminal exception when passing titles that are not strings
  medusa/subtitles.py
Labels: Concluded

#7986 Add Keep link as post processing method
  CHANGELOG.md
  medusa/post_processor.py
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/test/specs/__snapshots__/config-post-processing.spec.js.snap
  themes-default/slim/views/home_postprocess.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/home_postprocess.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/home_postprocess.mako
Labels: Enhancement

#7991 Fix/privatehd login
  CHANGELOG.md
  medusa/providers/torrent/html/cinemaz.py
  medusa/providers/torrent/html/privatehd.py
Labels: Concluded

#8004 Feature/add provider eztv
  CHANGELOG.md
  dredd/dredd.yml
  medusa/providers/torrent/json/eztv.py
  setup.py
  themes-default/slim/static/images/providers/eztv.png
  themes/dark/assets/img/providers/eztv.png
  themes/light/assets/img/providers/eztv.png
Labels: Concluded

#8032 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  setup.py
  themes/dark/assets/js/medusa-runtime.js.map
  themes/dark/assets/js/vendors.js.map
  themes/dark/assets/js/vendors~date-fns.js.map
  themes/light/assets/js/medusa-runtime.js.map
  themes/light/assets/js/vendors.js.map
  themes/light/assets/js/vendors~date-fns.js.map
Labels: Concluded
