Repository pymedusa/Medusa, pull requests merged in 2020-10, with the labels that each got.

#8556 Add new property to routes.js `nocache` to make sure that edit-show.v…
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/components/helpers/config-scene-exceptions.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/router/routes.js
  themes-default/slim/views/index.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/index.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/index.mako
Labels: Concluded, Frontend

#8563 Fix torrent hash from magnet to be unicode
  CHANGELOG.md
  medusa/clients/torrent/generic.py
Labels: Bug, Concluded

#8599 Avoid exception when headers have no host
  medusa/server/web/core/base.py
Labels: Bug, Concluded

#8607 Use b64decode instead of deprecated decodestring
  medusa/server/api/v2/base.py
Labels: Bug, Concluded

#8609 Feature/provider maintenance
  CHANGELOG.md
  medusa/classes.py
  medusa/providers/torrent/html/speedcd.py
  medusa/providers/torrent/json/animebytes.py
  medusa/scene_exceptions.py
  medusa/scene_numbering.py
  medusa/server/api/v2/providers.py
  medusa/server/web/home/handler.py
Labels: Bug, Concluded, Provider

#8665 Feature/skip ep 0
  medusa/indexers/tmdb/api.py
  medusa/indexers/tvdbv2/api.py
  medusa/indexers/tvmaze/api.py
Labels: Bug, Concluded, Tmdb, Tvdb, Tvmaze
