Repository pymedusa/Medusa, pull requests merged in 2020-11, with the labels that each got.

#8675 Fix IPTorrents layout change
  medusa/providers/torrent/html/iptorrents.py
Labels: Bug, Concluded

#8711 Update eztv provider url
  medusa/providers/torrent/json/eztv.py
Labels: Concluded

#8727 Fix email/powl notifications
  medusa/notifiers/emailnotify.py
  medusa/notifiers/prowl.py
  medusa/tv/series.py
  tests/notifiers/test_emailnotify.py
Labels: Bug, Concluded

#8732 Release 0.4.5
  CHANGELOG.md
  ext/certifi/__init__.py
  ext/certifi/cacert.pem
  ext/readme.md
  medusa/common.py
  medusa/notifiers/emailnotify.py
  medusa/notifiers/prowl.py
  medusa/providers/torrent/json/eztv.py
  medusa/tv/series.py
  requirements.txt
  tests/notifiers/test_emailnotify.py
  themes-default/slim/package.json
  themes-default/slim/static/images/network/sky-atlantic-(it).png
  themes-default/slim/static/images/network/sky-atlantic-(uk).png
  themes-default/slim/yarn.lock
  themes/dark/assets/img/network/sky-atlantic-(it).png
  themes/dark/assets/img/network/sky-atlantic-(uk).png
  themes/light/assets/img/network/sky-atlantic-(it).png
  themes/light/assets/img/network/sky-atlantic-(uk).png
Labels: Concluded

#8737 Fix provider TVChaosUK
  CHANGELOG.md
  medusa/providers/torrent/html/tvchaosuk.py
  themes/dark/assets/js/vendors~date-fns.js
  themes/light/assets/js/vendors~date-fns.js
Labels: Concluded, Provider

#8753 Refactor scene exception methods
  medusa/helpers/__init__.py
  medusa/name_parser/parser.py
  medusa/queues/show_queue.py
  medusa/scene_numbering.py
  medusa/server/web/home/handler.py
  medusa/tv/episode.py
  setup.cfg
  tests/name_parser/test_parse_anime.py
Labels: Concluded, Enhancement, Needs testing

#8768 Change decode/encode string -> bytes
  lib/rtorrent/lib/xmlrpc/basic_auth.py
  medusa/helpers/__init__.py
Labels: Bug, Concluded

#8778 Add properties for scene numbering
  medusa/providers/generic_provider.py
  medusa/tv/episode.py
Labels: Concluded

#8784 Fix searching show, episodes and fanart by language code.
  CHANGELOG.md
  medusa/indexers/tmdb/api.py
  medusa/tv/series.py
Labels: Bug, Concluded
