Repository pymedusa/Medusa, pull requests merged in 2020-08, with the labels that each got.

#8281 Add support for cached season results
  medusa/search/core.py
  medusa/tv/cache.py
Labels: Concluded

#8285 Remove text filter for poster layout.
  themes-default/slim/src/components/home.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8284 Fix mapState calls in .mako templates.
  themes-default/slim/src/app.js
  themes-default/slim/src/components/config-notifications.vue
  themes-default/slim/src/components/config-search.vue
  themes-default/slim/src/global-vue-shim.js
  themes-default/slim/src/index.js
  themes-default/slim/src/store/modules/config/layout.js
  themes-default/slim/static/js/add-shows/init.js
  themes-default/slim/static/js/ajax-episode-subtitles.js
  themes-default/slim/static/js/common/init.js
  themes-default/slim/static/js/config/init.js
  themes-default/slim/views/addShows_addExistingShow.mako
  themes-default/slim/views/addShows_recommended.mako
  themes-default/slim/views/addShows_trendingShows.mako
  themes-default/slim/views/config_backuprestore.mako
  themes-default/slim/views/config_providers.mako
  themes-default/slim/views/manage_backlogOverview.mako
  themes-default/slim/views/manage_massEdit.mako
  themes-default/slim/views/restart.mako
  themes/dark/assets/js/add-shows/init.js
  themes/dark/assets/js/ajax-episode-subtitles.js
  themes/dark/assets/js/app.js
  themes/dark/assets/js/common/init.js
  themes/dark/assets/js/config/init.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/addShows_addExistingShow.mako
  themes/dark/templates/addShows_recommended.mako
  themes/dark/templates/addShows_trendingShows.mako
  themes/dark/templates/config_backuprestore.mako
  themes/dark/templates/config_providers.mako
  themes/dark/templates/manage_backlogOverview.mako
  themes/dark/templates/manage_massEdit.mako
  themes/dark/templates/restart.mako
  themes/light/assets/js/add-shows/init.js
  themes/light/assets/js/ajax-episode-subtitles.js
  themes/light/assets/js/app.js
  themes/light/assets/js/common/init.js
  themes/light/assets/js/config/init.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/addShows_addExistingShow.mako
  themes/light/templates/addShows_recommended.mako
  themes/light/templates/addShows_trendingShows.mako
  themes/light/templates/config_backuprestore.mako
  themes/light/templates/config_providers.mako
  themes/light/templates/manage_backlogOverview.mako
  themes/light/templates/manage_massEdit.mako
  themes/light/templates/restart.mako
Labels: Bug, Concluded

#8286 Add storage icon to indexer, with which the show is added to db.
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/static/images/star.png
  themes/dark/assets/img/star.png
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/img/star.png
  themes/light/assets/js/medusa-runtime.js
Labels: Enhancement, Frontend

#8289 Add season folders to default naming patterns
  themes-default/slim/src/components/config-post-processing.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#8302 Limit Python dependency versions
  renovate.json
Labels: Concluded, Update dep (Py)

#8314 By default return a list, not string.
  medusa/tv/series.py
Labels: Bug, Concluded

#8313 remove z-index.
  themes-default/slim/src/components/show-header.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#8317 Rename animeSplitHomeInTabs to splitHomeInTabs
  CHANGELOG.md
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/show-list/index.vue
  themes-default/slim/src/store/modules/config/layout.js
  themes-default/slim/test/__fixtures__/common.json
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8316 Remove forcing the scene option, when a show has scene numbering avai…
  CHANGELOG.md
  medusa/show_queue.py
Labels: Enhancement

#8320 Only on mobile: Changed all li elements to floats. So they have a hei…
  themes-default/slim/static/css/style.css
  themes/dark/assets/css/style.css
  themes/light/assets/css/style.css
Labels: Bug, Concluded

#8321 Feature/small ui fixes
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/show-list/index.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8323 Fix showlists comparing lowercase.
  themes-default/slim/src/components/home.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#8337 Feature/fix save shows showlist
  medusa/tv/series.py
  themes-default/slim/src/mixins/show-list.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8338 Fix download sort
  themes-default/slim/src/mixins/show-list.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#8348 Hide Lists title, when there is only one list (for ex. Series).
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/schedule.vue
  themes-default/slim/src/components/show-list/index.vue
  themes-default/slim/src/store/modules/shows.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend

#8395 Fix backlog search ignoring found cached results
  medusa/search/core.py
Labels: Bug

#8407 Prevent double adding show lists to show.
  themes-default/slim/src/components/edit-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8413 Fix guessit parsing numbered episode titles as multi season
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#8414 Added a select for the search actions in display-show.vue.
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/show-list/index.vue
  themes-default/slim/src/store/modules/config/layout.js
  themes-default/slim/static/css/style.css
  themes/dark/assets/css/style.css
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/css/style.css
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Enhancement

#8415 Put back in the text input for filtering by show title.
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/show-list/index.vue
  themes-default/slim/src/components/show-list/poster.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend
