Repository pymedusa/Medusa, pull requests merged in 2020-12, with the labels that each got.

#8815 Only let renovate rebase when conflicted
  renovate.json
Labels: Concluded

#8823 decode() bytes for saving into config.ini
  medusa/__main__.py
  medusa/config.py
  medusa/helpers/__init__.py
  medusa/process_tv.py
  medusa/server/web/config/general.py
  tests/test_process_tv.py
Labels: Bug, Concluded

#8846 Fix backlog search on new show add & wanted switch for old episodes
  medusa/queues/show_queue.py
  medusa/server/api/v2/search.py
Labels: Bug, Concluded

#8851 Fix exception when torrent clients don't respond
  medusa/clients/torrent/generic.py
Labels: Bug, Concluded

#8856 Feature/fix parsing anime guessit
  medusa/classes.py
  medusa/name_parser/rules/rules.py
  medusa/tv/episode.py
  medusa/tv/series.py
  tests/test_guessit.yml
Labels: Concluded, Guessit

#8882 Add Processing failed for ... to custom logs
  medusa/app.py
Labels: Concluded

#8883 Update adba
  ext/adba/aniDBAbstracter.py
  ext/readme.md
  requirements.txt
Labels: Concluded

#8884 Fix startup with git install without valid git
  medusa/__main__.py
  medusa/updater/github_updater.py
Labels: Bug, Concluded

#8918 Fix setting default episode status.
  CHANGELOG.md
  medusa/queues/show_queue.py
Labels: Bug, Concluded

#8937 Allow torrent client move when process_method is 'copy' (2)
  medusa/post_processor.py
  medusa/process_tv.py
Labels: Concluded, Enhancement
