Repository pymedusa/Medusa, pull requests merged in 2020-02, with the labels that each got.

#7699 Fix guessit parser not using scene exceptions
  CHANGELOG.md
  medusa/name_parser/guessit_parser.py
Labels: Bug, Concluded

#7708 Update report guessit to work with aliases
  CHANGELOG.md
  tests/report_guessit.py
Labels: Concluded

#7716 Release/release 0.3.12
  CHANGELOG.md
  medusa/common.py
  medusa/name_parser/guessit_parser.py
  medusa/providers/torrent/html/yggtorrent.py
  package.json
  tests/report_guessit.py
  themes-default/slim/package.json
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/test/specs/__snapshots__/config-post-processing.spec.js.snap
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js.map
  yarn.lock
Labels: Concluded

#7732 Sync develop with master
  CHANGELOG.md
  medusa/common.py
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#7717 fix wording
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/config-notifications.vue
  themes-default/slim/src/components/config-post-processing.vue
  themes-default/slim/src/components/config-search.vue
  themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/config-post-processing.spec.js.snap
  themes-default/slim/views/config_subtitles.mako
  themes-default/slim/views/manage_massEdit.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/config_subtitles.mako
  themes/dark/templates/manage_massEdit.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/config_subtitles.mako
  themes/light/templates/manage_massEdit.mako
Labels: On hold

#6896 Webpack optimization
  themes-default/slim/gulpfile.js
  themes-default/slim/package.json
  themes-default/slim/webpack.config.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
Labels: Concluded

#7736 Fix travis config warnings
  .travis.yml
Labels: Concluded

#7759 Update outdated vender libs & build
  .build/package.json
  .build/yarn.lock
  themes-default/slim/static/css/vender.min.css
  themes-default/slim/static/js/vender.js
  themes-default/slim/static/js/vender.min.js
  themes/dark/assets/css/vender.min.css
  themes/dark/assets/js/vender.js
  themes/dark/assets/js/vender.min.js
  themes/light/assets/css/vender.min.css
  themes/light/assets/js/vender.js
  themes/light/assets/js/vender.min.js
Labels: Concluded

#7790 Fix show updater not updating shows without recent updates
  medusa/__main__.py
  medusa/indexers/tvdbv2/tvdbv2_api.py
  medusa/scheduler.py
  medusa/show_updater.py
  medusa/tv/series.py
Labels: Bug, Concluded
