Repository pymedusa/Medusa, pull requests merged in 2020-09, with the labels that each got.

#8399 Fix (master/develop) branch checkout from config-general
  medusa/server/api/v2/config.py
  medusa/server/api/v2/system.py
  medusa/server/core.py
  medusa/server/web/home/handler.py
  medusa/updater/github_updater.py
  medusa/updater/version_checker.py
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/restart.vue
  themes-default/slim/src/router/routes.js
  themes-default/slim/src/style/modal.css
  themes-default/slim/src/utils/core.js
  themes-default/slim/test/specs/__snapshots__/app-header.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap
  themes-default/slim/views/restart.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/restart.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/restart.mako
Labels: Bug, Concluded

#8426 Fix show-selector.vue using the correct show lists.
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/components/show-list/index.vue
  themes-default/slim/test/__fixtures__/show-lists.json
  themes-default/slim/test/__fixtures__/shows.json
  themes-default/slim/test/specs/__snapshots__/app-header.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/show-selector.spec.js.snap
  themes-default/slim/test/specs/app-header.spec.js
  themes-default/slim/test/specs/show-selector.spec.js
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8425 Catch error for using --set-remote-to on old git installations.
  medusa/updater/github_updater.py
Labels: Concluded, Enhancement

#8432 Don't warn when using deprecated git options
  medusa/updater/github_updater.py
Labels: Concluded, Enhancement

#8437 Add component for updating.
  CHANGELOG.md
  medusa/server/api/v2/system.py
  medusa/server/web/home/handler.py
  medusa/updater/update_manager.py
  themes-default/slim/src/components/app-header.vue
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/components/restart.vue
  themes-default/slim/src/components/update.vue
  themes-default/slim/src/router/routes.js
  themes-default/slim/test/specs/__snapshots__/app-header.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Frontend

#8438 Fix shutdown
  themes-default/slim/src/components/restart.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Frontend

#8441 Limit PRs per hour to reduce Travis workload
  renovate.json
Labels: Concluded

#8460 Fix no max seasons when the show is incomplete. Fixes #8429
  medusa/post_processor.py
Labels: Concluded

#8470 Release/release 0.4.3
  CHANGELOG.md
  ext/profilehooks.py
  ext/readme.md
  ext/validators/__init__.py
  ext/validators/url.py
  medusa/common.py
  medusa/post_processor.py
  renovate.json
  requirements.txt
  themes-default/slim/package.json
  themes-default/slim/src/components/helpers/name-pattern.vue
  themes-default/slim/yarn.lock
  themes/dark/assets/js/app.js
  themes/dark/assets/js/index.js
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/vendors.js
  themes/light/assets/js/app.js
  themes/light/assets/js/index.js
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/vendors.js
Labels: Concluded

#8510 Replace unrar2 with rarfile
  lib/native/unrar-license.txt
  lib/native/windows/UnRAR.exe
  lib/readme.md
  lib/unrar2/UnRARDLL/license.txt
  lib/unrar2/UnRARDLL/unrar.dll
  lib/unrar2/UnRARDLL/unrar.h
  lib/unrar2/UnRARDLL/unrar.lib
  lib/unrar2/UnRARDLL/unrardll.txt
  lib/unrar2/UnRARDLL/whatsnew.txt
  lib/unrar2/UnRARDLL/x64/readme.txt
  lib/unrar2/UnRARDLL/x64/unrar64.dll
  lib/unrar2/UnRARDLL/x64/unrar64.lib
  lib/unrar2/__init__.py
  lib/unrar2/rar_exceptions.py
  lib/unrar2/test.rar
  lib/unrar2/unix.py
  lib/unrar2/windows.py
  medusa/init/__init__.py
  medusa/process_tv.py
  medusa/server/web/config/post_processing.py
Labels: Concluded

#8518 Fix scene exceptions with year not being used
  medusa/name_parser/guessit_parser.py
Labels: Bug, Concluded

#8535 Feature/fix notify list
  CHANGELOG.md
  medusa/server/web/home/handler.py
  medusa/tv/series.py
  themes-default/slim/src/components/helpers/select-list.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/components/sub-menu.vue
  themes-default/slim/test/specs/__snapshots__/select-list.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/sub-menu.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8543 Add EpisodeUpdater to scheduler
  medusa/__main__.py
  medusa/config.py
  medusa/queues/__init__.py
  medusa/queues/event_queue.py
  medusa/queues/generic_queue.py
  medusa/queues/show_queue.py
  medusa/queues/utils.py
  medusa/schedulers/__init__.py
  medusa/schedulers/episode_updater.py
  medusa/schedulers/scheduler.py
  medusa/schedulers/show_updater.py
  medusa/schedulers/trakt_checker.py
  medusa/schedulers/utils.py
  medusa/search/backlog.py
  medusa/search/daily.py
  medusa/search/queue.py
  medusa/server/api/v2/config.py
  medusa/server/api/v2/log.py
  medusa/system/restart.py
  medusa/system/shutdown.py
  medusa/tv/series.py
  medusa/updater/version_checker.py
  setup.cfg
  setup.py
  tests/apiv2/test_config.py
  tests/test_system.py
  themes-default/slim/src/components/logs.vue
  themes-default/slim/test/specs/__snapshots__/logs.spec.js.snap
  themes-default/slim/views/status.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/status.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/status.mako
Labels: Concluded, Enhancement

#8546 Don't strip() channel names so they are matched correctly
  medusa/network_timezones.py
Labels: Bug, Concluded

#8547 Move seasonCount to "detailed" flag.
  medusa/schedulers/episode_updater.py
  medusa/tv/series.py
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/helpers/show-selector.vue
  themes-default/slim/src/components/show-header.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement, Frontend

#8550 Fix load all episodes when user is not using pagination.
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend
