Repository pymedusa/Medusa, pull requests merged in 2021-11, with the labels that each got.

#10021 Release/release 0.5.20
  CHANGELOG.md
  medusa/common.py
  medusa/process_tv.py
  medusa/server/api/v1/core.py
  themes-default/slim/src/components/manual-post-process.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#10032 Add rule for parsin shows that begin with a number as title.
  medusa/name_parser/rules/rules.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#10070 Catch AttributeError for TVMaze API
  medusa/indexers/tvmaze/api.py
Labels: Concluded

#10092 Fixed provider morethantv
  medusa/providers/torrent/html/morethantv.py
Labels: Bug, Provider

#10116 All() should only get one value.
  medusa/scene_numbering.py
Labels: Bug, Concluded

#10126 Fix torrentday generating a JSONDecodeError
  medusa/providers/torrent/json/torrentday.py
Labels: Bug, Concluded

#10131 Fix Plex Server library update from /manage/plex
  medusa/server/api/v2/notifications.py
Labels: Bug, Concluded, Frontend
