Repository pymedusa/Medusa, pull requests merged in 2021-07, with the labels that each got.

#9685 Fix removing prowlarr provider
  themes-default/slim/src/components/helpers/config-custom-prowlarr.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9686 Added :key, to make components refresh.
  themes-default/slim/src/components/config-providers.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9691 Fix filter displayShow episodes by overview status
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9695 Feature/fix provider cookies
  medusa/providers/generic_provider.py
  medusa/server/api/v2/providers.py
  themes-default/slim/src/components/helpers/config-provider-torrent.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9698 Feature/add test provider for results
  medusa/server/api/v2/providers.py
  themes-default/slim/src/components/helpers/config-provider-nzb.vue
  themes-default/slim/src/components/helpers/config-provider-torrent.vue
  themes-default/slim/src/components/helpers/index.js
  themes-default/slim/src/components/helpers/test-provider.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#9700 Use provider name for success/error messages.
  medusa/server/api/v2/providers.py
  themes-default/slim/src/components/helpers/config-provider-nzb.vue
  themes-default/slim/src/components/helpers/config-provider-torrent.vue
  themes-default/slim/src/components/helpers/test-provider.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#9721 Feature/update abnormal
  CHANGELOG.md
  medusa/providers/torrent/html/abnormal.py
  medusa/server/api/v2/providers.py
Labels: Bug, Concluded, Provider

#9744 Put key on backstretch components
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/components/history.vue
  themes-default/slim/src/components/home.vue
  themes-default/slim/src/components/logs.vue
  themes-default/slim/src/components/schedule.vue
  themes-default/slim/src/components/schedule/calendar.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes-default/slim/src/components/status.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Frontend

#9758 Fix JWT generation for API v2
  medusa/server/api/v2/auth.py
Labels: Bug, Concluded
