Repository pymedusa/Medusa, pull requests merged in 2021-08, with the labels that each got.

#9775 Fix PP starting to pp entire download folder, when processing season packs with multiple video files.
  medusa/process_tv.py
Labels: Concluded

#9780 Improve trakt recommended list sync, exceptions and warnings/feedback.
  medusa/generic_update_queue.py
  medusa/server/api/v2/recommended.py
  medusa/show/recommendations/trakt.py
Labels: Bug, Concluded

#9778 Make the show/season/ep leading and not the release_name for the failedProcessor
  medusa/failed_processor.py
  medusa/process_tv.py
  medusa/schedulers/download_handler.py
Labels: Enhancement, Concluded

#9781 Raise InvalidNameException for unsupported release names
  medusa/name_parser/parser.py
Labels: Bug, Concluded

#9782 Fix zindex on "show plot"
  themes-default/slim/src/components/recommended-poster.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9788 Group history compact layout results by quality
  medusa/server/api/v2/history.py
Labels: Enhancement, Concluded

#9822 Fix store negative value for search delay
  medusa/server/api/v2/providers.py
  themes-default/slim/src/components/helpers/config-provider-nzb.vue
  themes-default/slim/src/components/helpers/config-provider-torrent.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded, Frontend
