Repository pymedusa/Medusa, pull requests merged in 2021-03, with the labels that each got.

#9284 Don't save removed episode location as dot
  CHANGELOG.md
  medusa/tv/episode.py
Labels: Concluded

#9285 Release/release 0.5.10
  CHANGELOG.md
  medusa/common.py
  medusa/tv/episode.py
  themes-default/slim/yarn.lock
Labels: Concluded

#9308 Apply FDH for downloads where the PP fails.
  medusa/process_tv.py
Labels: Concluded, Enhancement

#9315 Don't empty SID cookie when qbittorrent is not returning any cookies
  medusa/clients/torrent/qbittorrent.py
Labels: Bug, Concluded, Upstream

#9333 Extract download id, as primary key for result
  medusa/providers/torrent/html/nebulance.py
Labels: Concluded, Enhancement

#9356 Fix setting scene numbering from show page
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9393 Fix error with ClientStatus import
  medusa/history.py
Labels: Bug, Concluded
