Repository pymedusa/Medusa, pull requests merged in 2021-02, with the labels that each got.

#9148 Fix missing background fanart
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/snatch-selection.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9147 Use location as fallback if there is no release group for SQN
  medusa/common.py
  medusa/tv/episode.py
Labels: Concluded

#9149 Fix delete show.
  medusa/server/web/home/handler.py
Labels: Bug, Concluded

#9150 Feature/fix mobile manual search link
  themes-default/slim/src/components/display-show.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9157 Fix getManualSearchStatus when called by schedule page.
  medusa/server/web/home/handler.py
  themes-default/slim/static/js/ajax-episode-search.js
  themes/dark/assets/js/ajax-episode-search.js
  themes/light/assets/js/ajax-episode-search.js
Labels: Bug, Concluded

#9184 Fix guessit exception because of missed unique episodes detection
  CHANGELOG.md
  medusa/name_parser/rules/rules.py
Labels: Bug, Concluded

#9187 Update trakt back to pyTrakt release 2.15.0
  ext/readme.md
  ext/trakt/__init__.py
  ext/trakt/calendar.py
  ext/trakt/sync.py
  requirements.txt
Labels: Concluded, Upstream

#9198 Fix guessit exception when episode initiator is int
  medusa/name_parser/rules/rules.py
Labels: Bug, Concluded

#9199 Release/release 0.5.8
  CHANGELOG.md
  medusa/common.py
  medusa/name_parser/rules/rules.py
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
Labels: Concluded

#9200 Sync develop & master
  CHANGELOG.md
  medusa/common.py
  themes-default/slim/yarn.lock
Labels: Concluded

#9211 Feature/fix backlog show
  medusa/server/web/manage/handler.py
Labels: Bug, Concluded

#9216 Post-process fallback as anime if the show is anime
  medusa/post_processor.py
  medusa/tv/episode.py
Labels: Concluded, Enhancement

#9217 Fix duplicate loading of fanart background
  themes-default/slim/src/components/current-downloads.vue
  themes-default/slim/src/components/display-show.vue
  themes-default/slim/src/components/edit-show.vue
  themes-default/slim/src/components/history-new.vue
  themes-default/slim/src/components/logs.vue
  themes-default/slim/src/components/show-header.vue
  themes-default/slim/src/components/show-history.vue
  themes-default/slim/src/components/show-list/banner.vue
  themes-default/slim/src/components/show-list/poster.vue
  themes-default/slim/src/components/show-list/simple.vue
  themes-default/slim/src/components/show-list/smallposter.vue
  themes-default/slim/src/components/show-results.vue
  themes-default/slim/test/specs/__snapshots__/logs.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/show-history.spec.js.snap
  themes-default/slim/test/specs/__snapshots__/show-results.spec.js.snap
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#9230 Fix black rows font on some pages
  themes-default/slim/src/components/show-history.vue
  themes-default/slim/src/components/show-results.vue
  themes-default/slim/src/style/vgt-table.css
  themes-default/slim/test/specs/__snapshots__/show-results.spec.js.snap
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded

#9231 Add App.vue.
  themes-default/slim/src/components/app.vue
  themes-default/slim/src/components/index.js
  themes-default/slim/src/global-vue-shim.js
  themes-default/slim/views/index.mako
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/templates/index.mako
  themes/light/assets/js/medusa-runtime.js
  themes/light/templates/index.mako
Labels: Concluded, Enhancement

#9272 Don't force new search if results are found for newznab/torznab
  medusa/providers/nzb/newznab.py
  medusa/providers/torrent/torznab/torznab.py
Labels: Bug, Concluded

#9262 Clean downloads that cannot be located anymore on client
  medusa/clients/nzb/nzbget.py
  medusa/clients/nzb/sab.py
  medusa/clients/torrent/deluge.py
  medusa/clients/torrent/deluged.py
  medusa/clients/torrent/qbittorrent.py
  medusa/clients/torrent/rtorrent.py
  medusa/clients/torrent/transmission.py
  medusa/clients/torrent/utorrent.py
  medusa/schedulers/download_handler.py
  medusa/server/web/home/handler.py
Labels: Enhancement

#9273 Add custom url option
  medusa/providers/torrent/html/iptorrents.py
Labels: Enhancement
