Repository pymedusa/Medusa, pull requests merged in 2021-01, with the labels that each got.

#8916 Feature/replace traktor with pytrakt
  CHANGELOG.md
  ext/readme.md
  ext/trakt/__init__.py
  ext/trakt/calendar.py
  ext/trakt/core.py
  ext/trakt/errors.py
  ext/trakt/movies.py
  ext/trakt/people.py
  ext/trakt/sync.py
  ext/trakt/tv.py
  ext/trakt/users.py
  ext/trakt/utils.py
  medusa/__main__.py
  medusa/app.py
  medusa/config.py
  medusa/failed_history.py
  medusa/helpers/externals.py
  medusa/helpers/trakt.py
  medusa/naming.py
  medusa/notifiers/trakt.py
  medusa/post_processor.py
  medusa/queues/show_queue.py
  medusa/schedulers/episode_updater.py
  medusa/schedulers/trakt_checker.py
  medusa/search/core.py
  medusa/server/web/home/add_shows.py
  medusa/server/web/home/handler.py
  medusa/show/recommendations/trakt.py
  medusa/tv/episode.py
  medusa/tv/series.py
  requirements.txt
  themes-default/slim/src/components/config-notifications.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#8948 Added the CHANGE_* methods from medusa.config.py
  CHANGELOG.md
  medusa/app.py
  medusa/config.py
  medusa/server/api/v2/config.py
  medusa/server/web/config/search.py
  medusa/server/web/config/subtitles.py
  setup.py
  tests/apiv2/test_config.py
Labels: Concluded, Enhancement

#8951 Fix starting threads on startup
  medusa/app.py
Labels: Bug, Concluded

#8954 Add episode updater to the schedulers
  medusa/schedulers/utils.py
Labels: Concluded

#8956 Make real use of dirty setter
  medusa/tv/base.py
  medusa/tv/episode.py
  medusa/tv/series.py
Labels: Bug, Concluded

#8957 Move testrar() to avoid high CPU load
  medusa/process_tv.py
Labels: Concluded, Enhancement

#8958 Use setter to set episode status
  medusa/failed_history.py
  medusa/post_processor.py
  medusa/schedulers/episode_updater.py
  medusa/schedulers/trakt_checker.py
  medusa/search/core.py
  medusa/server/web/home/handler.py
  medusa/tv/episode.py
  medusa/tv/series.py
Labels: Concluded

#8960 Use bitwise-or operator, avoids dirty flag overwrite
  medusa/tv/base.py
  medusa/tv/episode.py
Labels: Concluded

#8917 Add cache for guessit
  medusa/name_parser/cache.py
  medusa/name_parser/guessit_parser.py
  medusa/name_parser/parser.py
Labels: Concluded, Enhancement

#8966 Fix setting dirty setter for properties
  medusa/search/queue.py
  medusa/server/api/v2/episodes.py
  medusa/server/web/home/handler.py
  medusa/tv/base.py
  medusa/tv/episode.py
  medusa/tv/series.py
  tests/test_guessit.py
Labels: Concluded

#8955 Add UI option saveMagnetFile
  CHANGELOG.md
  medusa/__main__.py
  medusa/app.py
  medusa/providers/generic_provider.py
  medusa/providers/torrent/html/anidex.py
  medusa/providers/torrent/torrent_provider.py
  medusa/search/core.py
  medusa/server/api/v2/config.py
  tests/apiv2/test_config.py
  themes-default/slim/src/components/config-search.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Concluded, Enhancement

#8971 Fix post-processor missing some episode attributes
  medusa/name_parser/guessit_parser.py
  medusa/name_parser/parser.py
  medusa/name_parser/rules/rules.py
  medusa/post_processor.py
  medusa/tv/episode.py
  tests/test_guessit.yml
Labels: Bug, Concluded

#8994 Fix trakt sync exception
  medusa/notifiers/trakt.py
  medusa/server/web/home/handler.py
  medusa/tv/episode.py
Labels: Bug, Concluded

#8995 Release/release 0.5.3
  CHANGELOG.md
  medusa/common.py
  medusa/notifiers/trakt.py
  medusa/server/web/home/handler.py
  medusa/tv/episode.py
  themes-default/slim/package.json
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#9018 Feature/fix trakt tv show
  ext/trakt/core.py
  medusa/__main__.py
  medusa/notifiers/trakt.py
Labels: Bug, Concluded

#9017 Remove get_scene_exceptions() call from massUpdateShow handler.
  medusa/server/web/home/handler.py
  medusa/tv/series.py
Labels: Bug, Concluded

#9038 Feature/trakt fixes
  medusa/schedulers/trakt_checker.py
  medusa/tv/episode.py
Labels: Bug, Concluded

#9047 Fix black/whitelist for new shows, refactor episodes and series attrs
  medusa/server/api/v1/core.py
  medusa/server/api/v2/series.py
  medusa/tv/episode.py
  medusa/tv/series.py
  tests/test_search_core.py
  tests/test_words.py
Labels: Bug, Concluded

#9050 Avoid exception for shows that don't have show_lists in DB
  medusa/tv/series.py
Labels: Concluded

#9057 Fix version check scheduler running twice
  .travis.yml
  medusa/app.py
  medusa/config.py
  medusa/db.py
  medusa/server/web/config/general.py
  medusa/session/core.py
  setup.cfg
  setup.py
  test_requirements.txt
Labels: Bug, Concluded

#9064 Fix setting air attr for shows
  medusa/tv/series.py
Labels: Concluded

#9062 Update validators & dogpile.cache
  ext/dogpile/__init__.py
  ext/dogpile/cache/api.py
  ext/dogpile/cache/backends/__init__.py
  ext/dogpile/cache/backends/file.py
  ext/dogpile/cache/backends/memcached.py
  ext/dogpile/cache/backends/memory.py
  ext/dogpile/cache/backends/redis.py
  ext/dogpile/cache/proxy.py
  ext/dogpile/cache/region.py
  ext/dogpile/cache/util.py
  ext/dogpile/lock.py
  ext/dogpile/util/compat.py
  ext/dogpile/util/langhelpers.py
  ext/dogpile/util/nameregistry.py
  ext/dogpile/util/readwrite_lock.py
  ext/readme.md
  ext/validators/__init__.py
  ext/validators/btc_address.py
  ext/validators/url.py
  ext/validators/uuid.py
  renovate.json
  requirements.txt
Labels: Concluded

#9080 Fix trakt recommended shows
  ext/readme.md
  ext/trakt/calendar.py
  ext/trakt/core.py
  medusa/helpers/trakt.py
  requirements.txt
Labels: Concluded

#9103 Catch attributeerror
  ext/readme.md
  ext/tvdbapiv2/rest.py
  medusa/indexers/tvmaze/api.py
  requirements.txt
Labels: Concluded, Upstream

#9088 Never use checkout on update
  medusa/updater/github_updater.py
Labels: Bug, Concluded

#9107 Fix update component flow
  CHANGELOG.md
  themes-default/slim/src/components/update.vue
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Bug, Concluded

#9121 Sync w dev
  CHANGELOG.md
  medusa/common.py
  themes-default/slim/yarn.lock
  themes/dark/assets/js/medusa-runtime.js.map
  themes/light/assets/js/medusa-runtime.js.map
Labels: Concluded

#9118 Don't use add (year) option for backend related processes
  medusa/schedulers/trakt_checker.py
  medusa/tv/series.py
  themes-default/slim/src/components/config-general.vue
  themes-default/slim/src/components/new-show.vue
  themes-default/slim/test/specs/__snapshots__/config-general.spec.js.snap
  themes/dark/assets/js/medusa-runtime.js
  themes/light/assets/js/medusa-runtime.js
Labels: Enhancement
