Repository pymedusa/Medusa, pull requests merged in 2022-06, with the labels that each got.

#10700 Feature/docker python 310
  Dockerfile
  runscripts/init.docker
Labels: Enhancement, Concluded

#10701 Use aports mirror on github to go around 429 error.
  Dockerfile
Labels: Concluded

#10708 Fix test guessit
  medusa/server/api/v2/guessit.py
Labels: Bug, Concluded, Guessit

#10709 Change log error to info.
  medusa/subtitle_providers/addic7ed.py
Labels: Enhancement

#10729 Make log debug when metadata image can't be retrieved
  medusa/helper/metadata.py
Labels: Concluded

#10771 Added check for failed logins
  medusa/subtitle_providers/addic7ed.py
  medusa/subtitle_providers/converters/addic7ed.py
Labels: Bug, Enhancement, Concluded
