Repository pymedusa/Medusa, pull requests merged in 2022-04, with the labels that each got.

#10472 Fix joining segments in log for failed episodes
  medusa/failed_processor.py
Labels: Bug, Concluded

#10466 Added Plex metadata provider
  CHANGELOG.md
  medusa/__main__.py
  medusa/app.py
  medusa/metadata/__init__.py
  medusa/metadata/generic.py
  medusa/metadata/plex.py
  medusa/server/api/v2/base.py
  setup.cfg
Labels: Concluded, Feature request

#10477 Fixed morethentv (prob layout change)
  medusa/providers/torrent/html/morethantv.py
Labels: Concluded, Provider

#10496 Add option to use the guessit parser, uncached
  medusa/name_parser/guessit_parser.py
  medusa/server/api/v2/guessit.py
  tests/test_guessit.py
  tests/test_guessit.yml
Labels: Enhancement, Concluded

#10497 Fix Plex metadata creation.
  medusa/metadata/plex.py
Labels: Bug, Concluded

#10498 Feature/trakt json errors
  medusa/helpers/externals.py
  medusa/helpers/trakt.py
  medusa/notifiers/trakt.py
  medusa/queues/show_queue.py
  medusa/schedulers/trakt_checker.py
  medusa/server/web/home/add_shows.py
  medusa/server/web/home/handler.py
  medusa/tv/series.py
Labels: Bug, Enhancement, Concluded

#10522 Fix the runs_in_docker flag.
  medusa/__main__.py
  medusa/updater/version_checker.py
Labels: Bug, Concluded

#10523 Always overwrite app.BRANCH when we have a commit_branch_env.
  medusa/__main__.py
Labels: Enhancement, Concluded

#10524 Fix isoFormat on None.
  medusa/server/api/v2/internal.py
Labels: Bug, Concluded

#10525 Fix adding older shows. With releases without a startYear.
  medusa/indexers/imdb/api.py
Labels: Bug, Concluded

#10532 Disable guessit cache for postprocessing
  medusa/failed_processor.py
  medusa/name_parser/parser.py
  medusa/post_processor.py
  medusa/process_tv.py
  tests/conftest.py
Labels: Bug, Concluded

#10533 Don't overwrite already arhived episodes when postprocessing.
  medusa/helper/exceptions.py
  medusa/post_processor.py
  medusa/process_tv.py
Labels: Enhancement, Concluded

#10541 Add config setting to allow overriding xem url.
  medusa/__main__.py
  medusa/app.py
  medusa/scene_exceptions.py
  medusa/scene_numbering.py
  medusa/tv/series.py
Labels: Enhancement, Concluded
